import json, subprocess, sys, zipfile
from pathlib import Path
import jsonschema
from ldporto.active_speaker import build_active_speaker
from ldporto.run_status import build_run_manifest
from ldporto.review_overrides import new_document, add_override, undo, redo, invalidated_stages
from ldporto.second_curation import build_second_curation_package

ROOT=Path(__file__).resolve().parents[2]

def _vision():
    return {'people':[{'person_id':'PERSON_A'}],
            'frames':[{'time':0.5,'scene_id':'S','visible_people':['PERSON_A']}],
            'scene_intervals':[{'start':0,'end':2,'scene_id':'S'}],
            'observations':[{'time':0.5,'scene_id':'S','person_id':'PERSON_A','face_visible':True,'mouth_activity':.4}]}

def test_active_speaker_v4_exposes_uncertainty_state_without_forcing_person():
    d=build_active_speaker({'turns':[{'start':0,'end':2,'speaker':'S'}]},_vision(),[],{})['data']
    assert d['intervals'][0]['person_id'] is None
    assert d['intervals'][0]['state'] in {'UNKNOWN_PERSON','NO_CLEAR_SPEAKER','INSUFFICIENT_EVIDENCE','OFFSCREEN_SPEAKER'}
    assert 'observation_age' in d['intervals'][0]

def test_causal_manifest_marks_descendants_and_first_reprocess():
    stages={'07_people_tracking':{'status':'failed'},'08_person_reid':{'status':'blocked'},'09_person_motion':{'status':'blocked'},'12_camera_timeline':{'status':'blocked'}}
    m=build_run_manifest({'sha256':'a'*64,'analyzer_version':'4.0.0'},stages,[])
    assert m['root_cause_stage']=='07_people_tracking'
    assert '12_camera_timeline' in m['descendants_affected']
    assert m['first_stage_to_reprocess']=='07_people_tracking'

def test_review_overrides_are_non_destructive_and_dependency_aware():
    d=add_override(new_document(),'speaker_person_mapping',1,2,{'speaker':'S','person':'P'})
    assert 'camera_director' in invalidated_stages(d)
    u=undo(d); assert not u['overrides'] and u['redo_stack']
    r=redo(u); assert r['overrides'][0]['origin']=='manual'

def test_second_curation_is_grounded_in_real_ids():
    a={'analysis_status':'complete','words':[{'word_id':'W1','word':'Olá','start':1,'end':1.4}],
       'transcript_segments':[{'segment_id':'SEG1','start':1,'end':2,'speaker':'S','text':'Olá mundo.'}],
       'editorial_moments':[{'moment_id':'M1','start':1,'end':2,'possible_start':1,'possible_end':2,'standalone_class':'good'}],
       'active_speaker':[{'start':1,'end':2,'person_id':'P','state':'KNOWN_PERSON'}],
       'camera_plan':{'selected_global_path':[{'planner_id':'PLAN1','start':1,'end':2}]},
       'camera_director_timeline':[{'director_id':'D1','start':1,'end':2,'layout':'full_frame'}],
       'shots':[{'shot_id':'SHOT1','start':1,'end':2}], 'questions_answers':[], 'story_arcs':[], 'thumbnail_candidates':[],
       'analysis_quality':{'missing_capabilities':[]},'issues':[]}
    p=build_second_curation_package(a)
    c=p['candidates'][0]
    assert c['word_ids']==['W1'] and c['evidence_references']['planner_ids']==['PLAN1'] and c['evidence_references']['director_ids']==['D1']

def test_new_contract_schemas_accept_minimal_examples():
    examples={
      'camera_plan.schema.json':{'schema_version':'4.0','profile':'natural','selected_global_path':[],'candidate_states':[],'hard_constraints':[],'metrics':{},'planner_version':'4.0.0'},
      'preview_validation.schema.json':{'schema_version':'1.0','issues':[],'verifier_uses_rendered_frames':True},
      'second_curation_package.schema.json':{'schema_version':'2.0','candidate_count':0,'candidates':[],'resolvable_index':{}},
      'review_overrides.schema.json':{'schema_version':'1.0','overrides':[],'redo_stack':[]},
      'run_manifest.schema.json':{'schema_version':'1.0','run_id':'x','analysis_status':'complete','stage_status':{},'modules_still_valid':[]},
    }
    for name,value in examples.items():
        schema=json.loads((ROOT/'schemas'/name).read_text())
        jsonschema.validate(value,schema)

# Generated by GitHub Copilot - Oct-05-2026
def test_work_package_has_single_derived_manifest_files(tmp_path):
    """Check canonical packaging without legacy scripts or virtual environments."""
    subprocess.run([sys.executable,str(ROOT/'exportar_ldporto.py'),'--root',str(ROOT),
                    '--mode','project','--output-dir',str(tmp_path)],
                   check=True,capture_output=True,text=True)
    packages=list(tmp_path.glob('LDPORTO_PROJETO_ATUAL_*.zip'))
    assert len(packages)==1
    with zipfile.ZipFile(packages[0]) as z:
        names=z.namelist()
        for name in ('.package/PROJECT_EXPORT_MANIFEST.json','.package/PROJECT_EXPORT_TREE.txt','.package/PROJECT_EXPORT_README.txt'):
            assert names.count(name)==1
        assert not any(name.startswith('PROJECT_EXPORT_') for name in names)
        assert len(names)==len(set(names))
        assert len(names)==len({name.casefold() for name in names})
        assert not any('.venv' in Path(name).parts for name in names)
        assert 'pack_ldporto_for_work.py' not in names

def test_person_motion_subtracts_global_source_camera_translation():
    from ldporto.person_motion import build_person_motion
    vision={'observations':[
      {'time':0.0,'person_id':'P','track_id':'T','scene_id':'S','center':{'x':.40,'y':.50},'face_area':.04,'source_camera_motion':None},
      {'time':1.0,'person_id':'P','track_id':'T','scene_id':'S','center':{'x':.45,'y':.50},'face_area':.04,
       'source_camera_motion':{'dx':.05,'dy':0.0,'confidence':1.0}},
    ]}
    p=build_person_motion(vision,{'smoothing_alpha':1.0,'deadzone_per_second':.001,'max_gap_seconds':1.5})['data']['people'][0]
    s=p['samples'][1]
    assert abs(s['observed_velocity_x']-.05)<1e-9
    assert abs(s['source_camera_velocity_x']-.05)<1e-9
    assert s['residual_velocity_x']==0.0
