from pathlib import Path
import ast
import copy
import hashlib
import json
import logging
import shutil
import subprocess
import sys
import pytest
import jsonschema
from director_fixtures import fixture, turn
from ldporto.config import load_config
from ldporto.core import Context, ok, write_json, read_json
from ldporto.director_config import DEFAULTS, resolve_config
from ldporto.director_integration import run_director_stage, resume_director
from ldporto.camera_director import build_camera_director
from ldporto.visual_sampling import SamplingScheduler

ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.parametrize('key,value', [(k, 'invalid') for k in DEFAULTS if k != 'profile'])
def test_every_config_field_validated(key, value):
    with pytest.raises(ValueError):
        resolve_config({key: value})


@pytest.mark.parametrize('config', [{'profile': []}, {'tick_seconds': 0}, {'output_width': 1.2},
    {'enter_confidence': .2, 'exit_confidence': .8}, {'min_hold_seconds': 7},
    {'max_zoom_hard': 1.1}, {'lookahead_seconds': 100}, {'headroom': .5},
    {'max_pan_speed': 10}, {'debug_output': 'false'}, {'wat': 1}])
def test_config_relations_and_bounds(config):
    with pytest.raises(ValueError):
        resolve_config(config)


def test_director_cache_scoped_and_resume(tmp_path, monkeypatch):
    m, v, shots = fixture(12)
    cfg = load_config()
    logger = logging.getLogger('cache')
    ctx = Context(Path('absent video.mp4'), tmp_path, cfg, 'sha', logger)
    raw = [turn(0, 12)]
    d = run_director_stage(ctx, m, v, shots, raw, [], {}, {})
    key = ctx.states['19_camera_director']['key']
    import ldporto.director_integration as integration
    original = integration.build_camera_director
    monkeypatch.setattr(integration, 'build_camera_director', lambda *a, **kw: pytest.fail('Director cache missed'))
    ctx2 = Context(ctx.video, tmp_path, cfg, 'sha', logger)
    assert run_director_stage(ctx2, m, v, shots, raw, [], {}, {}) == d
    assert ctx2.states['19_camera_director']['key'] == key
    monkeypatch.setattr(integration, 'build_camera_director', original)
    cfg['camera_director']['profile'] = 'podcast'
    ctx3 = Context(ctx.video, tmp_path, cfg, 'sha', logger)
    run_director_stage(ctx3, m, v, shots, raw, [], {}, {})
    assert ctx3.states['19_camera_director']['key'] != key
    # Real change to input evidence invalidates Director independently of profile.
    previous = ctx3.states['19_camera_director']['key']
    raw[0]['confidence'] = .2
    ctx4 = Context(ctx.video, tmp_path, cfg, 'sha', logger)
    run_director_stage(ctx4, m, v, shots, raw, [], {}, {})
    assert ctx4.states['19_camera_director']['key'] != previous


def test_schemas_and_interval_invariants():
    m, v, shots = fixture(19.1, pair=True, distant=True, cuts=(5.3, 11.9))
    d = build_camera_director(m, v, shots, [turn(0, 19.1, overlap=True),turn(0, 19.1, 'PERSON_B', overlap=True)], [], {})['data']
    jsonschema.validate(d['timeline'], read_json(ROOT/'schemas/camera_director_timeline.schema.json'))
    jsonschema.validate(d['debug'], read_json(ROOT/'schemas/camera_director_debug.schema.json'))
    json.dumps(d, allow_nan=False)
    last = 0
    for r in d['timeline']:
        assert abs(r['start']-last) < 1e-7
        assert r['start'] < r['end'] <= m['duration']
        shot = next(s for s in shots if s['shot_id'] == r['source_shot_id'])
        assert shot['start'] <= r['start'] < r['end'] <= shot['end']
        assert r['focus_person'] is None or r['focus_person'] in r['visible_people']
        if r['split']:
            assert {r['split']['left_person'],r['split']['right_person']} <= set(r['visible_people'])
        last = r['end']
    assert last == m['duration']


def test_bats_real_crlf_and_python311_syntax():
    for path in ROOT.glob('*.bat'):
        data = path.read_bytes()
        assert b'\r\n' in data
        assert b'\n' not in data.replace(b'\r\n',b'')
        assert b'\r\r\n' not in data
    # Generated by GitHub Copilot - Oct-05-2026
    for path in [*ROOT.glob('*.py'),*(ROOT/'src').rglob('*.py'),*(ROOT/'scripts').rglob('*.py')]:
        ast.parse(path.read_text(encoding='utf-8-sig'), filename=str(path), feature_version=(3,11))


def test_dynamic_sampling_changes_without_second_pass():
    scheduler = SamplingScheduler(load_config()['vision'])
    fast, why = scheduler.frequency(0, speaking=True, speaker='A', boundary=True, motion=0, visible_count=1, mouth_count=1)
    stable, why = scheduler.frequency(3, speaking=True, speaker='A', boundary=False, motion=0, visible_count=1, mouth_count=1)
    motion, why = scheduler.frequency(4, speaking=True, speaker='A', boundary=False, motion=.2, visible_count=1, mouth_count=1)
    assert fast > stable and motion == fast
    assert 'high_motion' in why


def test_real_legacy_sample_can_be_read_without_inventing_evidence():
    sample = ROOT/'src/tests/fixtures/legacy_analysis'
    insights = read_json(sample/'llm_insights.json')
    words = read_json(sample/'words.json')
    legacy = read_json(sample/'timeline.json')
    # Use only timestamps/boxes actually included in the legacy sample.
    frames, observations = {}, {}
    for r in legacy:
        t = r.get('visual_observed_at')
        if t is None:
            continue
        frames[t] = {'time': t, 'scene_id': r.get('scene_id'), 'visible_people': r['visible_people']}
        for o in r.get('people_positions', []):
            observations[(t, o['person_id'])] = {**o,'time': t,'scene_id': r.get('scene_id'),
                                                 'face_visible': bool(o.get('face_bbox'))}
    scenes = read_json(sample/'scenes.json')
    shots = [{**s, 'shot_id': 'LEGACY_'+s['scene_id'], 'shot_type': s.get('scene_type','unknown')} for s in scenes]
    v = {'frames': list(frames.values()), 'observations': list(observations.values())}
    d = build_camera_director(insights['video'],v,shots,[],[],{},insights.get('questions_answers',[]))
    assert words and len(legacy) > 0
    assert not read_json(sample/'speakers.json')
    assert not any(r['focus_person'] for r in d['data']['timeline'])
    assert not any(r['split'] for r in d['data']['timeline'])
    assert d['status'] in ('partial','unavailable')
    json.dumps(d, allow_nan=False)


def make_media(path):
    subprocess.run(['ffmpeg','-hide_banner','-loglevel','error','-y',
        '-f','lavfi','-i','color=c=navy:s=640x360:r=10:d=4',
        '-f','lavfi','-i','sine=frequency=440:sample_rate=16000:duration=4',
        '-c:v','mpeg4','-c:a','aac','-shortest',str(path)],check=True)


def test_full_pipeline_cache_and_director_only_without_media(tmp_path, monkeypatch):
    from ldporto import pipeline
    video = tmp_path/'Vídeo com espaço.mp4'
    make_media(video)
    transcript = tmp_path/'anotação.json'
    write_json(transcript, {'words':[{'word':'Teste.', 'start':0.,'end':1.,'confidence':1.}]})
    cfg = load_config()
    cfg['transcription'].update(import_file=str(transcript))
    cfg['diarization']['enabled'] = False
    cfg['scenes']['enabled'] = False
    # Generated by GitHub Copilot - Oct-05-2026
    cfg['vision'].update(enabled=False,body_detection=False,active_speaker=False)
    cfg['semantic_analysis']['backend'] = 'heuristic'
    cfg['understanding']['extract_frames'] = False
    output = tmp_path/'Resultados com espaço'
    folder, analysis = pipeline.analyze(str(video),cfg,output)
    assert (folder/'camera_director_timeline.json').is_file()
    before = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in folder.glob('*.json')
              if p.name in ('words.json','caption_segments.json','speakers.json','people_observations.json')}
    states = copy.deepcopy(analysis['stage_status'])
    def forbidden(*a,**kw):
        pytest.fail('Heavy upstream stage reran for Director-only configuration change')
    monkeypatch.setattr(pipeline, 'extract_audio', forbidden)
    monkeypatch.setattr(pipeline.TranscriptionEngine, 'run', forbidden)
    monkeypatch.setattr(pipeline.VisionEngine, 'run', forbidden)
    cfg['camera_director']['profile'] = 'podcast'
    _, second = pipeline.analyze(str(video),cfg,output)
    assert all(states[k] == second['stage_status'][k] for k in states if k not in ('18b_global_camera_planner','19_camera_director','19b_preview_verifier','20_handoff'))
    video.unlink()  # The isolated operation must work even when source media is gone.
    monkeypatch.setattr(pipeline, 'resolve_input', forbidden)
    cfg['camera_director']['profile'] = 'natural'
    _, resumed = resume_director(output,cfg)
    assert resumed['camera_director_config']['profile'] == 'natural'
    handoff = read_json(folder/'CHATGPT_ANALYSIS_HANDOFF.json')
    assert handoff['camera_director_schema_version'] == '3.0'
    assert handoff['camera_director_timeline'] == resumed['camera_director_timeline']
    assert all(hashlib.sha256((folder/k).read_bytes()).hexdigest() == v for k,v in before.items())
    cfg['camera_director']['enabled'] = False
    _, disabled = resume_director(output,cfg)
    assert disabled['stage_status']['19_camera_director']['status'] == 'skipped'
    assert not disabled['camera_director_timeline']
    assert not (folder/'camera_director_debug.json').exists()
    assert 'director_switches_per_minute' not in disabled['analysis_quality']
    manifest = read_json(folder/'manifest.json')
    assert all((folder/p).is_file() for p in manifest['files'])


def test_synthetic_visual_fixture_can_be_generated_and_decoded(tmp_path):
    import importlib.util
    import cv2
    spec = importlib.util.spec_from_file_location('generate_fixture', ROOT/'scripts/generate_director_fixture.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    path = module.generate(tmp_path/'visual fixture')
    cap = cv2.VideoCapture(str(path))
    count = 0
    while cap.read()[0]:
        count += 1
    cap.release()
    assert count == 96
    artifact = read_json(path.parent/'synthetic_annotations.json')
    assert artifact['synthetic']
    d = build_camera_director(artifact['metadata'],artifact['vision'],artifact['shots'],artifact['active_speaker'],[],{})
    assert all(r['layout']=='full_frame' for r in d['data']['timeline'] if r['start']>=16)


def test_global_planner_is_deterministic_and_prefers_stay_put():
    from ldporto.global_camera_planner import build_global_camera_plan
    m, v, shots = fixture(12, pair=True)
    camera = []
    for i in range(12):
        camera.append({
            "start": float(i), "end": float(i+1), "shot_id": shots[0]["shot_id"],
            "shot_type": "two_shot", "active_person": "PERSON_A" if i < 6 else "PERSON_B",
            "active_person_confidence": .9, "visible_people": ["PERSON_A","PERSON_B"],
            "speech_overlap": False, "vertical_crop": {"recommended_layout":"single_person"}
        })
    cfg = load_config()["camera_director"]
    one = build_global_camera_plan(m, v, shots, camera, cfg)["data"]
    two = build_global_camera_plan(m, v, shots, camera, cfg)["data"]
    assert one == two
    assert one["selected_global_path"]
    assert one["metrics"]["expected_switches"] <= 3
    assert one["schema_version"] == "4.0"


def test_global_planner_rejects_unsafe_split_and_keeps_source_available():
    from ldporto.global_camera_planner import build_global_camera_plan
    m, v, shots = fixture(4, pair=True, distant=True)
    camera = [{"start":0.,"end":4.,"shot_id":shots[0]["shot_id"],"shot_type":"two_shot",
               "active_person":None,"active_person_confidence":None,"visible_people":["PERSON_A","PERSON_B"],
               "speech_overlap":True,"vertical_crop":{"recommended_layout":"split_candidate"}}]
    plan = build_global_camera_plan(m, v, shots, camera, load_config()["camera_director"])["data"]
    assert any(s["state"] == "SOURCE_FULL_FRAME" for s in plan["candidate_states"][0]["states"])
    assert all(r["start"] < r["end"] for r in plan["selected_global_path"])


def test_preview_renderer_and_verifier_use_rendered_frames(tmp_path):
    from ldporto.preview_renderer import render_preview, select_canary_intervals
    from ldporto.preview_verifier import verify_preview
    video = tmp_path/'preview source.mp4'
    make_media(video)
    metadata = {"duration":4.0,"width":640,"height":360,"fps":10.0,"rotation":0}
    timeline = [{
        "schema_version":"3.0","director_id":"DIRECTOR_000000","start":0.0,"end":4.0,
        "layout":"full_frame","focus_person":None,"split":None,"focus_confidence":None,
        "camera":{"transition_in":"initial","keyframes":[
            {"time":0.0,"center":[.5,.5],"zoom":1.0,"velocity":[0,0,0]},
            {"time":4.0,"center":[.5,.5],"zoom":1.0,"velocity":[0,0,0]}]},
        "crop":{"rect_end":None}
    }]
    canaries = select_canary_intervals(timeline, 4.0, 2, 2.0)
    assert canaries
    out = tmp_path/'preview.mp4'
    rendered = render_preview(video,timeline,metadata,out,{"start":0.0,"end":2.0},180,320)
    assert rendered["status"] == "ok" and out.is_file()
    checked = verify_preview(out,{"width":180,"height":320,"duration":2.0},timeline)
    assert checked["data"]["verifier_uses_rendered_frames"] is True
    assert checked["data"]["output_dimensions"] == [180,320]
