"""Synthetic camera continuity and rendered-preview failure regressions."""

from pathlib import Path
from types import SimpleNamespace
from director_fixtures import fixture, turn
from ldporto.camera_director import build_camera_director
from ldporto.global_camera_planner import build_global_camera_plan
from ldporto.analysis_quality import camera_quality_metrics
from ldporto.config import load_config


# Generated by GitHub Copilot - Oct-05-2026
def test_a_40_b_1_a_avoids_ping_pong():
    """One-second interruption with observed return need not create A-B-A crops."""
    metadata, vision, shots = fixture(50, pair=True)
    active = [turn(0, 40), turn(40, 41, "PERSON_B"), turn(41, 50)]
    timeline = [{"start": interval["start"], "end": interval["end"], "shot_id": shots[0]["shot_id"],
                 "shot_type": "two_shot", "active_person": interval["person_id"], "active_person_confidence": .95,
                 "speech_overlap": False, "vertical_crop": {"recommended_layout": "single_person"}} for interval in active]
    config = load_config()["camera_director"]
    plan = build_global_camera_plan(metadata, vision, shots, timeline, config)["data"]
    director = build_camera_director(metadata, vision, shots, active, [], config, camera_plan=plan)["data"]
    assert not any(row["focus_person"] == "PERSON_B" for row in director["timeline"] if 40 <= row["start"] < 41)
    assert plan["metrics"]["micro_interruption_windows"] == 1


# Generated by GitHub Copilot - Oct-05-2026
def test_temporal_coverage_does_not_imply_resolved_focus():
    """A full source timeline can have zero intelligent/resolved-focus coverage."""
    metrics = camera_quality_metrics([{"start": 0, "end": 10, "layout": "full_frame", "focus_person": None}], 10)
    assert metrics["timeline_temporal_coverage"] == 1
    assert metrics["resolved_focus_coverage"] == 0
    assert metrics["source_preservation_fraction"] == 1


# Generated by GitHub Copilot - Oct-05-2026
def test_failed_repair_render_never_reports_ok(tmp_path, monkeypatch):
    """A missing repaired preview cannot masquerade as zero validation issues."""
    from ldporto import preview_integration as preview
    from ldporto.core import ok
    calls = []
    def render(*args, **kwargs):
        """Make first render succeed and the repair render fail."""
        calls.append(True)
        return ok({}, "ok" if len(calls) == 1 else "unavailable")
    monkeypatch.setattr(preview, "render_preview", render)
    monkeypatch.setattr(preview, "verify_preview", lambda *args, **kwargs: ok(
        {"sampled_frames": 1, "verifier_uses_rendered_frames": True,
         "issues": [{"severity": "error", "issue_type": "FACE_OR_HEAD_CLIPPED"}]}, "partial"))
    timeline = [{"director_id": "D", "start": 0, "end": 4, "layout": "single_person", "focus_person": "P"}]
    result = preview.build_preview_package(SimpleNamespace(video=Path("fixture.mp4"), output=tmp_path),
        {"duration": 4}, {"timeline": timeline}, {"enabled": True, "max_canaries": 1, "canary_seconds": 4,
         "output_width": 180, "output_height": 320, "max_repair_iterations": 1})
    assert result["status"] != "ok"
    assert not result["data"]["closed_loop"]["repair_accepted"]
    assert result["data"]["repaired_timeline"] is None


# Generated by GitHub Copilot - Oct-05-2026
def test_skipped_preview_does_not_claim_visual_validation(tmp_path):
    """Disabled canaries explicitly expose that no rendered frame was inspected."""
    from ldporto.preview_integration import build_preview_package
    result = build_preview_package(SimpleNamespace(output=tmp_path), {}, {}, {"enabled": False})
    assert result["status"] == "skipped"
    assert result["data"]["validation"]["verifier_uses_rendered_frames"] is False


# Generated by GitHub Copilot - Oct-05-2026
def test_motion_flow_uses_elapsed_sample_time_not_stride_multiplier(tmp_path,monkeypatch):
    """A known flow fixture uses fps/stride; no neural motion-accuracy claim."""
    import cv2
    import numpy as np
    from ldporto.preview_verifier import verify_preview
    video=tmp_path/'flow fixture.mp4'
    writer=cv2.VideoWriter(str(video),cv2.VideoWriter_fourcc(*'mp4v'),10,(320,180))
    assert writer.isOpened()
    try:
        for index in range(20):
            writer.write(np.full((180,320,3),150,dtype=np.uint8))
    finally:
        writer.release()
    def unit_horizontal_flow(previous,current,*args):
        """Return one pixel displacement per pair of sampled frames."""
        flow=np.zeros((*previous.shape,2),dtype=np.float32)
        flow[:,:,0]=1
        return flow
    monkeypatch.setattr(cv2,'calcOpticalFlowFarneback',unit_horizontal_flow)
    result=verify_preview(video,{'width':320,'height':180,'duration':2},[{'start':0,'end':2,'layout':'full_frame'}])['data']
    assert result['estimated_pan_flow_peak_px_per_second']==10