"""Deterministic readiness fixtures, not hardware/model validation."""

import json
import sys
import pytest
from ldporto.config import load_config
from ldporto.core import scrub, write_json
from ldporto import preflight


# Generated by GitHub Copilot - Oct-05-2026
def minimal_config(tmp_path, monkeypatch):
    """Use an imported synthetic transcript with all optional capabilities disabled."""
    cfg = load_config()
    transcript = tmp_path / "transcript.json"
    write_json(transcript, {"words": []})
    cfg["transcription"]["import_file"] = str(transcript)
    for name in ("diarization", "vision", "scenes", "ocr", "audio_events"):
        cfg[name]["enabled"] = False
    cfg["preview"]["enabled"] = False
    cfg["semantic_analysis"]["backend"] = "heuristic"
    monkeypatch.setattr(preflight.shutil, "which", lambda name: "fixture/" + name)
    return cfg


# Generated by GitHub Copilot - Oct-05-2026
def test_disabled_optional_features_do_not_fail(tmp_path, monkeypatch):
    """Missing optional packages must not block an explicitly disabled feature."""
    cfg = minimal_config(tmp_path, monkeypatch)
    monkeypatch.setattr(preflight, "_import_check", lambda *args: pytest.fail("disabled dependency probed"))
    report = preflight.require_preflight(cfg, tmp_path / "output")
    assert report["ready"]
    assert report["capabilities"]["diarization"]["status"] == "DISABLED"
    assert report["runtime_target_match"] == (sys.platform == "win32" and sys.version_info[:2] == (3, 11))


# Generated by GitHub Copilot - Oct-05-2026
def test_enabled_diarization_missing_dependency_blocks_before_media(tmp_path, monkeypatch):
    """Reproduce a missing pyannote failure before even resolving the input."""
    from ldporto import pipeline
    cfg = minimal_config(tmp_path, monkeypatch)
    cfg["diarization"]["enabled"] = True
    monkeypatch.setattr(preflight, "_import_check", lambda *args: {"ok": False, "error": "fixture missing dependency"})
    monkeypatch.setattr(preflight, "_model_access", lambda cfg: {"ok": False, "token_present": False})
    monkeypatch.setattr(pipeline, "resolve_input", lambda *args: pytest.fail("expensive input path reached"))
    with pytest.raises(preflight.PreflightError, match="diarization"):
        pipeline.analyze("https://invalid.example/video", cfg, tmp_path / "output")


# Generated by GitHub Copilot - Oct-05-2026
def test_enabled_active_speaker_missing_mediapipe_fails(tmp_path, monkeypatch):
    """A real import failure, not only package discovery, must fail readiness."""
    cfg = minimal_config(tmp_path, monkeypatch)
    cfg["vision"].update(enabled=True, active_speaker=True, body_detection=False)
    monkeypatch.setattr(preflight, "_import_check", lambda name, cfg: {"ok": name != "mediapipe"})
    report = preflight.run_preflight(cfg, tmp_path)
    assert not report["ready"]
    assert not report["capabilities"]["vision"]["checks"]["mediapipe"]["ok"]


# Generated by GitHub Copilot - Oct-05-2026
def test_token_values_never_enter_preflight_report(tmp_path, monkeypatch):
    """Only presence is observable; fabricated credentials stay in memory."""
    cfg = minimal_config(tmp_path, monkeypatch)
    fake = "hf_" + "a" * 30
    monkeypatch.setenv("HF_TOKEN", fake)
    report = preflight.run_preflight(cfg, tmp_path)
    assert fake not in json.dumps(report)
    assert fake not in scrub("access denied " + fake)
    assert "sk-" + "b" * 30 not in scrub("sk-" + "b" * 30)


# Generated by GitHub Copilot - Oct-05-2026
def test_import_errors_are_scrubbed_and_never_repair_global_python(monkeypatch):
    """Missing native dependencies cannot leak credentials or alter global Python."""
    fake = "hf_" + "c" * 30
    def failing_import(name):
        """Model a loader failure containing an untrusted credential string."""
        raise ImportError(fake)
    monkeypatch.setattr(preflight.importlib, "import_module", failing_import)
    cfg = load_config()
    cfg["preflight"]["allow_self_repair"] = True
    monkeypatch.setattr(preflight.sys, "prefix", preflight.sys.base_prefix)
    monkeypatch.setattr(preflight.subprocess, "run", lambda *args, **kwargs: pytest.fail("global repair attempted"))
    result = preflight._import_check("mediapipe", cfg)
    assert not result["ok"] and fake not in json.dumps(result)


# Generated by GitHub Copilot - Oct-05-2026
def test_normal_install_includes_enabled_extras_and_models(tmp_path, monkeypatch):
    """Inspect the real installer command path with isolated subprocess fixtures."""
    import importlib.util
    from pathlib import Path
    from types import SimpleNamespace
    spec = importlib.util.spec_from_file_location("installer", Path(__file__).resolve().parents[2] / "install.py")
    installer = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(installer)
    monkeypatch.setattr(installer, "ROOT", tmp_path)
    monkeypatch.setattr(installer.sys, "version_info", (3, 11, 9))
    monkeypatch.setattr(installer.sys, "argv", ["install.py"])
    monkeypatch.setattr(installer.platform, "architecture", lambda: ("64bit", ""))
    monkeypatch.setattr(installer.venv.EnvBuilder, "create", lambda *args: None)
    monkeypatch.setattr(installer.subprocess, "run", lambda *args, **kwargs: SimpleNamespace(stdout="3.11\n"))
    commands = []
    monkeypatch.setattr(installer, "run", lambda args: commands.append([str(value) for value in args]))
    installer.main()
    installs = next(command for command in commands if any(value.endswith("requirements.txt") for value in command))
    assert any(Path(value).as_posix().endswith("requirements/diarization.txt") for value in installs)
    assert any(Path(value).as_posix().endswith("requirements/vision.txt") for value in installs)
    assert any(command[-1].endswith("download_models.py") for command in commands)
    assert not any(Path(value).as_posix().endswith("requirements/ocr.txt") for value in installs)


# Generated by GitHub Copilot - Oct-05-2026
def test_full_local_model_files_still_require_actual_model_load(tmp_path,monkeypatch):
    """A directory with plausible filenames cannot pretend to be a usable pipeline."""
    cfg=load_config()
    cfg['offline']=True
    model=tmp_path/'model'
    model.mkdir()
    (model/'config.yaml').write_text('fixture',encoding='utf-8')
    (model/'pytorch_model.bin').write_bytes(b'fixture')
    cfg['diarization']['model']=str(model)
    monkeypatch.setattr(preflight,'validate_pipeline_model',lambda cfg: {'ok':False,'model_load':'fixture-failed'})
    result=preflight._model_access(cfg)
    assert result['cached_model'] and not result['ok']
    assert result['model_load']=='fixture-failed'


# Generated by GitHub Copilot - Oct-05-2026
def test_auto_device_does_not_mask_nvidia_cuda_failure(tmp_path,monkeypatch):
    """A NVIDIA machine with broken CT2/DLLs cannot silently switch to CPU."""
    from ldporto import gpu_runtime,ollama_local
    cfg=minimal_config(tmp_path,monkeypatch)
    cfg['transcription']['import_file']=None
    monkeypatch.setattr(preflight,'_import_check',lambda *args:{'ok':True})
    monkeypatch.setattr(gpu_runtime,'ctranslate2_cuda_info',lambda:{'device_count':0,'dll_status':{'status':'missing'}})
    monkeypatch.setattr(ollama_local,'nvidia_smi',lambda:{'available':True,'gpus':[{'name':'fixture'}]})
    report=preflight.run_preflight(cfg,tmp_path)
    assert not report['capabilities']['asr']['checks']['cuda']['ok']
    cfg['device']='cpu'
    assert preflight.run_preflight(cfg,tmp_path)['capabilities']['asr']['checks']['cuda']['ok']


# Generated by GitHub Copilot - Oct-05-2026
def test_waveform_diarization_diagnoses_unused_decoder_without_blocking(tmp_path,monkeypatch):
    """An unused file decoder does not mask the required pyannote/model load checks."""
    from types import SimpleNamespace
    cfg=minimal_config(tmp_path,monkeypatch)
    cfg['diarization']['enabled']=True
    monkeypatch.setattr(preflight,'_import_check',lambda name,cfg:{'ok':name!='torchcodec'})
    monkeypatch.setattr(preflight,'_model_access',lambda cfg:{'ok':True,'model_load':'fixture_verified'})
    monkeypatch.setitem(sys.modules,'torch',SimpleNamespace(cuda=SimpleNamespace(is_available=lambda:False)))
    report=preflight.run_preflight(cfg,tmp_path)
    capability=report['capabilities']['diarization']
    assert capability['status']=='READY'
    assert capability['checks']['torchcodec']['ok'] is False
    assert capability['checks']['torchcodec']['required'] is False