"""Synthetic editorial contracts; no claim of human-labelled accuracy."""

import pytest
from ldporto.editorial import (normalize_context, classify_content, require_pt_br,
                              rank_candidate, deduplicate_candidates, topic_hierarchy)


# Generated by GitHub Copilot - Oct-05-2026
@pytest.mark.parametrize("legacy,expected", [(None, "unresolved"), ("", "unresolved"), ("null", "unresolved"),
                                            ("none", "none"), ("n\u00e3o", "none"), ("Nenhum", "none"),
                                            ("Precisa conhecer a pergunta anterior", "required")])
def test_context_is_normalized_to_strict_enum(legacy, expected):
    """Historical representations cannot remain arbitrary control values."""
    assert normalize_context({"context_required": legacy})["context_requirement"] == expected


# Generated by GitHub Copilot - Oct-05-2026
def test_clearly_english_metadata_is_rejected():
    """Detect wrong-language prose without translating literal transcript."""
    with pytest.raises(ValueError, match="language_mismatch"):
        require_pt_br(["This is the story about their lives and why they were successful."])
    assert require_pt_br(["O trecho conta uma historia sobre a carreira do convidado."])


# Generated by GitHub Copilot - Oct-05-2026
def candidate(mid, start=0, end=60, text="Historia da carreira musical.", ids=None):
    """Build a compact deterministic candidate with explicit observed components."""
    return {"moment_id": mid, "ideal_start": start, "ideal_end": end,
            "core_moment": {"start": start, "end": end, "text": text},
            "evidence_segment_ids": ids or ["S1"], "standalone_score": .8, "hook_score": .7,
            "clean_opening": True, "clean_ending": True, "duration_suitability_score": 1,
            "context_requirement": "none", **classify_content(text,ids or ["S1"])}


# Generated by GitHub Copilot - Oct-05-2026
def test_ads_are_penalized_but_brand_discussion_is_not():
    """Default ranking excludes a sales read, not ordinary noncommercial interviews."""
    ad = rank_candidate(candidate("AD", text="Compre na loja por apenas R$ 99. Aproveite o cupom e desconto!"))
    interview = rank_candidate(candidate("INTERVIEW", text="A carreira musical mudou depois da gravacao do album."))
    assert ad["content_type"] == "advertisement"
    assert ad["penalties"]["commercial"] > 0 and not ad["default_shortlist_eligible"]
    assert interview["penalties"]["commercial"] == 0 and interview["default_shortlist_eligible"]
    assert interview["score_components"]["audio_quality"] is None
    assert ad["editorial_score_final"] < interview["editorial_score_final"]


# Generated by GitHub Copilot - Oct-05-2026
def test_exact_duplicate_keeps_stronger_primary_and_alternate():
    """Preserve source IDs and evidence while collapsing identical intervals."""
    first, second = rank_candidate(candidate("M1")), rank_candidate(candidate("M2"))
    second["editorial_score_final"] = 1.0
    result, metrics = deduplicate_candidates([first, second])
    assert len(result) == 1 and result[0]["moment_id"] == "M2"
    assert result[0]["alternates"][0]["moment_id"] == "M1"
    assert metrics["exact_duplicate_count"] == 1


# Generated by GitHub Copilot - Oct-05-2026
def test_high_equivalent_overlap_dedups_but_distinct_ideas_survive():
    """Temporal overlap alone cannot erase a different grounded editorial idea."""
    first = rank_candidate(candidate("M1", 0, 60))
    same = rank_candidate(candidate("M2", 3, 63))
    distinct = rank_candidate(candidate("M3", 4, 64, "Pesquisa espacial e descoberta cientifica.", ["S_OTHER"]))
    result, metrics = deduplicate_candidates([first, same, distinct])
    assert len(result) == 2 and metrics["high_overlap_merge_count"] == 1


# Generated by GitHub Copilot - Oct-05-2026
def test_identical_ideal_interval_preserves_different_cores_as_alternates():
    """The same media window is one primary while each editorial core remains accessible."""
    first=rank_candidate(candidate('M1',0,60,'Carreira musical e gravacao.',['S1']))
    second=rank_candidate(candidate('M2',0,60,'Pesquisa cientifica e instrumentos.',['S2']))
    result,metrics=deduplicate_candidates([first,second])
    assert len(result)==1 and metrics['exact_duplicate_count']==1
    assert result[0]['alternates'][0]['evidence_segment_ids']==['S2']


# Generated by GitHub Copilot - Oct-05-2026
def test_keyword_soup_is_not_primary_theme():
    """Heuristic generic labels remain unresolved rather than claiming main topic."""
    rows = [{"topic_id": "T", "start": 0, "end": 10, "topic": "gente entao fazer era deixa",
             "method": "temporal_windows_and_keywords", "evidence_segment_ids": ["S"]}]
    _, sections, primary, _, quality = topic_hierarchy(rows, [{"segment_id": "S", "text": "Fala sobre carreira."}])
    assert primary is None and sections
    assert quality["primary_theme_status"] == "unresolved_no_qualified_theme"


    # Generated by GitHub Copilot - Oct-05-2026
    def test_program_section_groups_related_fine_topics_without_aliasing():
        """Coarse sections can contain multiple distinct, adjacent evidence topics."""
        topics=[{'topic_id':'T1','start':0,'end':10,'topic':'Carreira musical gravacao','method':'ollama','evidence_segment_ids':['S1']},
            {'topic_id':'T2','start':10,'end':20,'topic':'Carreira musical instrumentos','method':'ollama','evidence_segment_ids':['S2']}]
        merged,sections,_,_,_=topic_hierarchy(topics,[{'segment_id':'S1','text':'Carreira musical.'},{'segment_id':'S2','text':'Instrumentos musicais.'}])
        assert len(merged)==2 and len(sections)==1
        assert sections[0]['topic_ids']==['T1','T2']


# Generated by GitHub Copilot - Oct-05-2026
def test_question_without_speaker_is_not_answered_qa():
    """Punctuation remains a detected question, not a fabricated answer pair."""
    from ldporto.semantic import questions_answers, qa_contract
    rows = [{"segment_id": "Q", "start": 0, "end": 2, "speaker": None, "text": "Como gravou o album?"},
            {"segment_id": "A", "start": 2, "end": 5, "speaker": None, "text": "Gravei o album no estudio."}]
    contract = qa_contract(questions_answers(rows))
    assert contract["qa_metrics"]["question_candidate_count"] == 1
    assert contract["qa_metrics"]["answered_question_count"] == 0
    assert contract["question_candidates"][0]["association_status"] == "unresolved"


# Generated by GitHub Copilot - Oct-05-2026
def test_speaker_transition_with_relevant_complete_answer_is_pair():
    """A pair has actual answer span, lexical relevance and speaker transition."""
    from ldporto.semantic import questions_answers, qa_contract
    rows = [{"segment_id": "Q", "start": 0, "end": 2, "speaker": "HOST", "text": "Como gravou o album?"},
            {"segment_id": "A", "start": 2, "end": 5, "speaker": "GUEST", "text": "Gravei o album no estudio."}]
    contract = qa_contract(questions_answers(rows))
    assert contract["qa_metrics"]["complete_qa_count"] == 1
    assert contract["question_answer_pairs"][0]["answer_segment_ids"] == ["A"]


# Generated by GitHub Copilot - Oct-05-2026
@pytest.mark.parametrize("word", ["N\u00e3o", "Ele", "Era", "Deixa"])
def test_common_words_are_not_entities(word):
    """Reject exact false positives found in the real benchmark without quoting it."""
    from ldporto.understanding import extract_entities
    data = {"segments": [{"segment_id": "S", "start": 0, "end": 2, "text": f"O programa {word}. Eu sou {word}."}]}
    assert extract_entities(data) == []


# Generated by GitHub Copilot - Oct-05-2026
def test_multisection_arcs_do_not_require_old_regex_markers():
    """Ground discussion candidates and leave payoff unresolved when not evidenced."""
    from ldporto.understanding import build_story_arcs
    rows = [{"segment_id": f"S{index}", "start": index * 5, "end": (index + 1) * 5,
             "text": "Estudamos instrumentos e gravacao musical."} for index in range(6)]
    topics = [{"topic_id": "T1", "start": 0, "end": 15, "topic": "Instrumentos", "evidence_segment_ids": ["S0", "S1", "S2"]},
              {"topic_id": "T2", "start": 15, "end": 30, "topic": "Gravacao", "evidence_segment_ids": ["S3", "S4", "S5"]}]
    arcs = build_story_arcs({"segments": rows}, topics)
    assert len(arcs) == 2
    assert all(arc["payoff"] is None and arc["standalone_score"] is None for arc in arcs)
    assert set(arcs[0]["evidence_segment_ids"]) == {"S0", "S1", "S2"}


# Generated by GitHub Copilot - Oct-05-2026
def model_fixture():
    """Supply structurally valid PT-BR metadata based on existing source IDs only."""
    from ldporto.semantic import METRICS
    return {"locale": "pt-BR", "topics": [{"topic": "Carreira musical", "summary": "Fala sobre gravacao.",
             "segment_ids": ["S"], "context_required": "none"}],
            "moments": [{"segment_ids": ["S"], "categories": ["educational"], "reason": "O trecho aborda gravacao.",
             "standalone_class": "good", "context_required": "none", "editorial": {key: None for key in METRICS}}]}


# Generated by GitHub Copilot - Oct-05-2026
def semantic_context(tmp_path, monkeypatch):
    """Build a model-free context with explicit mocked Ollama availability."""
    import logging
    from ldporto.config import load_config
    from ldporto.core import Context
    from ldporto import semantic
    cfg = load_config()
    cfg["semantic_analysis"].update(backend="ollama", global_review=False)
    monkeypatch.setattr(semantic, "ollama_service_info", lambda *args, **kwargs: {"reachable": True, "models": [{"name": "qwen3:14b", "digest": "fixture"}]})
    transcript = {"segments": [{"segment_id": "S", "start": 0, "end": 10, "speaker": None, "text": "A gravacao foi feita no estudio."}]}
    return Context(tmp_path / "no_media.mp4", tmp_path, cfg, "synthetic", logging.getLogger("semantic-fixture")), transcript


# Generated by GitHub Copilot - Oct-05-2026
def test_llm_cannot_invent_ids_timestamps_or_nonfinite_scores():
    """Strict schema and evidence grounding reject invented control-plane data."""
    from ldporto.semantic import ground_model_output
    rows = [{"segment_id": "S", "start": 0, "end": 10, "text": "A gravacao foi feita no estudio.", "speaker": None}]
    valid = model_fixture()
    assert ground_model_output(valid, rows, 0)["moments"][0]["start"] == 0
    valid["moments"][0]["start"] = 999
    with pytest.raises(Exception):
        ground_model_output(valid, rows, 0)
    valid = model_fixture()
    valid["topics"][0]["segment_ids"] = ["INVENTED"]
    with pytest.raises(ValueError):
        ground_model_output(valid, rows, 0)
    valid = model_fixture()
    valid["moments"][0]["editorial"]["clarity"] = float("nan")
    with pytest.raises(ValueError):
        ground_model_output(valid, rows, 0)


# Generated by GitHub Copilot - Oct-05-2026
def test_semantic_has_one_repair_and_honest_fallback(tmp_path, monkeypatch):
    """Failed repairs remain visible in denominator and fallback metrics."""
    from ldporto import semantic
    ctx, transcript = semantic_context(tmp_path, monkeypatch)
    invalid = model_fixture()
    invalid["topics"][0]["segment_ids"] = ["BAD"]
    calls = {"initial": 0, "repair": 0}
    def initial(*args):
        """Return one invalid model response."""
        calls["initial"] += 1
        return invalid, {}
    def repair(*args):
        """Return an invalid repair to exercise fallback accounting."""
        calls["repair"] += 1
        return invalid, {}
    monkeypatch.setattr(semantic, "call_ollama", initial)
    monkeypatch.setattr(semantic, "repair_ollama_output", repair)
    result = semantic.SemanticEngine().run(ctx, transcript)["data"]
    assert calls == {"initial": 1, "repair": 1}
    assert result["semantic_metrics"]["semantic_fallback_ratio"] == 1
    assert result["ollama_calls"][0]["repair_attempted"] and not result["ollama_calls"][0]["repair_success"]


# Generated by GitHub Copilot - Oct-05-2026
def test_semantic_cache_resume_and_corruption_recompute(tmp_path, monkeypatch):
    """Checksummed chunks resume deterministically and corrupted chunks recompute."""
    from ldporto import semantic
    from ldporto.core import write_json
    ctx, transcript = semantic_context(tmp_path, monkeypatch)
    calls = []
    monkeypatch.setattr(semantic, "call_ollama", lambda *args: (calls.append(True) or model_fixture(), {}))
    first = semantic.SemanticEngine().run(ctx, transcript)["data"]
    second = semantic.SemanticEngine().run(ctx, transcript)["data"]
    assert len(calls) == 1 and first["moments"] == second["moments"]
    assert second["semantic_metrics"]["semantic_cache_hit_ratio"] == 1
    cache = next((ctx.cache / "semantic_chunks").glob("*.json"))
    write_json(cache, {"version": "4.2", "key": "corrupted", "data": {}})
    third = semantic.SemanticEngine().run(ctx, transcript)["data"]
    assert len(calls) == 2 and third["moments"] == first["moments"]


# Generated by GitHub Copilot - Oct-05-2026
def test_global_review_cannot_mix_literal_or_evidence_ids():
    """Generated copy is allowed; falsely-labelled literal transcript is rejected."""
    from ldporto.semantic import validate_global_review
    candidates = [{"moment_id": "M", "text": "A gravacao foi feita no estudio.", "evidence_segment_ids": ["S"]}]
    data = {"locale": "pt-BR", "overview": "O trecho aborda gravacao.", "notes": [], "content_angles": [],
            "top_moments": [{"moment_id": "M", "editorial_score": .5, "why": "O trecho mostra o relato sobre gravacao.",
             "hook_text": "Uma gravacao memoravel", "title_idea": "A historia do estudio", "context_note": "Sem contexto adicional.",
             "evidence_segment_ids": ["S"], "literal_excerpt": "A gravacao foi feita no estudio."}]}
    assert validate_global_review(data, candidates)
    data["top_moments"][0]["literal_excerpt"] = "Uma fala que nunca foi dita."
    with pytest.raises(ValueError, match="Citacao"):
        validate_global_review(data, candidates)


# Generated by GitHub Copilot - Oct-05-2026
def test_global_review_payload_includes_topics_in_budget(monkeypatch):
    """The complete user/system text, not only candidate snippets, obeys max_chars."""
    from ldporto import semantic
    from ldporto.config import load_config
    cfg=load_config()['semantic_analysis']
    cfg['global_max_chars']=12000
    moments=[{'moment_id':f'M{index}','start':index*10,'end':index*10+10,'text':'A historia da gravacao musical. '*40,
              'evidence_segment_ids':[f'S{index}'],'editorial':{},'categories':[]} for index in range(20)]
    topics=[{'topic_id':f'T{index}','start':index*10,'end':index*10+10,'topic':'Gravacao musical','summary':'Contexto musical. '*40} for index in range(20)]
    calls=[]
    def chat(url,model,messages,schema,config):
        """Capture the actual request without network inference."""
        calls.append(messages)
        return {'locale':'pt-BR','overview':'O trecho fala sobre gravacao musical.','top_moments':[],
                'content_angles':[],'notes':[]},{}
    monkeypatch.setattr(semantic,'ollama_chat',chat)
    semantic.call_global_review(cfg,topics,moments)
    assert calls and sum(len(message['content']) for message in calls[0])<=cfg['global_max_chars']


# Generated by GitHub Copilot - Oct-05-2026
def test_thumbnails_prioritize_editorial_timing_not_fragmented_ids():
    """A new raw identity alone is not a thumbnail/editorial relevance signal."""
    from ldporto.understanding import build_thumbnail_candidates
    vision={'thumbnails':[{'time':0,'path':'raw.jpg','reason':'new_person'},
                          {'time':1,'path':'early.jpg','reason':'scene_start'},
                          {'time':100,'path':'candidate.jpg','reason':'scene_start'}],
            'observations':[],'people':[]}
    moments=[{'moment_id':'M','ideal_start':90,'ideal_end':110}]
    result=build_thumbnail_candidates(vision,[],80,moments)
    assert result[0]['path']=='candidate.jpg'
    assert result[0]['editorial_moment_ids']==['M']
    assert 'raw.jpg' not in {row['path'] for row in result}