"""Synthetic timestamp, diarization and identity regression evidence."""

from copy import deepcopy
import pytest
from ldporto.transcription import validate_import, normalize_asr_timestamps, annotate_review, alternative_evidence
from ldporto.diarization import align_speakers, overlap_intervals


# Generated by GitHub Copilot - Oct-05-2026
@pytest.mark.parametrize("times", [(float("nan"), 1), (0, float("inf")), (2, 1), (0, 0)])
def test_import_rejects_invalid_word_times(times):
    """Imported timestamps must be finite, positive-duration evidence."""
    with pytest.raises(ValueError):
        validate_import({"words": [{"word": "teste", "start": times[0], "end": times[1]}]}, 5)


# Generated by GitHub Copilot - Oct-05-2026
def test_import_rejects_overlap_and_out_of_segment_word():
    """Sorting cannot hide an overlap or a reference outside segment boundaries."""
    with pytest.raises(ValueError):
        validate_import({"words": [{"word": "a", "start": 0, "end": 2}, {"word": "b", "start": 1, "end": 3}]}, 5)
    with pytest.raises(ValueError):
        validate_import({"words": [{"word": "teste", "start": 1, "end": 3, "segment_id": "S"}],
                         "segments": [{"segment_id": "S", "start": 1, "end": 2, "text": "teste"}]}, 5)


# Generated by GitHub Copilot - Oct-05-2026
def test_asr_timing_repair_preserves_raw_evidence():
    """ASR anomalies are visible and repaired intervals never overlap."""
    original = [{"word": "a", "start": 0, "end": 1, "confidence": .9},
                {"word": "b", "start": .8, "end": 2, "confidence": .4},
                {"word": "c", "start": float("nan"), "end": 3}]
    words, anomalies, unaligned = normalize_asr_timestamps(original, 5)
    assert words[1]["start"] == words[0]["end"]
    assert words[1]["raw_start"] == .8
    assert len(anomalies) == 2 and len(unaligned) == 1
    assert original[1]["start"] == .8
    data = {"words": words}
    annotate_review(data, .6)
    assert words[1]["needs_review"]


# Generated by GitHub Copilot - Oct-05-2026
def test_repetition_region_is_not_mislabeled_low_model_probability():
    """Review flags and model probability thresholds represent different quantities."""
    from ldporto.transcription import transcription_metrics
    words=[{'word':'repeticao','word_id':f'W{index}','start':index,'end':index+.5,'confidence':.95} for index in range(6)]
    data={'words':words}
    annotate_review(data,.6)
    metrics=transcription_metrics(data,8)
    assert metrics['suspected_hallucination_region_count']==1
    assert metrics['low_confidence_word_count']==0
    assert metrics['review_needed_word_count']>0


# Generated by GitHub Copilot - Oct-05-2026
def test_low_confidence_alternatives_do_not_replace_canonical_words():
    """A higher model probability alone is not independent correctness evidence."""
    hypothesis = {"words": [{"word": "inventado", "start": 0, "end": 1, "confidence": .99}]}
    evidence = alternative_evidence(hypothesis, 0, 2)
    assert evidence["mean_model_probability"] == .99
    assert not evidence["replacement_permitted"]
    data = {"words": [{"word": "literal", "start": 0, "end": 1, "confidence": .2}]}
    annotate_review(data, .6)
    assert data["words"][0]["word"] == "literal" and data["words"][0]["needs_review"]


# Generated by GitHub Copilot - Oct-05-2026
def test_exclusive_alignment_keeps_overlap_evidence():
    """Community-1 exclusive turns align words; normal overlapping turns survive."""
    transcript = validate_import({"words": [{"word": "Ola.", "start": 1, "end": 2}]}, 5)
    diarization = {"turns": [{"start": 0, "end": 3, "speaker": "A"}, {"start": 1, "end": 2, "speaker": "B"}],
                   "exclusive_turns": [{"start": 0, "end": 1, "speaker": "A"}, {"start": 1, "end": 2, "speaker": "B"}],
                   "speakers": [{"speaker_id": "A"}, {"speaker_id": "B"}]}
    diarization["overlaps"] = overlap_intervals(diarization["turns"])
    before = deepcopy(diarization["turns"])
    aligned = align_speakers(transcript, diarization)
    assert aligned["words"][0]["speaker"] == "B"
    assert aligned["words"][0]["speech_overlap"]
    assert aligned["words"][0]["speaker_assignment_method"] == "exclusive_temporal_alignment"
    assert diarization["turns"] == before and diarization["overlaps"]


# Generated by GitHub Copilot - Oct-05-2026
def test_missing_diarization_never_invents_speaker():
    """Imported/transcribed words remain anonymous without acoustic evidence."""
    transcript = validate_import({"words": [{"word": "Ola.", "start": 0, "end": 1}]}, 3)
    aligned = align_speakers(transcript, {})
    assert aligned["words"][0]["speaker"] is None
    assert aligned["segments"][0]["speaker"] is None


# Generated by GitHub Copilot - Oct-05-2026
def track_fixture(specifications):
    """Construct detector tracklets with explicit synthetic face evidence."""
    rows = []
    for track_id, source_id, start, end, embedding in specifications:
        for time in (start, (start + end) / 2, end):
            rows.append({"track_id": track_id, "person_id": source_id, "time": time,
                         "scene_id": "SCENE_" + str(int(start)), "face_visible": True,
                         "face_embedding": embedding, "tracking_method": "temporal_iou"})
    return {"observations": rows, "people": [{"person_id": row["person_id"]} for row in rows],
            "frames": [{"time": row["time"], "visible_people": [row["person_id"]]} for row in rows]}


# Generated by GitHub Copilot - Oct-05-2026
def test_strong_face_evidence_merges_across_cuts():
    """The Re-ID stage actually merges separate online-tracker identities."""
    from ldporto.person_reid import build_person_identities
    vision = track_fixture([("T1", "P1", 0, 2, [1, 0]), ("T2", "P2", 5, 7, [1, 0])])
    data = build_person_identities(vision)["data"]
    assert len(data["identities"]) == 1
    assert data["metrics"]["reid_merge_count"] == 1
    assert data["tracklet_to_person"]["T1"] == data["tracklet_to_person"]["T2"]


# Generated by GitHub Copilot - Oct-05-2026
def test_simultaneous_faces_never_merge():
    """Even identical synthetic embeddings cannot merge simultaneous people."""
    from ldporto.person_reid import build_person_identities
    data = build_person_identities(track_fixture([("T1", "P1", 0, 2, [1, 0]), ("T2", "P2", 0, 2, [1, 0])]))["data"]
    assert len(data["identities"]) == 2
    assert data["metrics"]["simultaneous_identity_conflict_count"] > 0


# Generated by GitHub Copilot - Oct-05-2026
def test_same_screen_location_without_embedding_stays_uncertain():
    """Continuity across cuts requires facial evidence, not matching geometry."""
    from ldporto.person_reid import build_person_identities
    data = build_person_identities(track_fixture([("T1", "P1", 0, 2, None), ("T2", "P2", 5, 7, None)]))["data"]
    assert len(data["identities"]) == 2
    assert all(person["reid_confidence"] is None for person in data["identities"])
    assert all(not decision["accepted"] for decision in data["merge_decisions"])


# Generated by GitHub Copilot - Oct-05-2026
def test_microtracks_do_not_explode_participants():
    """Hundreds of 0.2s tracks remain raw evidence instead of participants."""
    from ldporto.person_reid import build_person_identities, apply_person_identities
    from ldporto.understanding import build_participants
    vision = track_fixture([(f"T{index}", f"P{index}", index, index + .2, None) for index in range(100)])
    data = build_person_identities(vision)["data"]
    persistent = apply_person_identities(vision, data)
    assert data["metrics"]["raw_track_count"] == 100
    assert data["metrics"]["micro_track_count"] == 100
    assert not persistent["people"]
    assert len(persistent["tracklet_observations"]) == 300
    assert build_participants({"segments": []}, {"speakers": []}, persistent, [], []) == []


# Generated by GitHub Copilot - Oct-05-2026
def test_editorial_speaker_remains_participant_without_visible_person():
    """An offscreen acoustic participant is valid without inventing visual identity."""
    from ldporto.understanding import build_participants
    participants = build_participants({"segments": []}, {"speakers": [{"speaker_id": "S", "speech_seconds": 10}]}, {"people": []}, [], [])
    assert participants[0]["person_id"] is None
    assert participants[0]["status"] == "confirmed_editorial_participant"
    assert participants[0]["role"] == "unknown"


# Generated by GitHub Copilot - Oct-05-2026
def test_missing_visual_observations_do_not_fabricate_zero_age():
    """No contemporary sample is an unknown age, not perfect zero-latency evidence."""
    from ldporto.active_speaker import build_active_speaker
    result=build_active_speaker({'turns':[{'start':0,'end':2,'speaker':'S'}]},
        {'people':[],'frames':[],'observations':[]},[],{})['data']
    assert result['metrics']['observation_age_mean'] is None
    assert result['metrics']['observation_age_p95'] is None