@echo off
chcp 65001 >nul
cd /d "%~dp0"
if not exist ".venv\Scripts\python.exe" (
  echo Execute INSTALAR_WINDOWS.bat primeiro.
  pause
  exit /b 1
)
REM Generated by GitHub Copilot - Oct-05-2026
REM Modelos Ollama de outras sessoes nao sao encerrados por este launcher.
".venv\Scripts\python.exe" app.py
if errorlevel 1 pause
