#!/usr/bin/env python3
import argparse
import importlib.util
import json
import os
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT/"src"))


def configure_path():
    local_ffmpeg = ROOT/"tools"/"ffmpeg"/"bin"
    if local_ffmpeg.is_dir():
        os.environ["PATH"] = str(local_ffmpeg)+os.pathsep+os.environ.get("PATH", "")
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    # Register NVIDIA DLL folders from pip wheels before importing CTranslate2.
    try:
        from ldporto.gpu_runtime import configure_windows_nvidia_runtime
        configure_windows_nvidia_runtime()
    except Exception:
        pass


# Generated by GitHub Copilot - Oct-05-2026
def doctor(cfg):
    """Use the same enabled-capability readiness gate as an actual analysis."""
    import platform
    from ldporto.preflight import run_preflight
    from ldporto.core import versions, sanitize_json_numbers
    report = run_preflight(cfg)
    disk = shutil.disk_usage(ROOT)
    report.update(os=platform.platform(), architecture=platform.machine(), dependencies=versions(),
                  disk={"free_bytes": disk.free, "total_bytes": disk.total},
                  base_ready=report["ready"], ffmpeg=shutil.which("ffmpeg"), ffprobe=shutil.which("ffprobe"),
                  hf_token_configured=bool(os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")),
                  notes=["Python 3.11.x e Windows 10/11 continuam sendo o alvo de homologacao.",
                         "runtime_target_match=false nao valida nem reprova a compatibilidade com Python 3.11.",
                         "Recursos habilitados indisponiveis nao sao rebaixados silenciosamente."])
    print(json.dumps(sanitize_json_numbers(report), ensure_ascii=False, indent=2, allow_nan=False))
    return 0 if report["ready"] else 2


# Generated by GitHub Copilot - Oct-05-2026
def main():
    """Run the shared pipeline or readiness/camera-only routes with secret-safe errors."""
    configure_path()
    parser = argparse.ArgumentParser(description="L.D.PORTO VIDEO ANALYZER - analise local, sem renderizar cortes.")
    parser.add_argument("source", nargs="?", help="Caminho de video ou URL do YouTube")
    parser.add_argument("--output", help="Pasta de saida; padrao analysis/NOME_HASH/")
    parser.add_argument("--config", default=str(ROOT / "config" / "config.yaml"))
    parser.add_argument("--device", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--model", help="Modelo faster-whisper ou diretorio CTranslate2 local")
    parser.add_argument("--offline", action="store_true")
    parser.add_argument("--force", action="store_true", help="Reexecutar etapas e invalidar cache")
    parser.add_argument("--doctor", action="store_true", help="Diagnosticar ambiente")
    parser.add_argument("--strict", action="store_true", help="Falhar se uma etapa opcional nao puder executar")
    parser.add_argument("--import-transcript", help="JSON com words/segments e tempos absolutos")
    parser.add_argument("--no-vision", action="store_true")
    parser.add_argument("--no-diarization", action="store_true")
    parser.add_argument("--semantic", choices=["heuristic", "ollama"])
    parser.add_argument("--ollama-model", help="Modelo local do Ollama, ex.: qwen3:8b")
    parser.add_argument("--ollama-profile", choices=["fast", "balanced", "max"], help="Perfil Ollama")
    parser.add_argument("--camera-profile", choices=["natural", "podcast", "dynamic_short", "documentary", "conservative"])
    parser.add_argument("--no-camera-director", action="store_true")
    parser.add_argument("--preview", action="store_true", help="Renderizar e validar canarios tecnicos")
    parser.add_argument("--director-only", metavar="PASTA", help="Reprocessar apenas Director a partir de analysis.json")
    parser.add_argument("--camera-min-hold", type=float)
    parser.add_argument("--camera-max-zoom", type=float)
    args = parser.parse_args()
    try:
        from ldporto.config import load_config, configure_local_mode, validate
        cfg = load_config(args.config)
        if args.device:
            cfg["device"] = args.device
        if args.model:
            cfg["transcription"]["model"] = args.model
        cfg["offline"] = cfg["offline"] or args.offline
        cfg["strict"] = cfg["strict"] or args.strict
        if args.import_transcript:
            cfg["transcription"]["import_file"] = str(Path(args.import_transcript).resolve())
        if args.no_vision:
            cfg["vision"]["enabled"] = False
        if args.no_diarization:
            cfg["diarization"]["enabled"] = False
        if args.semantic:
            cfg["semantic_analysis"]["backend"] = args.semantic
        if args.ollama_model:
            cfg["semantic_analysis"]["model"] = args.ollama_model
        if args.ollama_profile:
            cfg["semantic_analysis"]["profile"] = args.ollama_profile
        if args.camera_profile:
            cfg["camera_director"]["profile"] = args.camera_profile
        if args.no_camera_director:
            cfg["camera_director"]["enabled"] = False
        if args.preview:
            cfg["preview"]["enabled"] = True
        if args.camera_min_hold is not None:
            cfg["camera_director"]["min_hold_seconds"] = args.camera_min_hold
        if args.camera_max_zoom is not None:
            cfg["camera_director"]["max_zoom_default"] = args.camera_max_zoom
        validate(cfg)
        configure_local_mode(cfg)
        if args.director_only:
            from ldporto.director_integration import resume_director
            folder, analysis = resume_director(args.director_only, cfg, args.force)
            print("Camera Director:", folder / "camera_director_timeline.json")
            return 0
        if args.doctor:
            return doctor(cfg)
        if not args.source:
            parser.error("Informe um arquivo/URL ou use --doctor.")
        from ldporto.pipeline import analyze
        folder, analysis = analyze(args.source, cfg, args.output, args.force)
        print("\nConcluido:", analysis["analysis_status"])
        counts = [
            "Palavras: " + str(len(analysis["words"])),
            "Locutores acusticos: " + str(len(analysis["speakers"])),
            "Tracks brutos: " + str(len(analysis.get("raw_tracks", []))),
            "Identidades persistentes: " + str(len(analysis["people"])),
            "Participantes editoriais: " + str(len(analysis.get("participants", []))),
            "Limites visuais: " + str(len(analysis["scenes"])),
        ]
        print(" | ".join(counts))
        print("Qualidade:", analysis.get("quality_gate", {}).get("status", "not_measured"))
        print("Para enviar ao ChatGPT:", folder / "CHATGPT_ANALYSIS_HANDOFF.compact.json")
        print("Para revisar:", folder / "report.html")
        return 0
    except KeyboardInterrupt:
        print("\nInterrompido. Checkpoints concluidos foram preservados.", file=sys.stderr)
        return 130
    except Exception as exc:
        from ldporto.core import scrub
        print("\nERRO:", scrub(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
