"""Small native local launcher; runs the same CLI in a child process."""
import os
from pathlib import Path
import queue
import shutil
import subprocess
import sys
import threading
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import webbrowser

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT/"src"))


class App:
    def __init__(self, window):
        self.window, self.proc, self.messages, self.output_folder = window, None, queue.Queue(), None
        window.title("L.D.PORTO VIDEO ANALYZER")
        window.geometry("1060x840")
        window.configure(bg="#17171b")
        style = ttk.Style()
        style.theme_use("clam")
        style.configure("TFrame", background="#17171b")
        style.configure("TLabel", background="#17171b", foreground="#eeeeee")
        style.configure("TCheckbutton", background="#17171b", foreground="#eeeeee")
        # Generated by GitHub Copilot - Oct-05-2026
        style.map('TButton',background=[('focus','#4c4c59')],foreground=[('focus','#ffffff')])
        style.map('TCheckbutton',background=[('focus','#3c3c49')])
        outer = ttk.Frame(window, padding=24)
        outer.pack(fill="both", expand=True)
        ttk.Label(outer, text="L.D.PORTO · VIDEO ANALYZER", font=("Segoe UI", 24, "bold"),
                  foreground="#fb505a").pack(anchor="w")
        ttk.Label(outer, text="Vídeo inteiro → transcrição → pessoas → timeline → insights",
                  font=("Segoe UI", 11)).pack(anchor="w", pady=(3, 22))
        ttk.Label(outer, text="Arquivo local ou link do YouTube").pack(anchor="w")
        line = ttk.Frame(outer)
        line.pack(fill="x", pady=6)
        self.source = tk.StringVar()
        ttk.Entry(line, textvariable=self.source).pack(side="left", fill="x", expand=True)
        ttk.Button(line, text="Selecionar vídeo", command=self.select).pack(side="left", padx=(8, 0))
        line2 = ttk.Frame(outer)
        line2.pack(fill="x", pady=8)
        ttk.Label(line2, text="Modelo ASR").pack(side="left")
        self.model = tk.StringVar(value="large-v3")
        ttk.Combobox(line2, textvariable=self.model, values=["large-v3", "medium", "small", "turbo", "tiny"],
                     width=15, state="readonly").pack(side="left", padx=8)
        ttk.Label(line2, text="Dispositivo").pack(side="left", padx=(16, 0))
        self.device = tk.StringVar(value="cuda" if shutil.which("nvidia-smi") else "auto")
        ttk.Combobox(line2, textvariable=self.device, values=["auto", "cpu", "cuda"],
                     width=10, state="readonly").pack(side="left", padx=8)
        try:
            from ldporto.config import load_config
            sem_cfg = load_config(ROOT/"config"/"config.yaml")["semantic_analysis"]
        except Exception:
            sem_cfg = {"backend": "ollama", "model": "qwen3:8b", "profile": "max"}
        self.ollama = tk.BooleanVar(value=sem_cfg.get("backend") == "ollama")
        ttk.Checkbutton(outer, text="Usar Ollama local para análise semântica + revisão editorial global",
                        variable=self.ollama).pack(anchor="w", pady=4)
        ollama_row = ttk.Frame(outer)
        ollama_row.pack(fill="x", pady=4)
        ttk.Label(ollama_row, text="Modelo Ollama").pack(side="left")
        self.ollama_model = tk.StringVar(value=sem_cfg.get("model") or "qwen3:8b")
        self.ollama_combo = ttk.Combobox(ollama_row, textvariable=self.ollama_model,
                                         values=["qwen3:8b", "qwen3:14b", "qwen3:30b"], width=24)
        self.ollama_combo.pack(side="left", padx=8)
        ttk.Label(ollama_row, text="Perfil").pack(side="left", padx=(12, 0))
        self.ollama_profile = tk.StringVar(value=sem_cfg.get("profile") or "max")
        ttk.Combobox(ollama_row, textvariable=self.ollama_profile,
                     values=["max", "balanced", "fast"], width=12, state="readonly").pack(side="left", padx=8)
        ttk.Button(ollama_row, text="Atualizar modelos", command=self.refresh_ollama).pack(side="left", padx=4)
        ttk.Button(ollama_row, text="Configurar Ollama", command=self.configure_ollama).pack(side="left", padx=4)
        self.ollama_status = tk.StringVar(value="Ollama: verificando…")
        ttk.Label(outer, textvariable=self.ollama_status, font=("Segoe UI", 9)).pack(anchor="w", pady=(0, 6))
        try:
            camera_cfg = load_config(ROOT/"config"/"config.yaml")["camera_director"]
        except Exception:
            camera_cfg = {"enabled": True, "profile": "natural"}
        camera_row = ttk.Frame(outer)
        camera_row.pack(fill="x", pady=4)
        self.camera_enabled = tk.BooleanVar(value=camera_cfg.get("enabled", True))
        ttk.Checkbutton(camera_row, text="Camera Director", variable=self.camera_enabled).pack(side="left")
        self.camera_profile = tk.StringVar(value=camera_cfg.get("profile", "natural"))
        ttk.Combobox(camera_row, textvariable=self.camera_profile, state="readonly", width=18,
                     values=["natural", "podcast", "dynamic_short", "documentary", "conservative"]).pack(side="left", padx=8)
        self.camera_advanced = ttk.Frame(outer)
        self.camera_hold = tk.StringVar()
        self.camera_zoom = tk.StringVar()
        ttk.Label(self.camera_advanced, text="Hold mínimo (s; vazio = perfil)").pack(side="left")
        ttk.Entry(self.camera_advanced, textvariable=self.camera_hold, width=7).pack(side="left", padx=6)
        ttk.Label(self.camera_advanced, text="Zoom máximo (vazio = perfil)").pack(side="left")
        ttk.Entry(self.camera_advanced, textvariable=self.camera_zoom, width=7).pack(side="left", padx=6)
        ttk.Button(camera_row, text="Configuração avançada", command=self.toggle_camera_settings).pack(side="left")
        ttk.Button(camera_row, text="Reprocessar só câmera", command=self.resume_camera).pack(side="left", padx=8)
        self.camera_summary = tk.StringVar(value="Camera Director: aguardando análise")
        ttk.Label(outer, textvariable=self.camera_summary, font=("Segoe UI", 9), wraplength=980).pack(anchor="w")
        self.force = tk.BooleanVar(value=False)
        ttk.Checkbutton(outer, text="Reprocessar (ignorar cache)", variable=self.force).pack(anchor="w", pady=4)
        # Generated by GitHub Copilot - Oct-05-2026
        capability_cfg = load_config(ROOT/"config"/"config.yaml")
        capability_row = ttk.Frame(outer)
        capability_row.pack(fill="x", pady=4)
        self.diarization = tk.BooleanVar(value=capability_cfg["diarization"]["enabled"])
        self.vision = tk.BooleanVar(value=capability_cfg["vision"]["enabled"])
        ttk.Checkbutton(capability_row, text="Diarizacao", variable=self.diarization).pack(side="left")
        ttk.Checkbutton(capability_row, text="Visao / active speaker", variable=self.vision).pack(side="left", padx=12)
        self.preflight_status = tk.StringVar(value="Preflight: nao executado")
        ttk.Label(outer, textvariable=self.preflight_status, wraplength=980).pack(anchor="w")
        token_row = ttk.Frame(outer)
        token_row.pack(fill="x", pady=6)
        ttk.Label(token_row, text="HF_TOKEN (Community-1 online exige token + aceite; somente nesta sessao)").pack(side="left")
        self.hf_token = tk.StringVar(value=os.environ.get("HF_TOKEN", ""))
        ttk.Entry(token_row, textvariable=self.hf_token, show="*", width=42).pack(side="left", padx=8)
        ttk.Label(outer, text="Large-v3 prioriza fidelidade. Em NVIDIA, use CUDA; falha de GPU nao cai silenciosamente para CPU."
                  "\nDiarização exige extras + HF_TOKEN. Veja LEIA_PRIMEIRO.md.",
                  font=("Segoe UI", 10)).pack(anchor="w", pady=10)
        buttons = ttk.Frame(outer)
        buttons.pack(fill="x", pady=10)
        self.start_button = ttk.Button(buttons, text="ANALISAR", command=self.start)
        self.start_button.pack(side="left")
        ttk.Button(buttons, text="Diagnóstico", command=self.diagnose).pack(side="left", padx=8)
        if os.name == "nt":
            ttk.Button(buttons, text="Reparar GPU", command=self.repair_gpu).pack(side="left", padx=4)
        ttk.Button(buttons, text="Abrir resultados", command=self.open_results).pack(side="left")
        ttk.Button(buttons, text="Interromper", command=self.stop).pack(side="right")
        self.status = tk.StringVar(value="Prontidao ainda nao verificada. Diagnostico verifica recursos habilitados.")
        ttk.Label(outer, textvariable=self.status).pack(anchor="w", pady=(8, 3))
        self.warning_count=0
        self.run_state=tk.StringVar(value='Etapa: aguardando | Avisos: 0 | Qualidade: nao medida | Cache: nao verificado')
        ttk.Label(outer,textvariable=self.run_state,wraplength=980).pack(anchor='w')
        self.log = tk.Text(outer, bg="#222229", fg="#eeeeee", insertbackground="white",
                           wrap="word", font=("Consolas", 10))
        self.log.pack(fill="both", expand=True)
        window.after(150, self.poll)
        window.after(500, self.refresh_ollama)
        window.protocol("WM_DELETE_WINDOW", self.close)

    def select(self):
        path = filedialog.askopenfilename(filetypes=[("Vídeos", "*.mp4 *.mkv *.webm *.mov *.avi"), ("Todos", "*.*")])
        if path:
            self.source.set(path)

    def launch(self, args):
        if self.proc and self.proc.poll() is None:
            messagebox.showinfo("Em execução", "Aguarde o processamento atual.")
            return
        env = dict(os.environ, PYTHONIOENCODING="utf-8", PYTHONUNBUFFERED="1")
        if self.hf_token.get().strip():
            env["HF_TOKEN"] = self.hf_token.get().strip()
        self.proc = subprocess.Popen([sys.executable, "-u", str(ROOT/"analyze.py")]+args,
                    cwd=ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                    text=True, encoding="utf-8", errors="replace", env=env,
                    creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0,
                    start_new_session=os.name != "nt")
        self.start_button.configure(state="disabled")
        self.warning_count=0
        self.status.set("Processando… acompanhe as etapas abaixo.")
        proc = self.proc
        def read():
            for line in proc.stdout:
                self.messages.put(("line", line))
            self.messages.put(("done", proc.wait()))
        threading.Thread(target=read, daemon=True).start()

    def start(self):
        source = self.source.get().strip()
        if not source:
            messagebox.showinfo("Entrada", "Selecione um vídeo ou cole um link.")
            return
        self.output_folder = ROOT/"analysis"/__import__("datetime").datetime.now().strftime("execucao_%Y%m%d_%H%M%S")
        args = [source, "--output", str(self.output_folder), "--model", self.model.get(),
                "--device", self.device.get(), "--semantic", "ollama" if self.ollama.get() else "heuristic"]
        if self.ollama.get():
            args += ["--ollama-model", self.ollama_model.get().strip() or "qwen3:8b",
                     "--ollama-profile", self.ollama_profile.get()]
        if self.force.get():
            args.append("--force")
        # Generated by GitHub Copilot - Oct-05-2026
        if not self.diarization.get():
            args.append("--no-diarization")
        if not self.vision.get():
            args.append("--no-vision")
        self.preflight_status.set("Preflight: verificando capacidades habilitadas")
        # Stable output per source allows automatic resume from previous GUI executions.
        import hashlib
        tag = hashlib.sha256(source.encode()).hexdigest()[:12]
        self.output_folder = ROOT/"analysis"/f"video_{tag}"
        args[2] = str(self.output_folder)
        try:
            args += self.camera_args()
        except ValueError:
            messagebox.showerror("Câmera", "Hold e zoom devem ser números válidos.")
            return
        self.launch(args)

    def camera_args(self):
        args = ["--camera-profile", self.camera_profile.get()]
        if not self.camera_enabled.get():
            args.append("--no-camera-director")
        for flag, var in (("--camera-min-hold", self.camera_hold), ("--camera-max-zoom", self.camera_zoom)):
            if var.get().strip():
                args += [flag, str(float(var.get().replace(",", ".")))]
        return args

    def toggle_camera_settings(self):
        if self.camera_advanced.winfo_manager():
            self.camera_advanced.pack_forget()
        else:
            self.camera_advanced.pack(fill="x", pady=4, before=self.log)

    def resume_camera(self):
        if self.proc and self.proc.poll() is None:
            return
        folder = filedialog.askdirectory(title="Pasta contendo analysis.json")
        if folder:
            try:
                args = ["--director-only", folder]+self.camera_args()
            except ValueError:
                messagebox.showerror("Câmera", "Hold e zoom devem ser números válidos.")
                return
            self.output_folder = Path(folder)
            self.launch(args)

    def update_camera_summary(self):
        if not self.output_folder:
            return
        import json
        try:
            q = json.loads((self.output_folder/"analysis_quality.json").read_text(encoding="utf-8"))
            manifest = json.loads((self.output_folder/"manifest.json").read_text(encoding="utf-8"))
            status = manifest.get("stage_status", {}).get("19_camera_director", {}).get("status", "unavailable")
            def pct(key):
                v = q.get(key)
                return f"{v*100:.1f}%" if isinstance(v, (int, float)) else "n/d"
            def num(key):
                v = q.get(key)
                return f"{v:.2f}" if isinstance(v, (int, float)) else "n/d"
            self.camera_summary.set(f"Camera Director: {status} | Active speaker: {pct('active_speaker_coverage')} | "
                f"Cobertura temporal: {pct('timeline_temporal_coverage')} | Foco resolvido: {pct('resolved_focus_coverage')} | Plano médio: {num('average_director_shot_seconds')}s | "
                f"Trocas/min: {num('director_switches_per_minute')} | Split: {pct('split_fraction')} | "
                f"Foco incerto: {pct('unresolved_focus_fraction')} | Pan/zoom com limites físicos; revisar keyframes.")
            self.run_state.set('Etapa: finalizada | Avisos: '+str(self.warning_count)+' | Qualidade: '+str(q.get('quality_status','nao medida')))
        except (OSError, ValueError):
            self.camera_summary.set("Camera Director: resultado ainda indisponível")

    def refresh_ollama(self):
        self.ollama_status.set("Ollama: verificando serviço local…")
        def work():
            try:
                from ldporto.ollama_local import service_info
                info = service_info("http://127.0.0.1:11434", timeout=2)
                names = [m.get("name") for m in info.get("models", []) if m.get("name")]
                def apply():
                    if info.get("reachable"):
                        self.ollama_status.set(f"Ollama {info.get('version') or ''}: {len(names)} modelo(s) instalado(s)" +
                                               (" · " + ", ".join(names[:4]) if names else " · nenhum modelo"))
                        if names:
                            self.ollama_combo.configure(values=names)
                            if self.ollama_model.get() not in names:
                                self.ollama_status.set(self.ollama_status.get()+' | modelo configurado ausente; escolha nao foi alterada')
                    else:
                        self.ollama_status.set("Ollama não respondeu em 127.0.0.1:11434. Use Configurar Ollama.")
                self.window.after(0, apply)
            except Exception as exc:
                from ldporto.core import scrub
                message=scrub(exc)
                self.window.after(0, lambda text=message: self.ollama_status.set('Ollama: '+text))
        threading.Thread(target=work, daemon=True).start()

    def configure_ollama(self):
        bat = ROOT/"CONFIGURAR_OLLAMA_MAXIMO_WINDOWS.bat"
        if os.name == "nt" and bat.is_file():
            os.startfile(str(bat))
        else:
            messagebox.showinfo("Ollama", "Veja LEIA_PRIMEIRO.md para instalar o Ollama e baixar um modelo.")


    def repair_gpu(self):
        bat = ROOT/"CORRIGIR_GPU_WINDOWS.bat"
        if os.name == "nt" and bat.is_file():
            os.startfile(str(bat))
        else:
            messagebox.showinfo("GPU", "Use o instalador CUDA/cuDNN correspondente ao seu sistema.")

    # Generated by GitHub Copilot - Oct-05-2026
    def diagnose(self):
        """Diagnose the selected GUI capabilities instead of unrelated defaults."""
        args = ["--doctor", "--device", self.device.get(),
                "--semantic", "ollama" if self.ollama.get() else "heuristic",
                "--ollama-model", self.ollama_model.get().strip(),
                "--ollama-profile", self.ollama_profile.get()]
        if not self.diarization.get():
            args.append("--no-diarization")
        if not self.vision.get():
            args.append("--no-vision")
        self.preflight_status.set("Preflight: verificando capacidades habilitadas")
        self.launch(args)

    def poll(self):
        try:
            while True:
                kind, value = self.messages.get_nowait()
                if kind == "line":
                    if 'WARNING' in value or 'fallback' in value.casefold():
                        self.warning_count+=1
                    if 'iniciando' in value or 'retomado do cache' in value:
                        self.run_state.set(value.strip()+' | Avisos: '+str(self.warning_count))
                    # Generated by GitHub Copilot - Oct-05-2026
                    if "00_preflight: READY" in value:
                        self.preflight_status.set(value.strip())
                    if "Preflight reprovado" in value or '"status": "ERROR"' in value:
                        self.preflight_status.set("Preflight: ERROR. Consulte o diagnostico abaixo.")
                    if "19_camera_director:" in value:
                        self.camera_summary.set(value.strip())
                    self.log.insert("end", value)
                    self.log.see("end")
                else:
                    self.start_button.configure(state="normal")
                    if value == 0:
                        self.update_camera_summary()
                    self.status.set("Finalizado. Consulte os avisos no relatório." if value == 0
                                    else "Processamento terminou com erro/interrupção. Veja o log.")
        except queue.Empty:
            pass
        self.window.after(150, self.poll)

    def stop(self):
        if self.proc and self.proc.poll() is None:
            if os.name == "nt":
                subprocess.run(["taskkill", "/PID", str(self.proc.pid), "/T", "/F"],
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            else:
                import signal
                os.killpg(self.proc.pid, signal.SIGTERM)
            # Process tree has stopped. Completed checkpoints remain; stale run lock is removable.
            self.proc.wait()
            if self.output_folder:
                (self.output_folder/"RUNNING.lock").unlink(missing_ok=True)
            self.status.set("Interrompido; etapas concluídas podem ser retomadas.")

    def open_results(self):
        folder = self.output_folder or ROOT/"analysis"
        report = folder/"report.html"
        if report.is_file():
            webbrowser.open(report.as_uri())
        elif folder.exists():
            if os.name == "nt":
                os.startfile(str(folder))
            else:
                webbrowser.open(folder.as_uri())

    def close(self):
        if self.proc and self.proc.poll() is None:
            if not messagebox.askyesno("Fechar", "Há processamento em curso. Interromper e fechar?"):
                return
            self.stop()
        self.window.destroy()


if __name__ == "__main__":
    App(tk.Tk())
    tk.mainloop()
