import argparse
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import venv

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))
from ldporto.paths import optional_requirement


def run(args):
    subprocess.run([str(a) for a in args], check=True, shell=False)


# Generated by GitHub Copilot - Oct-05-2026
def main():
    """Prepare recommended enabled capabilities in a compatible project .venv."""
    p = argparse.ArgumentParser(description="Instala o Analyzer em ambiente isolado.")
    p.add_argument("--extras", default="diarization,vision", help="Padrao: diarization,vision; OCR/YOLO/audio-events sao opt-in")
    p.add_argument("--windows-tools", action="store_true", help="Instalar FFmpeg e Deno via winget quando faltarem")
    p.add_argument("--download-vision-models", action="store_true")
    p.add_argument("--no-model-download", action="store_true", help="Modo offline: preflight exige modelos locais completos")
    p.add_argument("--ollama", action="store_true", help="Instalar Ollama no Windows quando ausente")
    args = p.parse_args()
    print("Selected executable:", sys.executable, flush=True)
    print("Selected version:", sys.version.split()[0], flush=True)
    if sys.version_info[:2] != (3, 11) or platform.architecture()[0] != "64bit":
        raise SystemExit("Use Python 3.11.x de 64 bits. Veja README.md.")
    extras = [s.strip() for s in args.extras.split(",") if s.strip()]
    allowed = {"diarization", "vision", "ocr", "yolo", "audio-events"}
    if not set(extras) <= allowed:
        raise SystemExit("Extras inválidos: "+", ".join(set(extras)-allowed))
    env = ROOT/".venv"
    python = env/("Scripts/python.exe" if os.name == "nt" else "bin/python")
    print("Project venv:", env, flush=True)
    if not python.is_file():
        print("Criando ambiente Python isolado…", flush=True)
        venv.EnvBuilder(with_pip=True).create(env)
    existing = subprocess.run([str(python), "-c", "import sys; print('%s.%s' % sys.version_info[:2])"],
                              check=True, capture_output=True, text=True, shell=False)
    if existing.stdout.strip() != f"{sys.version_info[0]}.{sys.version_info[1]}":
        raise SystemExit("A .venv existente usa outro Python. Preserve-a separadamente e crie a .venv com Python 3.11.x; nao sera sobrescrita.")
    run([python, "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel"])
    args_pip = [python, "-m", "pip", "install", "-r", ROOT/"requirements.txt"]
    for name in extras:
        args_pip += ["-r", optional_requirement(name, ROOT)]
    run(args_pip)
    if args.windows_tools and os.name == "nt":
        if not shutil.which("winget"):
            print("winget ausente; instale FFmpeg manualmente conforme README.md.")
        else:
            if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
                run(["winget", "install", "--id", "Gyan.FFmpeg", "--exact",
                     "--accept-source-agreements", "--accept-package-agreements"])
            if not shutil.which("deno") and not shutil.which("node"):
                run(["winget", "install", "--id", "DenoLand.Deno", "--exact",
                     "--accept-source-agreements", "--accept-package-agreements"])
            if args.ollama and not shutil.which("ollama"):
                run(["winget", "install", "--id", "Ollama.Ollama", "--exact",
                     "--accept-source-agreements", "--accept-package-agreements"])
    if not args.no_model_download and (args.download_vision_models or "vision" in extras):
        run([python, ROOT/"scripts"/"download_models.py"])
    print("\nDependencias preparadas. Isso nao comprova prontidao dos modelos/GPU. Reabra o terminal para atualizar o PATH.")
    print("Execute ABRIR_ANALYZER.bat ou: .venv/Scripts/python.exe analyze.py --doctor")
    print("Diarização precisa de HF_TOKEN + aceite do modelo; veja docs/setup/LEIA_PRIMEIRO.md.")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"Instalação interrompida (código {exc.returncode}). Leia a mensagem acima.")
