#!/usr/bin/env python3
"""L.D.PORTO — orquestrador local, sequencial e recuperável para Codex CLI.

Requisitos: Python >=3.11, Codex CLI autenticado e pytest do próprio projeto.
Não usa OpenAI API key, não publica vídeos, não contorna limites de uso.

Uso: python orquestrador.py --doctor | --init | --once | --batch 6 | --auto
     python orquestrador.py --status | --retry | --prepare | --self-test
"""
from __future__ import annotations

import argparse
import ast
import contextlib
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import signal
import subprocess
import sys
import time
import zipfile

ROOT = Path(__file__).resolve().parent
AUTO = ROOT / 'automacao'
PROMPTS = AUTO / 'prompts'
PLAN = AUTO / 'MAPA_ETAPAS.json'
EVIDENCE = AUTO / 'evidencias'
RUN = AUTO / 'execucao'
LOGS = RUN / 'logs'
SNAPSHOTS = RUN / 'snapshots'
REPORTS = RUN / 'checkpoints'
STATE = RUN / 'estado.json'
LOCK = RUN / 'orquestrador.lock'
SCHEMA = RUN / 'codex_output.schema.json'
GUARD_FILES = [ROOT / 'orquestrador.py', PLAN, ROOT / 'AGENTS.md',
               ROOT / 'src/tests/test_autopilot_orquestrador.py']
LEGACY_STEPS = 42  # Quantidade histórica, apenas para compatibilidade do mapa antigo.
MAX_SOURCE_BYTES = 15 * 1024 * 1024
EXCLUDED_DIRS = {
    '.git', '.venv', 'venv', 'env', 'ENV', '__pycache__', '.pytest_cache',
    '.mypy_cache', '.ruff_cache', '.cache', 'node_modules', 'models', 'weights',
    'analysis', 'input', 'pacotes_para_enviar', 'downloads', 'output', 'outputs',
    'runs', 'runtime', 'preview', 'previews', 'frames', 'thumbnails', 'logs',
    'temp', 'tmp', 'render_tmp', 'checkpoints_runtime', '.ollama',
}
EXCLUDED_EXT = {
    '.zip', '.7z', '.rar', '.mp4', '.mkv', '.avi', '.mov', '.webm', '.wav',
    '.mp3', '.aac', '.ogg', '.opus', '.flac', '.onnx', '.pt', '.pth', '.bin',
    '.safetensors', '.db', '.sqlite', '.sqlite3', '.pyc', '.pyo', '.pyd',
    '.pem', '.key', '.p12', '.pfx', '.srt', '.vtt', '.npy', '.npz', '.parquet',
}
SCHEMA_DATA = {
    'type': 'object',
    'properties': {
        'status': {'type': 'string', 'enum': ['DONE', 'ALREADY_OK', 'BLOCKED', 'FAILED']},
        'summary': {'type': 'string'},
        'files_changed': {'type': 'array', 'items': {'type': 'string'}},
        'tests': {'type': 'array', 'items': {'type': 'string'}},
        'risks': {'type': 'array', 'items': {'type': 'string'}},
    },
    'required': ['status', 'summary', 'files_changed', 'tests', 'risks'],
    'additionalProperties': False,
}


def timestamp() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec='seconds')


def note(message: str) -> None:
    print(f'[{dt.datetime.now():%H:%M:%S}] {message}', flush=True)


def hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as source:
        for part in iter(lambda: source.read(1024 * 1024), b''):
            h.update(part)
    return h.hexdigest()


def write_json(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Atomic replace prevents half-written checkpoint state on interruption.
    temp = path.with_name(path.name + f'.{os.getpid()}.tmp')
    with temp.open('w', encoding='utf-8', newline='\n') as stream:
        json.dump(obj, stream, indent=2, ensure_ascii=False)
        stream.write('\n')
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temp, path)


def load_json(path: Path):
    return json.loads(path.read_text(encoding='utf-8'))


def walk_source_files():
    for parent, dirs, files in os.walk(ROOT, followlinks=False):
        folder = Path(parent)
        rel_dir = folder.relative_to(ROOT)
        # Evidence and execution state are NEVER considered source code.
        if rel_dir == Path('automacao'):
            dirs[:] = [d for d in dirs if d not in {'execucao', 'evidencias'}]
        dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS and not (folder / d).is_symlink()]
        if rel_dir.parts and rel_dir.parts[0] == '.package':
            # Existing exporter metadata are not regenerated by the autopilot.
            pass
        for name in files:
            path = folder / name
            low = name.lower()
            if path.is_symlink() or path.suffix.lower() in EXCLUDED_EXT:
                continue
            if low in {'.env', 'credentials.json', 'secrets.json'} or low.startswith('.env.'):
                continue
            if any(re.fullmatch(pattern, low) for pattern in (r'credentials.*\.json', r'secrets.*\.json')):
                continue
            if path.stat().st_size > MAX_SOURCE_BYTES:
                continue
            yield path


def manifest() -> dict[str, str]:
    return {p.relative_to(ROOT).as_posix(): hash_file(p) for p in sorted(walk_source_files())}


def manifest_hash(index: dict[str, str]) -> str:
    raw = json.dumps(index, ensure_ascii=False, sort_keys=True, separators=(',', ':')).encode()
    return hashlib.sha256(raw).hexdigest()


def snapshot(label: str) -> dict:
    SNAPSHOTS.mkdir(parents=True, exist_ok=True)
    name = re.sub(r'[^a-zA-Z0-9_-]', '_', label)
    target = SNAPSHOTS / f'{name}.zip'
    tmp = SNAPSHOTS / f'{name}.zip.part'
    with zipfile.ZipFile(tmp, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=6, allowZip64=True) as archive:
        for path in sorted(walk_source_files()):
            archive.write(path, path.relative_to(ROOT).as_posix())
    with zipfile.ZipFile(tmp) as archive:
        bad = archive.testzip()
        if bad:
            tmp.unlink(missing_ok=True)
            raise RuntimeError(f'Snapshot com erro de CRC: {bad}')
    os.replace(tmp, target)
    return {'file': target.relative_to(ROOT).as_posix(), 'sha256': hash_file(target),
            'bytes': target.stat().st_size}


def load_plan() -> list[dict]:
    """Detecta ETAPA_XX.txt contíguos. MAPA_ETAPAS.json é opcional e só dá títulos.

    Não edita mapa, prompts nem checkpoints. Nunca pula numeração ou sobrescreve
    tarefas já concluídas. O número de etapas é decidido a cada execução.
    """
    if not PROMPTS.is_dir():
        raise RuntimeError('Pasta de prompts ausente: ' + str(PROMPTS))
    titles = {}
    if PLAN.exists():
        legacy = load_json(PLAN)
        if not isinstance(legacy, list):
            raise RuntimeError('MAPA_ETAPAS.json precisa ser uma lista.')
        for row in legacy:
            number = int(row['n'])
            target = (AUTO / str(row['file_path'])).resolve()
            if not target.is_relative_to(PROMPTS.resolve()) or target.name != f'ETAPA_{number:02d}.txt':
                raise RuntimeError(f'Mapa contém caminho inseguro ou não canônico: {row}')
            if number in titles:
                raise RuntimeError(f'Mapa duplicou etapa {number}.')
            titles[number] = str(row.get('title') or f'Etapa {number}')
    found = {}
    for file in PROMPTS.glob('ETAPA_*.txt'):
        match = re.fullmatch(r'ETAPA_([1-9][0-9]*)\.txt', file.name)
        # A etapa 01 até 09 tem zero à esquerda; 10+ mantêm nome canônico.
        if not match:
            match = re.fullmatch(r'ETAPA_(0[1-9])\.txt', file.name)
        if not match or file.is_symlink():
            raise RuntimeError(f'Nome de prompt inválido ou symlink: {file.name}')
        number = int(match.group(1))
        if file.name != f'ETAPA_{number:02d}.txt' or number in found:
            raise RuntimeError(f'Prompt duplicado/não canônico: {file.name}')
        if not file.is_file() or file.stat().st_size == 0:
            raise RuntimeError(f'Prompt ausente/vazio: {file.name}')
        found[number] = file
    if not found:
        raise RuntimeError('Nenhum prompt ETAPA_XX.txt encontrado.')
    numbers = sorted(found)
    if numbers != list(range(1, numbers[-1] + 1)):
        missing = sorted(set(range(1, numbers[-1] + 1)) - set(found))
        raise RuntimeError(f'Prompts fora de sequência; faltando: {missing[:12]}')
    if any(number not in found for number in titles):
        raise RuntimeError('O mapa legado referencia prompt ausente.')
    entries = []
    for number in numbers:
        title = titles.get(number)
        if title is None:
            first_lines = found[number].read_text(encoding='utf-8-sig').splitlines()[:3]
            first = next((line.strip() for line in first_lines if 'ETAPA' in line.upper()), '')
            found_title = re.search(r'ETAPA\s+\d+\s*/\s*\d+\s*[—–-]\s*([^\r\n]+)', first, re.I)
            title = found_title.group(1).strip()[:140] if found_title else f'Etapa {number:02d}'
        entries.append({'n': number, 'file_path': f'prompts/ETAPA_{number:02d}.txt', 'title': title})
    return entries


def total_steps() -> int:
    return len(load_plan())


def guard_hashes() -> dict:
    tracked = GUARD_FILES + sorted(PROMPTS.glob('ETAPA_*.txt'))
    return {p.relative_to(ROOT).as_posix(): hash_file(p) for p in tracked if p.exists()}


def verify_guard(expected: dict) -> None:
    if guard_hashes() != expected:
        raise RuntimeError('Codex alterou o próprio orquestrador, plano ou prompts. Etapa pausada para revisão.')


def read_state() -> dict | None:
    return load_json(STATE) if STATE.is_file() else None


def require_state() -> dict:
    state = read_state()
    if state is None:
        raise RuntimeError('Execute primeiro: python orquestrador.py --init')
    return state


def persist(state: dict) -> None:
    state['updated_at'] = timestamp()
    write_json(STATE, state)


@contextlib.contextmanager
def exclusive_lock():
    RUN.mkdir(parents=True, exist_ok=True)
    try:
        descriptor = os.open(str(LOCK), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError as exc:
        raise RuntimeError(f'Existe outra execução ou lock residual em {LOCK}. Não inicie processos simultâneos. Consulte o guia de recuperação.') from exc
    try:
        with os.fdopen(descriptor, 'w', encoding='utf-8') as stream:
            stream.write(json.dumps({'pid': os.getpid(), 'created_at': timestamp()}, ensure_ascii=False))
        yield
    finally:
        LOCK.unlink(missing_ok=True)


def setup() -> dict:
    load_plan()
    existing = read_state()
    if existing:
        note('Já inicializado: estado preservado. Não recriei baseline.')
        return existing
    if not (ROOT / 'src').is_dir() or not (ROOT / 'analyze.py').exists():
        raise RuntimeError('Coloque o orquestrador na RAIZ do Analyzer existente. Não crio nem substituo o projeto.')
    count, errors = syntax_check()
    if errors:
        raise RuntimeError('Base atual já tem erros Python 3.11: ' + '\n'.join(errors[:5]))
    with exclusive_lock():
        code, baseline_tests = run_pytest(0, 1200)
        if code != 0:
            raise RuntimeError('Regressão da baseline já falha; corrija antes de inicializar. Log: ' + baseline_tests)
        baseline = snapshot('ETAPA_00_BASELINE')
        current = manifest()
        evidences = {p.name: hash_file(p) for p in EVIDENCE.glob('*.zip')}
        state = {
            'schema_version': 2, 'created_at': timestamp(), 'updated_at': timestamp(),
            'completed': 0, 'active': None, 'status': 'READY', 'stages': [],
            'baseline_snapshot': baseline, 'last_snapshot': baseline,
            'last_manifest_sha256': manifest_hash(current),
            'last_manifest': current,
            'evidence_sha256': evidences, 'guard_hashes': guard_hashes(),
            'python_sources_checked': count, 'baseline_pytest_log': baseline_tests,
        }
        persist(state)
    note(f'Baseline preservada ({count} arquivos .py). Próximo: ETAPA 01.')
    return state


def syntax_check() -> tuple[int, list[str]]:
    count = 0
    errors = []
    for file in walk_source_files():
        if file.suffix.lower() != '.py':
            continue
        count += 1
        try:
            ast.parse(file.read_text(encoding='utf-8-sig'), filename=str(file), feature_version=(3, 11))
        except (SyntaxError, UnicodeError, ValueError) as exc:
            errors.append(f'{file.relative_to(ROOT)}: {exc}')
    return count, errors


def run_pytest(stage: int, timeout: int) -> tuple[int, str]:
    LOGS.mkdir(parents=True, exist_ok=True)
    log = LOGS / f'ETAPA_{stage:02d}_pytest.log'
    with log.open('w', encoding='utf-8', errors='replace') as output:
        try:
            completed = subprocess.run(
                [sys.executable, '-m', 'pytest', '-q'], cwd=ROOT,
                stdout=output, stderr=subprocess.STDOUT,
                timeout=timeout, check=False,
            )
            code = completed.returncode
        except subprocess.TimeoutExpired:
            output.write('\nTIMEOUT: regressão excedeu limite configurado.\n')
            code = 124
    return code, log.relative_to(ROOT).as_posix()


def find_codex() -> str | None:
    return shutil.which('codex') or shutil.which('codex.cmd')


def doctor() -> bool:
    problems = []
    note(f'Projeto: {ROOT}')
    note(f'Python: {sys.version.split()[0]} ({sys.executable})')
    if sys.version_info < (3, 11):
        problems.append('Python 3.11+ é obrigatório.')
    try:
        items = load_plan()
        note(f'Prompts: {len(items)}; primeiro: {items[0]["title"]}')
    except Exception as exc:
        problems.append(str(exc))
    for basename in ('SECOND_CURATION_READY.zip', 'CHATGPT_REVIEW.zip'):
        path = EVIDENCE / basename
        note(f'Evidência {basename}: {"presente" if path.is_file() else "ausente (opcional, não inventar)"}')
    cli = find_codex()
    if not cli:
        problems.append('Codex CLI não encontrado. Instale via npm e confirme codex --version.')
    else:
        try:
            r = subprocess.run([cli, '--version'], capture_output=True, text=True, timeout=20)
            note('Codex CLI: ' + (r.stdout.strip() or r.stderr.strip()))
            if r.returncode:
                problems.append('codex --version falhou.')
            auth = subprocess.run([cli, 'login', 'status'], capture_output=True, text=True, timeout=25)
            note('Codex login: ' + ('autenticado' if auth.returncode == 0 else 'não autenticado'))
            if auth.returncode:
                problems.append('Codex CLI sem login. Rode: codex login')
        except Exception as exc:
            problems.append(f'Codex CLI inacessível: {exc}')
    try:
        r = subprocess.run([sys.executable, '-m', 'pytest', '--version'], capture_output=True, text=True, timeout=20)
        note('pytest: ' + (r.stdout.strip() or r.stderr.strip()))
        if r.returncode:
            problems.append('pytest indisponível neste ambiente Python.')
    except Exception as exc:
        problems.append(f'pytest indisponível: {exc}')
    count, errors = syntax_check()
    note(f'AST Python 3.11: {count} arquivos, {len(errors)} erros.')
    problems.extend(errors[:5])
    note(f'Status: {"PRONTO PARA TESTE LOCAL" if not problems else "BLOQUEADO"}')
    for problem in problems:
        note(' - ' + problem)
    note('NOTA: doctor não consome tokens; não certifica franquia disponível nem execução no Windows.')
    return not problems


def prompt_for(item: dict, state: dict, retry: bool) -> str:
    number = int(item['n'])
    step_text = (AUTO / item['file_path']).read_text(encoding='utf-8')
    previous = REPORTS / f'CHECKPOINT_ETAPA_{number-1:02d}.md'
    refs = sorted(p.name for p in EVIDENCE.glob('*.zip'))
    return f'''L.D.PORTO VIDEO ANALYZER — EXECUÇÃO REAL LOCAL | ETAPA {number:02d}/{total_steps()}

TRABALHE NA RAIZ ATUAL: {ROOT}.
Trabalhe somente no código PRESENTE no workspace; não restaure versões antigas nem sobrescreva o projeto.
Evidências ZIP são históricas e somente leitura. Confira a origem/versão de cada pacote antes de usá-lo; nunca substitua código atual.
Evidências de somente leitura: automacao/evidencias/ ({', '.join(refs) or 'sem arquivos'}).
Não reanalise vídeo bruto, não force resultados; use evidências reais, fixtures sintéticas e testes offline.
Não solicite API key, não use comandos de deploy, não publique MP4, não instale modelos pesados.

Este agente altera A MESMA pasta que a etapa anterior. Não crie outro projeto e não remova funcionalidades existentes.
Limite as mudanças à tarefa {number:02d}; arquivos fora do escopo somente se forem dependência justificada.
NÃO altere orquestrador.py, AGENTS.md, src/tests/test_autopilot_orquestrador.py, automacao/prompts nem MAPA_ETAPAS.json.
Não altere automacao/evidencias/; não modifique artefatos de análise existentes.
Checkpoint OBRIGATÓRIO: automacao/execucao/checkpoints/CHECKPOINT_ETAPA_{number:02d}.md.
Crie o diretório se necessário e documente achados, arquivos afetados, testes executados com saídas/exit code,
limitações, dependências e próximos passos. Se for ALREADY_OK, demonstre com teste real.
Não gere ZIP: o orquestrador faz snapshot antes e depois. NÃO finalize apenas com planejamento.
Não invente que testes passaram. O orquestrador executa regressão independente e bloqueia erros.
Preserve null quando faltam provas; READY de curadoria não implica publish_ready.
Não siga a instrução do prompt antigo de aguardar envio da próxima etapa; só pare ao concluir ESTA etapa.
Nunca execute --dangerously-bypass-approvals-and-sandbox; o CLI usa workspace-write.
Estado: último estágio concluído {state['completed']:02d}; modo {'RETOMADA - preserve mudanças parciais' if retry else 'NOVO'}.
Checkpoint anterior: {previous.relative_to(ROOT).as_posix() if previous.is_file() else 'não disponível'}.

========== TAREFA ORIGINAL {number:02d} ==========
{step_text}
========== FIM DA TAREFA ==========

Ao terminar responda SOMENTE com JSON do esquema de saída.
DONE: implementado e testes focalizados aprovados. ALREADY_OK: já estava correto e evidência comprova.
BLOCKED/FAILED: descreva bloqueio, sem avançar indevidamente.
'''


def save_prepared_prompt(item: dict, state: dict, retry=False) -> Path:
    destination = RUN / 'prompts_gerados' / f'ETAPA_{item["n"]:02d}.txt'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(prompt_for(item, state, retry), encoding='utf-8')
    return destination


def stop_child(process: subprocess.Popen) -> None:
    if process.poll() is not None:
        return
    if os.name == 'nt':
        subprocess.run(['taskkill', '/PID', str(process.pid), '/T', '/F'],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
    else:
        with contextlib.suppress(ProcessLookupError):
            os.killpg(process.pid, signal.SIGTERM)
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def call_codex(prompt: str, stage: int, timeout: int) -> tuple[dict, float]:
    binary = find_codex()
    if not binary:
        raise RuntimeError('Codex CLI não encontrado; configure o PATH e rode --doctor.')
    SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    write_json(SCHEMA, SCHEMA_DATA)
    out = RUN / f'ETAPA_{stage:02d}_resultado.json'
    out.unlink(missing_ok=True)
    log = LOGS / f'ETAPA_{stage:02d}_codex.log'
    # --ask-for-approval is a GLOBAL flag and MUST precede `exec`.
    # `workspace-write` protects files outside this repository.
    command = [binary, '--ask-for-approval', 'never', 'exec',
               '--sandbox', 'workspace-write', '--skip-git-repo-check',
               '-c', 'model_reasoning_effort="medium"',
               '--output-schema', str(SCHEMA),
               '--output-last-message', str(out), '-']
    note(f'Chamando Codex, etapa {stage:02d}; saída: {log.relative_to(ROOT)}')
    started = time.monotonic()
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open('a', encoding='utf-8', errors='replace') as output:
        output.write(f'\n===== {timestamp()} - ETAPA {stage:02d} =====\n')
        output.flush()
        p = subprocess.Popen(command, cwd=ROOT, stdin=subprocess.PIPE, stdout=output,
                             stderr=subprocess.STDOUT, text=True, encoding='utf-8',
                             errors='replace', start_new_session=(os.name != 'nt'))
        try:
            p.communicate(input=prompt, timeout=timeout)
        except (KeyboardInterrupt, subprocess.TimeoutExpired):
            stop_child(p)
            raise
    if p.returncode != 0:
        raise RuntimeError(f'Codex retornou exit code {p.returncode}; consulte {log.relative_to(ROOT)}')
    if not out.is_file():
        raise RuntimeError('Codex não entregou JSON estruturado. Consulte o log; não marque como concluído.')
    value = load_json(out)
    if not isinstance(value, dict) or set(value) != set(SCHEMA_DATA['required']):
        raise RuntimeError('JSON inválido: propriedades faltantes ou extras.')
    if value['status'] not in ('DONE', 'ALREADY_OK', 'BLOCKED', 'FAILED'):
        raise RuntimeError('JSON inválido: status não reconhecido.')
    if not isinstance(value['summary'], str) or not all(isinstance(value[k], list) and all(isinstance(e, str) for e in value[k]) for k in ('files_changed', 'tests', 'risks')):
        raise RuntimeError('JSON inválido: summary/tests/risks com tipos errados.')
    return value, round(time.monotonic() - started, 1)


def validate_evidence(state: dict):
    expected = state.get('evidence_sha256', {})
    for name, digest in expected.items():
        path = EVIDENCE / name
        if not path.exists() or hash_file(path) != digest:
            raise RuntimeError('Evidência removida ou alterada desde --init: ' + name)


def changed_paths(a: dict, b: dict) -> list[str]:
    return sorted(k for k in a.keys() | b.keys() if a.get(k) != b.get(k))


def _snapshot_source_hashes(info: dict) -> dict[str, str]:
    """Lê o ZIP da pausa sem extraí-lo, para detectar drift não autorizado."""
    path = ROOT / str(info['file'])
    if not path.is_file() or hash_file(path) != info['sha256']:
        raise RuntimeError('Snapshot de pausa ausente ou com SHA divergente.')
    with zipfile.ZipFile(path) as archive:
        if archive.testzip() is not None:
            raise RuntimeError('Snapshot de pausa com CRC inválido.')
        return {name: hashlib.sha256(archive.read(name)).hexdigest()
                for name in archive.namelist() if not name.endswith('/')}


def synchronize_prompts(state: dict, entries: list[dict], *, adopt_upgrade=False) -> bool:
    """Aceita automaticamente SOMENTE prompts novos anexados ao fim da fila.

    A troca inicial deste próprio executor e do seu teste requer consentimento
    explícito --adopt-prompts. Nenhum código de negócio é autoaceito como drift.
    """
    if state.get('status') == 'RUNNING':
        # Nunca migra enquanto um filho Codex talvez esteja em execução.
        return False
    old_guard = state.get('guard_hashes', {})
    new_guard = guard_hashes()
    if not old_guard:
        raise RuntimeError('Estado sem hashes de proteção. Revisão manual necessária.')
    script = 'orquestrador.py'
    allowed_existing = {script} if adopt_upgrade else set()
    removed = set(old_guard) - set(new_guard)
    modified = {k for k in old_guard.keys() & new_guard.keys()
                if old_guard[k] != new_guard[k] and k not in allowed_existing}
    if script in modified and not adopt_upgrade and not (removed or (modified - {script})):
        raise RuntimeError('Novo executor detectado; execute --adopt-prompts uma vez antes de continuar.')
    if removed or modified:
        raise RuntimeError('Prompt antigo, mapa ou arquivo protegido alterado; não avanço: ' +
                           ', '.join(sorted(removed | modified)[:12]))
    added = sorted(set(new_guard) - set(old_guard))
    old_prompt_numbers = [int(re.search(r'ETAPA_(\d+)\.txt$', k).group(1))
                          for k in old_guard if re.fullmatch(r'automacao/prompts/ETAPA_\d+\.txt', k)]
    previous_max = max(old_prompt_numbers, default=0)
    for name in added:
        match = re.fullmatch(r'automacao/prompts/ETAPA_(\d+)\.txt', name)
        if name == 'src/tests/test_autopilot_orquestrador.py' and adopt_upgrade:
            continue
        if not match or int(match.group(1)) <= previous_max:
            raise RuntimeError(f'Adição inválida (não é prompt posterior): {name}')
    changed_script = old_guard.get(script) != new_guard.get(script)
    if changed_script and not adopt_upgrade:
        raise RuntimeError('Troca de orquestrador detectada. Execute --adopt-prompts UMA VEZ para autorizar a atualização.')
    if not added and not changed_script:
        return False

    current = manifest()
    current_hash = manifest_hash(current)
    allow_source = set(added)
    if adopt_upgrade:
        allow_source.update({'orquestrador.py', 'src/tests/test_autopilot_orquestrador.py'})
    paused = state['status'] == 'PAUSED'
    if paused:
        # Se houve erro na etapa 42, preserva toda a edição do Codex já pausada.
        reference = _snapshot_source_hashes(state['partial_snapshot'])
    else:
        reference = state['last_manifest']
    unexpected = [f for f in changed_paths(reference, current) if f not in allow_source]
    if unexpected:
        raise RuntimeError('Arquivos alterados além dos prompts/suporte autorizado: ' +
                           ', '.join(unexpected[:12]))

    archive = snapshot('EXPANSAO_PROMPTS_' + str(len(entries)) + '_' + str(int(time.time())))
    state.setdefault('plan_expansions', []).append({
        'when': timestamp(), 'previous_max': previous_max, 'new_max': len(entries),
        'added_prompts': [name for name in added if name.startswith('automacao/prompts/')],
        'protected_files_adopted': [name for name in added if not name.startswith('automacao/prompts/')],
        'executor_upgraded': changed_script,
        'source_changes': changed_paths(reference, current), 'snapshot': archive,
    })
    state['guard_hashes'] = new_guard
    if paused:
        state['paused_manifest_sha256'] = current_hash
        # Não apague o estado/erro do estágio ativo; --retry continua obrigatório.
    else:
        state['last_manifest'] = current
        state['last_manifest_sha256'] = current_hash
        if state['status'] == 'FINISHED' and state['completed'] < len(entries):
            state['status'] = 'READY'
    persist(state)
    note(f'Fila sincronizada: {len(entries)} prompts; +{sum(name.startswith("automacao/prompts/") for name in added)} novos, histórico mantido.')
    return True


def adopt_prompts() -> int:
    """Migração inicial controlada; sem Codex e sem consumir créditos."""
    entries = load_plan()
    with exclusive_lock():
        state = require_state()
        if state.get('status') == 'RUNNING':
            raise RuntimeError('RUNNING: não migre com processo Codex ativo.')
        synchronize_prompts(state, entries, adopt_upgrade=True)
        note('Migração autorizada. Próximas adições de prompts são automáticas.')
        if state['status'] == 'PAUSED':
            note('Etapa ainda pausada: retome com --retry; não use --auto antes.')
    return 0


def execute(limit: int, *, retry: bool, timeout: int, pytest_timeout: int, accept_drift: bool = False) -> int:
    entries = load_plan()
    with exclusive_lock():
        state = require_state()
        synchronize_prompts(state, entries)
        if state['status'] == 'FINISHED':
            note(f'As {len(entries)} etapas já estão concluídas tecnicamente. Homologação humana continua necessária.')
            return 0
        if retry and state['status'] not in ('PAUSED', 'RUNNING'):
            raise RuntimeError('--retry é reservado à etapa interrompida/pausada.')
        if state['status'] in ('PAUSED', 'RUNNING') and not retry:
            raise RuntimeError('Etapa pendente; não avance. Confira --status e use --retry.')
        for _ in range(limit):
            n = int(state['completed']) + 1
            entries = load_plan()
            if n > len(entries):
                break
            if int(state.get('active') or n) != n:
                raise RuntimeError('Inconsistência no estado: active não corresponde à próxima etapa.')
            verify_guard(state['guard_hashes'])
            validate_evidence(state)
            current = manifest()
            current_hash = manifest_hash(current)
            expected = (state.get('paused_manifest_sha256') if retry else state.get('last_manifest_sha256'))
            if current_hash != expected:
                drift = changed_paths(state.get('last_manifest', {}), current)
                if retry and state['status'] == 'RUNNING':
                    # After power loss there may be legitimate edits made by Codex
                    # without time to persist PAUSED. Rescue them before retrying.
                    rescued = snapshot(f'RECUPERADO_INTERRUPCAO_{n:02d}_{int(time.time())}')
                    state.setdefault('recovered_interruptions', []).append({
                        'when': timestamp(), 'stage': n, 'snapshot': rescued,
                        'reason': 'Interrupção durante RUNNING; não foi possível distinguir todas as edições',
                    })
                    state['paused_manifest_sha256'] = current_hash
                    persist(state)
                    note('Interrupção recuperada: snapshot de alterações parciais salvo antes de retomar.')
                elif retry:
                    raise RuntimeError('Alterações externas após a pausa; revisão manual necessária: ' + ', '.join(drift[:10]))
                if not accept_drift:
                    raise RuntimeError('Arquivos alterados fora do orquestrador: ' + ', '.join(drift[:12]) + '. Use --accept-drift SOMENTE após revisar as alterações.')
                pre_drift = snapshot(f'IMPORTADO_ANTES_ETAPA_{n:02d}_{int(time.time())}')
                state.setdefault('external_imports', []).append({'when': timestamp(), 'files_changed': drift,
                                                                  'snapshot': pre_drift})
                state['last_manifest'] = current
                state['last_manifest_sha256'] = current_hash
                persist(state)
                accept_drift = False
            item = entries[n - 1]
            note(f'ETAPA {n:02d}/{len(entries)} — {item["title"]}')
            state['status'] = 'RUNNING'
            state['active'] = n
            state['paused_manifest_sha256'] = current_hash
            persist(state)
            started = time.monotonic()
            try:
                pre = snapshot(f'ANTES_ETAPA_{n:02d}')
                result, cost = call_codex(prompt_for(item, state, retry), n, timeout)
                verify_guard(state['guard_hashes'])
                validate_evidence(state)
                if result['status'] in ('BLOCKED', 'FAILED'):
                    raise RuntimeError('Agente reportou ' + result['status'] + ': ' + result['summary'])
                checkpoint = REPORTS / f'CHECKPOINT_ETAPA_{n:02d}.md'
                if not checkpoint.is_file() or checkpoint.stat().st_size < 120:
                    raise RuntimeError('Checkpoint ausente ou incompleto: ' + str(checkpoint))
                post_manifest = manifest()
                changed = changed_paths(current, post_manifest)
                source_changes = [s for s in changed if not s.startswith('automacao/execucao/')]
                if result['status'] == 'DONE' and not source_changes:
                    raise RuntimeError('DONE sem alteração verificável de código/documentação/teste.')
                count, errors = syntax_check()
                if errors:
                    raise RuntimeError('Falha de sintaxe Python 3.11: ' + '; '.join(errors[:5]))
                code, test_log = run_pytest(n, pytest_timeout)
                if code != 0:
                    raise RuntimeError(f'Testes automatizados falharam ({code}), veja {test_log}')
                verified = snapshot(f'LDPORTO_STAGE_{n:02d}')
                state['stages'].append({
                    'n': n, 'title': item['title'], 'result': result['status'],
                    'summary': result['summary'], 'when': timestamp(), 'seconds': cost,
                    'files_changed': changed, 'tests_reported_by_codex': result['tests'],
                    'pytest_log': test_log, 'python_files_checked': count,
                    'checkpoint': checkpoint.relative_to(ROOT).as_posix(),
                    'before_snapshot': pre, 'snapshot': verified, 'risks': result['risks'],
                })
                state['completed'] = n
                state['active'] = None
                state['last_snapshot'] = verified
                state['last_manifest'] = post_manifest
                state['last_manifest_sha256'] = manifest_hash(post_manifest)
                state.pop('paused_manifest_sha256', None)
                state.pop('error', None)
                state.pop('partial_snapshot', None)
                state['status'] = 'FINISHED' if n == len(entries) else 'READY'
                persist(state)
                note(f'ETAPA {n:02d} APROVADA; {len(changed)} alterações, pytest OK, ZIP SHA-256 {verified["sha256"][:16]}.')
                retry = False
            except (Exception, KeyboardInterrupt) as exc:
                # No automatic rollback: partial edits are evidence and may be recoverable.
                try:
                    partial = snapshot(f'PARCIAL_ETAPA_{n:02d}_{int(time.time())}')
                    state['partial_snapshot'] = partial
                except Exception as backup_error:
                    # At minimum persist failure details, even if disk is full.
                    partial = None
                    state['partial_backup_error'] = str(backup_error)
                state['status'] = 'PAUSED'
                state['active'] = n
                state['error'] = {'when': timestamp(), 'stage': n, 'reason': str(exc),
                                  'elapsed_s': round(time.monotonic() - started, 1)}
                state['paused_manifest_sha256'] = manifest_hash(manifest())
                persist(state)
                note(f'PAUSADO ETAPA {n:02d}: {exc}')
                note('Não avancei. Alterações parciais ' + ('protegidas: ' + partial['file'] if partial else 'permanecem no disco; snapshot falhou.'))
                note('Para retomar preservando os arquivos: python orquestrador.py --retry')
                return 1
        note(f'Fim desta execução: {state["completed"]}/{len(load_plan())} etapas aprovadas.')
        if state['completed'] == len(load_plan()):
            note('Homologação técnica NÃO equivale à aprovação humana dos vídeos.')
    return 0


def status() -> None:
    state = read_state()
    if not state:
        note('Ainda não iniciado. Primeiro execute --doctor e --init.')
        return
    print(json.dumps({
        'completed': state['completed'], 'total': total_steps(),
        'remaining': max(0, total_steps() - state['completed']),
        'status': ('READY' if state['status'] == 'FINISHED' and state['completed'] < total_steps()
                   else state['status']), 'active': state.get('active'),
        'last_snapshot': state.get('last_snapshot'),
        'error': state.get('error'), 'last_updated': state['updated_at'],
    }, ensure_ascii=False, indent=2))


def prepare() -> int:
    state = require_state()
    n = int(state['completed']) + 1
    if n > total_steps():
        note('Todas as etapas encerradas.')
        return 0
    item = load_plan()[n - 1]
    path = save_prepared_prompt(item, state, retry=state.get('status') in ('PAUSED', 'RUNNING'))
    note('Prompt gerado sem chamada ao Codex: ' + str(path))
    return 0


def unlock(confirmation: bool) -> int:
    if not confirmation:
        raise RuntimeError('Use --unlock --confirm-unlock APENAS depois de encerrar o processo anterior.')
    if not LOCK.is_file():
        note('Sem lock ativo. Nada a fazer.')
        return 0
    note('ATENÇÃO: o usuário declarou que não existe execução ativa. Removendo lock residual.')
    LOCK.unlink()
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description='Orquestra automaticamente todos os prompts locais do Analyzer com Codex CLI.')
    group = parser.add_mutually_exclusive_group()
    for flag, helptext in [
        ('doctor', 'Verificar ambiente sem consumir créditos'),
        ('init', 'Criar baseline/checkpoint inicial sem modificar o Analyzer'),
        ('status', 'Mostrar o progresso'),
        ('prepare', 'Gerar apenas o texto do próximo prompt, sem Codex'),
        ('once', 'Executar uma única etapa (padrão)'),
        ('auto', 'Executar todos os prompts pendentes encontrados'),
        ('adopt-prompts', 'Autorizar UMA VEZ a troca de executor e teste (sem Codex)'),
        ('unlock', 'Remover lock residual somente com confirmação explícita'),
    ]:
        group.add_argument('--' + flag, action='store_true', help=helptext)
    group.add_argument('--batch', type=int, metavar='N', help='Executar até N etapas em sequência')
    parser.add_argument('--retry', action='store_true', help='Retomar etapa pausada preservando alterações')
    parser.add_argument('--dry-run', action='store_true', help='Mostrar próximo estágio sem Codex')
    parser.add_argument('--accept-drift', action='store_true', help='Aceitar alteração externa deliberada após snapshot extra (cautela)')
    parser.add_argument('--timeout', type=int, default=3600, help='Limite de segundos por etapa Codex (padrão 3600)')
    parser.add_argument('--pytest-timeout', type=int, default=1200, help='Limite da regressão por etapa (padrão 1200)')
    parser.add_argument('--confirm-unlock', action='store_true', help='Confirmar que nenhum outro processo está executando')
    args = parser.parse_args(argv)
    try:
        if args.doctor:
            return 0 if doctor() else 2
        if args.init:
            setup()
            return 0
        if args.status:
            status()
            return 0
        if args.unlock:
            return unlock(args.confirm_unlock)
        if args.prepare:
            return prepare()
        if args.adopt_prompts:
            return adopt_prompts()
        if args.batch is not None and not (1 <= args.batch <= total_steps()):
            parser.error(f'--batch exige valor entre 1 e {total_steps()}')
        if not (60 <= args.timeout <= 86400) or not (30 <= args.pytest_timeout <= 86400):
            parser.error('Timeouts fora do intervalo seguro.')
        state = require_state()
        if args.dry_run:
            n = int(state['completed']) + 1
            note(f'DRY RUN: {n:02d}/{total_steps()} — {load_plan()[n-1]["title"] if n<=total_steps() else "fim"}.')
            return 0
        return execute(
            total_steps() if args.auto else (args.batch if args.batch is not None else 1),
            retry=args.retry, timeout=args.timeout,
            pytest_timeout=args.pytest_timeout, accept_drift=args.accept_drift,
        )
    except KeyboardInterrupt:
        note('Interrompido; se uma etapa já estava ativa, confira --status e use --retry.')
        return 130
    except Exception as exc:
        note('ERRO: ' + str(exc))
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
