#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
L.D.PORTO VIDEO ANALYZER - Exportador unificado

Python 3.11+ / somente biblioteca padrao.

Sem argumentos, gera DOIS pacotes separados:
  1) LDPORTO_PROJETO_ATUAL_<timestamp>.zip
  2) CHATGPT_REVIEW_<analysis>_<timestamp>.zip

O pacote de PROJETO contem codigo/config/testes/docs/scripts e arquivos de apoio.
O pacote de ANALISE contem somente evidencias para segunda curadoria.

Nao altera o projeto e nao inclui .venv, videos, audios, modelos/pesos,
caches, downloads, previews, proxies, ZIPs antigos ou credenciais detectadas.

Uso mais comum (na raiz do projeto):
    py -3.11 exportar_ldporto.py

Somente projeto:
    py -3.11 exportar_ldporto.py --mode project

Somente analise mais recente:
    py -3.11 exportar_ldporto.py --mode analysis

Analise especifica:
    py -3.11 exportar_ldporto.py --mode analysis --analysis analysis/video_xxxxx

Ajuda:
    py -3.11 exportar_ldporto.py --help
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import zipfile
import tempfile
from collections import Counter
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import Iterable


# -----------------------------------------------------------------------------
# Projeto
# -----------------------------------------------------------------------------

PROJECT_DIRS = {
    "src",
    "tests",
    "config",
    "configs",
    "docs",
    "examples",
    "scripts",
    "requirements",
    "schemas",
    "assets",
    "resources",
    ".github",
}

ROOT_TEXT_EXTENSIONS = {
    ".py", ".pyi", ".toml", ".cfg", ".ini", ".json", ".jsonl",
    ".yaml", ".yml", ".md", ".txt", ".rst", ".bat", ".cmd",
    ".ps1", ".sh", ".xml", ".csv", ".tsv", ".html", ".css",
    ".js", ".ts", ".tsx", ".jsx", ".lock",
}

PROJECT_ALLOWED_EXTENSIONS = ROOT_TEXT_EXTENSIONS | {
    ".svg", ".ico", ".png", ".jpg", ".jpeg", ".webp", ".gif",
}

EXCLUDED_DIR_NAMES = {
    ".venv", "venv", "env", ".git", ".idea", ".vscode", ".vs",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "node_modules", "cache", "caches", ".cache", "tmp", "temp",
    "downloads", "download", "input", "inputs", "output", "outputs",
    "build", "dist", "models", "model", "weights", "checkpoints",
    "audio", "audios", "video", "videos", "preview", "previews",
    "proxy", "proxies", "pacotes_para_enviar",
}

HEAVY_EXTENSIONS = {
    ".mp4", ".mkv", ".webm", ".mov", ".avi", ".m4v", ".mts", ".m2ts",
    ".wav", ".mp3", ".flac", ".aac", ".ogg", ".m4a", ".wma",
    ".pt", ".pth", ".onnx", ".bin", ".safetensors", ".ckpt",
    ".dll", ".so", ".dylib", ".exe", ".pyd", ".whl",
    ".zip", ".7z", ".rar", ".tar", ".gz", ".bz2", ".xz",
    ".pyc", ".pyo",
}

MODEL_DOC_NAMES = {
    "README.md", "README.txt", "LICENSE", "LICENSE.txt", "NOTICE",
    "manifest.json", "models.json", "vision_models_manifest.json",
    "checksums.txt",
}

# Scripts antigos que este arquivo substitui. Mesmo que ainda estejam na raiz,
# nao entram no ZIP novo.
LEGACY_EXPORTER_NAMES = {
    "pack_ldporto_for_work.py",
    "pack_ldporto_for_work(1).py",
    "export_ldporto_project.py",
    "gerar_pacote_ldporto.py",
    "gerar_pacote_ldporto(1).py",
    "pack_analysis_for_chatgpt.py",
}

# Generated by GitHub Copilot - Oct-05-2026
DERIVED_PACKAGE_NAMES = {
    "PROJECT_EXPORT_MANIFEST.json",
    "PROJECT_EXPORT_TREE.txt",
    "PROJECT_EXPORT_README.txt",
    "ANALYSIS_EXPORT_MANIFEST.json",
    "ANALYSIS_EXPORT_TREE.txt",
    "ANALYSIS_EXPORT_README.txt",
    "WORK_PACKAGE_MANIFEST.json",
    "WORK_PACKAGE_PROJECT_TREE.txt",
    "WORK_PACKAGE_README.txt",
    "PACK_EXPORT_MANIFEST.json",
    "PACK_EXPORT_TREE.txt",
    "PACK_EXPORT_README.txt",
    "PACKAGE_MANIFEST.json",
    "README_CHATGPT.txt",
}

DERIVED_PREFIXES = (
    "LDPORTO_PROJETO_ATUAL_",
    "LDPORTO_VIDEO_ANALYZER_WORK_PACKAGE_",
    "CHATGPT_REVIEW_",
)


# -----------------------------------------------------------------------------
# Analise / segunda curadoria
# -----------------------------------------------------------------------------

ANALYSIS_PRIORITY_FILES = [
    # Generated by GitHub Copilot - Oct-05-2026
    "analysis_summary.json", "people_summary.json", "camera_plan.compact.json",
    "camera_timeline.compact.json", "master_timeline.compact.json", "CHATGPT_ANALYSIS_HANDOFF.compact.json",
    "artifact_metrics.json", "transcript_segments.json", "speaker_turns.json", "speech_overlaps.json",
    "question_candidates.json", "question_answer_pairs.json", "qa_summary.json", "program_sections.json",
    # V4 / segunda curadoria
    "second_curation_package.json",
    "second_curation_package.md",
    "CHATGPT_ANALYSIS_HANDOFF.json",
    "CHATGPT_ANALYSIS_HANDOFF.md",

    # entendimento editorial
    "video_understanding.json",
    "main_moments.json",
    "story_arcs.json",
    "editorial_moments.json",
    "llm_insights.json",
    "ollama_editorial_review.json",
    "questions_answers.json",
    "topics.json",
    "participants.json",
    "entities.json",

    # transcricao
    "transcript.txt",
    "transcript.srt",
    "transcript.vtt",
    "words.json",
    "caption_segments.json",

    # qualidade / execucao
    "analysis_quality.json",
    "quality_issues.json",
    "run_manifest.json",
    "evaluation_report.json",
    "evaluation_report.md",
    "analysis.json",

    # planner / camera / preview
    "camera_plan.json",
    "camera_timeline.json",
    "camera_director_timeline.json",
    "camera_director_debug.json",
    "preview_validation.json",
    "edit_plan.json",
    "review_overrides.json",

    # percepcao
    "active_speaker.json",
    "speaker_person_mapping.json",
    "speaker_person_summary.json",
    "speakers.json",
    "people.json",
    "people_observations.json",
    "person_identities.json",
    "person_motion.json",
    "shots.json",
    "scenes.json",
    "master_timeline.json",
    "thumbnail_candidates.json",

    # relatorio/logs
    "report.html",
    "analyzer.log",
    "analysis.log",
    "run.log",
    "debug.log",
]


# Generated by GitHub Copilot - Oct-05-2026
COMPACT_EQUIVALENTS = {
    "analysis.json":"analysis_summary.json", "people_observations.json":"people_summary.json",
    "person_motion.json":"people_summary.json", "camera_plan.json":"camera_plan.compact.json",
    "camera_timeline.json":"camera_timeline.compact.json", "master_timeline.json":"master_timeline.compact.json",
    "CHATGPT_ANALYSIS_HANDOFF.json":"CHATGPT_ANALYSIS_HANDOFF.compact.json",
    "video_analysis.json":"CHATGPT_ANALYSIS_HANDOFF.compact.json",
}
ANALYSIS_ESSENTIAL_FILES = ("second_curation_package.json", "CHATGPT_ANALYSIS_HANDOFF.json", "analysis_quality.json",
                            "camera_plan.json", "camera_director_timeline.json", "preview_validation.json", "transcript.txt",
                            "words.json", "people_observations.json", "person_motion.json", "master_timeline.json", "video_analysis.json", "analysis.json")
WORKER_TEMP_FILES = {"WORKER_PROMPT_V42.md","WORKER_BENCHMARK_EVIDENCE.md","WORKER_RUNBOOK_V42.md","INICIAR_WORKER.txt"}

ANALYSIS_TEXT_EXTENSIONS = {
    ".json", ".jsonl", ".txt", ".md", ".html", ".htm", ".srt", ".vtt",
    ".csv", ".tsv", ".yaml", ".yml", ".xml",
}

ANALYSIS_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

ANALYSIS_EXCLUDED_DIRS = {
    "cache", "caches", ".cache", "__pycache__", ".pytest_cache", ".git",
    "audio", "audios", "video", "videos", "proxy", "proxies",
    "preview", "previews", "temp", "tmp", "models", "weights",
    "checkpoints",
}

IMAGE_REFERENCE_KEYS = (
    "thumbnail", "frame", "portrait", "image", "keyframe", "snapshot",
)


# -----------------------------------------------------------------------------
# Seguranca
# -----------------------------------------------------------------------------

SENSITIVE_FILENAME_RE = re.compile(
    r"(?:^|[._-])(?:\.env|cookie|credential|credentials|client[_-]?secret|"
    r"access[_-]?token|refresh[_-]?token|hf[_-]?token|private[_-]?key|"
    r"secret|secrets)(?:$|[._-])",
    re.I,
)

SENSITIVE_EXACT_NAMES = {
    ".env", ".netrc", ".npmrc", ".pypirc", "credentials.json",
    "secrets.json", "token.json", "tokens.json",
}

SENSITIVE_KEY_EXTENSIONS = {".pem", ".key", ".pfx", ".p12", ".jks"}

# So padroes fortes: evita remover codigo/documentacao apenas por mencionar HF_TOKEN.
STRONG_SECRET_PATTERNS = [
    re.compile(rb"\bhf_[A-Za-z0-9]{20,}\b"),
    re.compile(rb"\bsk-[A-Za-z0-9_-]{24,}\b"),
    re.compile(rb"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----"),
    re.compile(rb"(?i)\bBearer\s+[A-Za-z0-9._~+/=-]{24,}\b"),
]


@dataclass(frozen=True)
class Record:
    path: str
    bytes: int
    sha256: str
    kind: str
    included: bool = True
    original_bytes: int = 0
    source_artifact: str = ""
    compact_equivalent: str | None = None


def human_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if value < 1024:
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TiB"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# Generated by GitHub Copilot - Oct-05-2026
def sha256_file(path: Path) -> str:
    """Checksum omitted large evidence with bounded memory rather than loading it."""
    checksum = hashlib.sha256()
    with path.open('rb') as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b''):
            checksum.update(block)
    return checksum.hexdigest()


def linked(path: Path) -> bool:
    try:
        attrs = getattr(path.lstat(), "st_file_attributes", 0)
    except OSError:
        attrs = 0
    return path.is_symlink() or (
        hasattr(path, "is_junction") and path.is_junction()
    ) or bool(attrs & 0x400)


def sensitive_name(path: Path) -> bool:
    name = path.name.lower()
    if name in SENSITIVE_EXACT_NAMES or name.startswith(".env."):
        return True
    if path.suffix.lower() in SENSITIVE_KEY_EXTENSIONS:
        return True
    return bool(SENSITIVE_FILENAME_RE.search(path.name))


def contains_strong_secret(data: bytes) -> bool:
    # Evita escanear binarios gigantes; os binarios de qualquer forma nao entram.
    return any(pattern.search(data) for pattern in STRONG_SECRET_PATTERNS)


def is_generated_package_name(name: str) -> bool:
    upper = name.upper()
    if name.casefold() in {derived.casefold() for derived in DERIVED_PACKAGE_NAMES} or name in WORKER_TEMP_FILES:
        return True
    if any(upper.startswith(prefix.upper()) for prefix in DERIVED_PREFIXES):
        return True
    return False


def looks_like_project_root(root: Path) -> bool:
    return (root / "src" / "ldporto" / "pipeline.py").is_file()


def find_project_root(value: str | None) -> Path:
    starts = []
    if value:
        starts.append(Path(value).expanduser())
    starts.extend([Path(__file__).resolve().parents[2], Path.cwd()])

    checked: set[Path] = set()
    for start in starts:
        try:
            resolved = start.resolve()
        except OSError:
            continue
        for candidate in [resolved, *resolved.parents]:
            if candidate in checked:
                continue
            checked.add(candidate)
            if looks_like_project_root(candidate):
                return candidate

    raise ValueError(
        "Raiz do projeto nao encontrada. Execute dentro do LDPORTO_VIDEO_ANALYZER "
        "ou use --root \"C:\\caminho\\LDPORTO_VIDEO_ANALYZER\"."
    )


def safe_relative(path: Path, root: Path) -> Path | None:
    try:
        return path.resolve().relative_to(root.resolve())
    except (ValueError, OSError):
        return None


def project_file_allowed(root: Path, path: Path, output_dir: Path) -> bool:
    rel = safe_relative(path, root)
    if rel is None or not path.is_file() or linked(path):
        return False

    if safe_relative(path, output_dir) is not None:
        return False

    parts_lower = [p.lower() for p in rel.parts]
    if not rel.parts:
        return False

    if rel.parts[0].lower() == "analysis":
        return False

    if any(part in EXCLUDED_DIR_NAMES for part in parts_lower[:-1]):
        return False

    if path.name in LEGACY_EXPORTER_NAMES or is_generated_package_name(path.name):
        return False

    if sensitive_name(path):
        return False

    if path.suffix.lower() in HEAVY_EXTENSIONS:
        return False

    # Arquivos da raiz: somente arquivos de projeto reconheciveis.
    if len(rel.parts) == 1:
        return (
            path.suffix.lower() in ROOT_TEXT_EXTENSIONS
            or path.name in {"LICENSE", "NOTICE", ".gitignore"}
        )

    # Subpastas selecionadas.
    if rel.parts[0] in PROJECT_DIRS:
        return (
            path.suffix.lower() in PROJECT_ALLOWED_EXTENSIONS
            or path.name in {"LICENSE", "NOTICE"}
        )

    return False


def collect_project_files(root: Path, output_dir: Path) -> list[Path]:
    selected: list[Path] = []

    # Arquivos normais do projeto.
    for base, dirs, files in os.walk(root, followlinks=False):
        folder = Path(base)
        rel_folder = safe_relative(folder, root)
        if rel_folder is None:
            dirs[:] = []
            continue

        # Poda agressiva para nao caminhar por input/analysis/.venv etc.
        kept_dirs = []
        for d in sorted(dirs):
            child = folder / d
            child_rel = safe_relative(child, root)
            if child_rel is None or linked(child):
                continue
            if child.resolve() == output_dir.resolve():
                continue
            if len(child_rel.parts) == 1:
                if d == "analysis":
                    continue
                if d.lower() in EXCLUDED_DIR_NAMES:
                    continue
                if d not in PROJECT_DIRS and d != "models":
                    continue
            elif any(part.lower() in EXCLUDED_DIR_NAMES for part in child_rel.parts):
                continue
            kept_dirs.append(d)
        dirs[:] = kept_dirs

        for name in sorted(files):
            p = folder / name
            if project_file_allowed(root, p, output_dir):
                selected.append(p)

    # Metadados/documentacao pequenos de models, nunca pesos/binarios.
    models = root / "models"
    if models.is_dir() and not linked(models):
        for p in models.rglob("*"):
            if not p.is_file() or linked(p):
                continue
            if safe_relative(p,root) is None or safe_relative(p,models) is None:
                continue
            if p.name not in MODEL_DOC_NAMES:
                continue
            if sensitive_name(p) or p.suffix.lower() in HEAVY_EXTENSIONS:
                continue
            selected.append(p)

    unique = {p.resolve(): p for p in selected}
    return sorted(unique.values(), key=lambda p: p.relative_to(root).as_posix().lower())


def analysis_activity_time(folder: Path) -> float:
    times: list[float] = []
    priority = set(ANALYSIS_PRIORITY_FILES)
    try:
        for p in folder.iterdir():
            if p.is_file() and (p.name in priority or p.suffix.lower() in ANALYSIS_TEXT_EXTENSIONS):
                try:
                    times.append(p.stat().st_mtime)
                except OSError:
                    pass
    except OSError:
        return 0.0
    try:
        times.append(folder.stat().st_mtime)
    except OSError:
        pass
    return max(times) if times else 0.0


def latest_analysis_dir(root: Path) -> Path | None:
    base = root / "analysis"
    if not base.is_dir() or linked(base):
        return None
    candidates = [p for p in base.iterdir() if p.is_dir() and not linked(p)]
    if not candidates:
        return None
    return max(candidates, key=analysis_activity_time)


def resolve_analysis_dir(root: Path, value: str | None) -> Path | None:
    if not value:
        return latest_analysis_dir(root)

    candidate = Path(value).expanduser()
    if not candidate.is_absolute():
        candidate = root / candidate
    candidate = candidate.resolve()

    analysis_root = (root / "analysis").resolve()
    try:
        candidate.relative_to(analysis_root)
    except ValueError as exc:
        raise ValueError("--analysis deve apontar para uma pasta dentro de analysis/.") from exc

    if not candidate.is_dir() or linked(candidate):
        raise ValueError(f"Pasta de analise nao encontrada: {candidate}")
    return candidate


def analysis_path_excluded(path: Path, analysis: Path) -> bool:
    rel = safe_relative(path, analysis)
    if rel is None:
        return True
    return any(part.lower() in ANALYSIS_EXCLUDED_DIRS for part in rel.parts[:-1])


# Generated by GitHub Copilot - Oct-05-2026
def read_json(path: Path, max_bytes: int = 32 * 1024 ** 2):
    """Bound optional JSON inspection instead of loading monolithic legacy artifacts."""
    try:
        if path.stat().st_size>max_bytes:
            return None
        with path.open(encoding='utf-8-sig') as handle:
            return json.load(handle,parse_constant=lambda value: (_ for _ in ()).throw(ValueError('nonfinite JSON')))
    except Exception:
        return None


def referenced_images(analysis: Path, maximum: int) -> list[Path]:
    if maximum <= 0:
        return []

    source_names=["thumbnail_candidates.json","moment_frames.json","participants.json","people.json",
                  "second_curation_package.json","main_moments.json"]
    results: list[Path] = []
    seen: set[Path] = set()

    def add_candidate(raw: str) -> None:
        if len(results) >= maximum:
            return
        raw = raw.strip().replace("\\", "/")
        if not raw:
            return
        candidate = Path(raw)
        if not candidate.is_absolute():
            candidate = analysis / candidate
        try:
            candidate = candidate.resolve()
            candidate.relative_to(analysis.resolve())
        except (ValueError, OSError):
            return
        if (
            candidate.is_file()
            and not linked(candidate)
            and candidate.suffix.lower() in ANALYSIS_IMAGE_EXTENSIONS
            and candidate not in seen
        ):
            seen.add(candidate)
            results.append(candidate)

    def inspect(value) -> None:
        if len(results) >= maximum:
            return
        if isinstance(value, dict):
            for key, item in value.items():
                if (
                    isinstance(item, str)
                    and any(token in str(key).lower() for token in IMAGE_REFERENCE_KEYS)
                ):
                    add_candidate(item)
                inspect(item)
                if len(results) >= maximum:
                    return
        elif isinstance(value, list):
            for item in value:
                inspect(item)
                if len(results) >= maximum:
                    return

    for name in source_names:
        p = analysis / name
        if not p.is_file():
            continue
        data = read_json(p,max_bytes=8 * 1024 ** 2)
        if data is not None:
            inspect(data)
        if len(results) >= maximum:
            break

    return results


def collect_analysis_files(analysis: Path, include_images: bool, max_images: int) -> list[tuple[Path, str]]:
    selected: list[tuple[Path, str]] = []
    seen: set[Path] = set()

    def add(p: Path, kind: str) -> None:
        if not p.is_file() or linked(p) or analysis_path_excluded(p, analysis):
            return
        rp = p.resolve()
        if rp in seen:
            return
        if p.suffix.lower() in HEAVY_EXTENSIONS:
            return
        seen.add(rp)
        selected.append((p, kind))

    for name in ANALYSIS_PRIORITY_FILES:
        add(analysis / name, "priority")

    # Inclui novos contratos textuais que ainda nao existiam quando o script foi criado.
    for p in sorted(analysis.rglob("*"), key=lambda x: x.as_posix().lower()):
        if not p.is_file() or linked(p) or analysis_path_excluded(p, analysis):
            continue
        if p.suffix.lower() in ANALYSIS_TEXT_EXTENSIONS:
            add(p, "textual_evidence")

    if include_images:
        for p in referenced_images(analysis, max_images):
            add(p, "referenced_image")

    # Generated by GitHub Copilot - Oct-05-2026
    compact_names=set(COMPACT_EQUIVALENTS.values())
    essential_names=set(ANALYSIS_ESSENTIAL_FILES)-set(COMPACT_EQUIVALENTS)
    order={name:index for index,name in enumerate(ANALYSIS_PRIORITY_FILES)}
    return sorted(selected,key=lambda item:(
        0 if item[0].name in compact_names | essential_names else 1 if 'review_evidence' in item[0].relative_to(analysis).parts else 2,
        order.get(item[0].name,len(order)),item[0].relative_to(analysis).as_posix()))


def prepare_file(
    path: Path,
    rel: str,
    kind: str,
    max_file_bytes: int,
    remaining_bytes: int,
    scan_secrets: bool = True,
) -> tuple[bytes | None, dict | None]:
    try:
        size = path.stat().st_size
    except OSError as exc:
        return None, {"path": rel, "reason": "stat_error", "detail": str(exc)}

    if size > max_file_bytes:
        return None, {"path": rel, "reason": "file_too_large", "bytes": size, "original_bytes":size,
                      "sha256":sha256_file(path), "included":False, "source_artifact":path.name,
                      "compact_equivalent":COMPACT_EQUIVALENTS.get(path.name)}
    if size > remaining_bytes:
        return None, {"path": rel, "reason": "total_limit", "bytes": size, "original_bytes":size,
                  "sha256":sha256_file(path), "included":False, "source_artifact":path.name,
                  "compact_equivalent":COMPACT_EQUIVALENTS.get(path.name)}
    if sensitive_name(path):
        return None, {"path": rel, "reason": "sensitive_filename", "bytes": size}

    try:
        data = path.read_bytes()
    except OSError as exc:
        return None, {"path": rel, "reason": "read_error", "detail": str(exc)}

    if scan_secrets:
        if contains_strong_secret(data):
            return None, {"path": rel, "reason": "possible_secret_value", "bytes": size,
                          "original_bytes":size,"included":False,"source_artifact":path.name,
                          "compact_equivalent":None,"sha256":sha256_bytes(data)}

    return data, None


# Generated by GitHub Copilot - Oct-05-2026
def export_readiness(package_type, root, records, skipped, extra):
    """Describe evidence completeness independently of the analysis quality verdict."""
    included={record.path for record in records}
    if package_type == 'LDPORTO_PROJECT_EXPORT':
        missing=[name for name in ('src/ldporto/pipeline.py','exportar_ldporto.py','config/config.yaml','analyze.py','app.py') if name not in included]
        return {'export_state':'PARTIAL_EXPORT' if missing or skipped else 'READY',
                'missing_essential_artifacts':missing,'unresolved_package_references':[]}
    prefix=f'analysis/{root.name}/'
    source_names={record.path[len(prefix):] for record in records if record.path.startswith(prefix)}
    missing=[name for name in ANALYSIS_ESSENTIAL_FILES if name not in source_names and COMPACT_EQUIVALENTS.get(name) not in source_names]
    referenced=[]

    def inspect_refs(value):
        """Find compact chunk and explicitly internal references, not original-only provenance."""
        if isinstance(value,dict):
            if value.get('format') == 'indexed_json_projection':
                referenced.extend(chunk.get('path') for chunk in value.get('chunks',[]) if chunk.get('path'))
            for key,item in value.items():
                if key.endswith('_ref') and isinstance(item,str):
                    referenced.append(item)
                elif key in ('transcript_refs','qa_refs') and isinstance(item,dict):
                    referenced.extend(item.values())
                elif key.endswith('_ref') and isinstance(item,dict) and item.get('path'):
                    referenced.append(item['path'])
                inspect_refs(item)
        elif isinstance(value,list):
            for item in value:
                inspect_refs(item)

    for name in COMPACT_EQUIVALENTS.values():
        if name in source_names:
            inspect_refs(read_json(root/name))
    unresolved=sorted({name for name in referenced if isinstance(name,str) and name not in source_names})
    summary=read_json(root/'analysis_summary.json') or {}
    manifest=read_json(root/'run_manifest.json') or {}
    summary=summary if isinstance(summary,dict) else {}
    manifest=manifest if isinstance(manifest,dict) else {}
    evidence_count=(summary.get('counts') or {}).get('words',0)
    if not evidence_count:
        word_path=root/'words.json'
        if word_path.is_file() and word_path.stat().st_size <= 32 * 1024 ** 2:
            words=read_json(word_path)
            evidence_count=len(words) if isinstance(words,list) else 0
    if not evidence_count:
        segments=read_json(root/'transcript_segments.json')
        evidence_count=len(segments) if isinstance(segments,list) else 0
    critical_compact_skipped=any(Path(record.get('path','')).name in set(COMPACT_EQUIVALENTS.values()) or
                                'review_evidence/' in record.get('path','') for record in skipped)
    if extra.get('source_running_lock'):
        state='IN_PROGRESS'
    elif not evidence_count:
        state='ERROR' if manifest.get('root_cause_status') == 'failed' else 'EMPTY'
    elif missing or unresolved or critical_compact_skipped:
        state='PARTIAL_EXPORT'
    else:
        state='READY'
    return {'export_state':state,'source_analysis_status':manifest.get('analysis_status') or summary.get('analysis_status'),
            'evidence_count':evidence_count,'missing_essential_artifacts':missing,
            'unresolved_package_references':unresolved,'compact_projections_used':sorted(name for name in source_names if name in set(COMPACT_EQUIVALENTS.values()))}


# Generated by GitHub Copilot - Oct-05-2026
def inspect_package(path: Path) -> dict:
    """Independently stream-check integrity, collisions, unsafe paths and strong secrets."""
    problems=[]
    seen=set()
    with zipfile.ZipFile(path) as archive:
        if archive.testzip():
            problems.append('zip_crc_failure')
        project='src/ldporto/pipeline.py' in archive.namelist()
        for entry in archive.infolist():
            name=entry.filename.replace('\\','/')
            normalized=name.casefold()
            if normalized in seen:
                problems.append('duplicate_or_windows_collision:'+name)
            seen.add(normalized)
            rel=Path(name)
            if name.startswith('/') or '..' in rel.parts or ':' in name:
                problems.append('unsafe_path:'+name)
            if project and any(part.casefold() in EXCLUDED_DIR_NAMES | {'.worker_v42','.venv311','.venv313'} for part in rel.parts):
                if not (rel.parts[0]=='models' and rel.name in MODEL_DOC_NAMES):
                    problems.append('forbidden_project_path:'+name)
            if project and (rel.suffix.casefold() in HEAVY_EXTENSIONS or sensitive_name(rel)):
                problems.append('forbidden_project_file:'+name)
            if entry.is_dir():
                continue
            carry=b''
            with archive.open(entry) as handle:
                for chunk in iter(lambda:handle.read(1024 * 1024),b''):
                    data=carry+chunk
                    if contains_strong_secret(data):
                        problems.append('strong_secret:'+name)
                        break
                    carry=data[-1024:]
        count=len(archive.infolist())
    return {'status':'PASS' if not problems else 'FAIL','entry_count':count,'issues':problems,
            'secret_scan':'all_uncompressed_entries_streamed','sha256':sha256_file(path)}


# Generated by GitHub Copilot - Oct-05-2026
def exporter_self_test(root: Path) -> dict:
    """Exercise canonical project packaging and explicit empty-analysis readiness."""
    with tempfile.TemporaryDirectory(prefix='ldporto_export_selftest_') as directory:
        temporary=Path(directory)
        project,manifest=build_project_package(root,temporary/'packages','selftest',32,180)
        inspection=inspect_package(project)
        empty_root=temporary/'fixture'
        empty=empty_root/'analysis'/'empty'
        empty.mkdir(parents=True)
        _,empty_manifest=build_analysis_package(empty_root,empty,temporary/'empty_packages','empty',32,250,False,0)
        passed=inspection['status']=='PASS' and manifest['export_state']=='READY' and empty_manifest['export_state']=='EMPTY'
        return {'status':'PASS' if passed else 'FAIL','project_export_state':manifest['export_state'],
                'empty_analysis_export_state':empty_manifest['export_state'],'inspection':inspection,
                'fixture_kind':'temporary_project_package_and_empty_analysis'}


def write_zip_atomic(
    output: Path,
    files: Iterable[tuple[Path, str, str]],
    package_type: str,
    root_for_manifest: Path,
    max_file_mb: int,
    max_total_mb: int,
    extra_manifest: dict,
    readme_text: str,
    manifest_name: str,
    tree_name: str,
    readme_name: str,
) -> tuple[Path, dict]:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".part")
    temporary.unlink(missing_ok=True)

    max_file_bytes = max_file_mb * 1024**2
    max_total_bytes = max_total_mb * 1024**2
    used = 0
    records: list[Record] = []
    skipped: list[dict] = []
    # Generated by GitHub Copilot - Oct-05-2026
    seen_names={name.casefold() for name in (manifest_name,tree_name,readme_name)}

    try:
        with zipfile.ZipFile(temporary, "x", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
            for path, arcname, kind in files:
                if path.resolve() == output.resolve() or path.resolve() == temporary.resolve():
                    continue
                normalized=arcname.replace('\\','/')
                if normalized.startswith('/') or '..' in Path(normalized).parts or ':' in normalized:
                    raise ValueError('Caminho inseguro no pacote: '+normalized)
                if normalized.casefold() in seen_names:
                    raise ValueError('Entrada duplicada ou colisao Windows no ZIP: '+normalized)
                seen_names.add(normalized.casefold())
                arcname=normalized
                remaining = max_total_bytes - used
                data, problem = prepare_file(
                    path, arcname, kind, max_file_bytes, remaining, scan_secrets=True
                )
                if problem:
                    skipped.append(problem)
                    continue
                assert data is not None
                zf.writestr(arcname, data)
                used += len(data)
                records.append(
                    Record(
                        path=arcname,
                        bytes=len(data),
                        sha256=sha256_bytes(data),
                        kind=kind,
                        original_bytes=len(data),source_artifact=path.name,
                        compact_equivalent=COMPACT_EQUIVALENTS.get(path.name),
                    )
                )

            included_paths = sorted(r.path for r in records)
            tree = "\n".join(included_paths) + ("\n" if included_paths else "")
            manifest = {
                "package_type": package_type,
                "created_at_local": datetime.now().astimezone().isoformat(),
                "packager_python": sys.version.split()[0],
                "source_root": str(root_for_manifest),
                "included_file_count": len(records),
                "included_bytes": used,
                "included_human": human_size(used),
                "files": [asdict(r) for r in records],
                "skipped": skipped,
                "security_note": (
                    "Nomes sensiveis e padroes fortes de token/chave sao excluidos automaticamente. "
                    "A verificacao e heuristica; revise o manifesto antes de compartilhar."
                ),
                **extra_manifest,
                **export_readiness(package_type,root_for_manifest,records,skipped,extra_manifest),
            }
            zf.writestr(manifest_name, json.dumps(manifest, ensure_ascii=False, indent=2))
            zf.writestr(tree_name, tree)
            zf.writestr(readme_name, readme_text.strip() + "\n")

        # Integridade do container + hashes de todos os arquivos de origem inseridos.
        with zipfile.ZipFile(temporary, "r") as zf:
            bad = zf.testzip()
            if bad:
                raise ValueError(f"Falha de integridade no ZIP: {bad}")
            names = zf.namelist()
            duplicates = [name for name, count in Counter(names).items() if count > 1]
            if duplicates:
                raise ValueError("Entradas duplicadas no ZIP: " + ", ".join(duplicates))
            for record in records:
                if sha256_bytes(zf.read(record.path)) != record.sha256:
                    raise ValueError(f"Hash divergente dentro do ZIP: {record.path}")

        temporary.replace(output)
        return output, manifest
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def build_project_package(
    root: Path,
    output_dir: Path,
    stamp: str,
    max_file_mb: int,
    max_total_mb: int,
) -> tuple[Path, dict]:
    source_files = collect_project_files(root, output_dir)
    files = [
        (p, p.relative_to(root).as_posix(), "project")
        for p in source_files
    ]

    output = output_dir / f"LDPORTO_PROJETO_ATUAL_{stamp}.zip"
    readme = f"""
L.D.PORTO VIDEO ANALYZER - PACOTE DO PROJETO

Origem:
{root}

Objetivo:
Enviar a base atual de codigo/config/testes/docs para inspecao e evolucao.

Inclui:
- src / tests / config(s) / docs / schemas / scripts / examples
- assets/resources pequenos permitidos
- arquivos de projeto na raiz
- documentacao/metadados pequenos de models quando existirem

Exclui propositalmente:
- analysis/
- .venv / venv
- videos e audios
- modelos/pesos/binarios
- downloads/input
- caches
- previews/proxies
- ZIPs antigos e arquivos derivados de pacotes
- scripts exportadores antigos substituidos por exportar_ldporto.py
- credenciais/tokens detectados

Use este ZIP quando a tarefa for alterar, revisar ou evoluir o codigo.
"""

    return write_zip_atomic(
        output=output,
        files=files,
        package_type="LDPORTO_PROJECT_EXPORT",
        root_for_manifest=root,
        max_file_mb=max_file_mb,
        max_total_mb=max_total_mb,
        extra_manifest={
            "analysis_included": False,
            "legacy_exporters_excluded": sorted(LEGACY_EXPORTER_NAMES),
        },
        readme_text=readme,
        manifest_name=".package/PROJECT_EXPORT_MANIFEST.json",
        tree_name=".package/PROJECT_EXPORT_TREE.txt",
        readme_name=".package/PROJECT_EXPORT_README.txt",
    )


def build_analysis_package(
    root: Path,
    analysis: Path,
    output_dir: Path,
    stamp: str,
    max_file_mb: int,
    max_total_mb: int,
    include_images: bool,
    max_images: int,
) -> tuple[Path, dict]:
    selected = collect_analysis_files(analysis, include_images, max_images)
    files = []
    for p, kind in selected:
        rel = p.relative_to(analysis).as_posix()
        arcname = f"analysis/{analysis.name}/{rel}"
        files.append((p, arcname, kind))

    safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", analysis.name)
    output = output_dir / f"CHATGPT_REVIEW_{safe_name}_{stamp}.zip"

    expected = list(ANALYSIS_ESSENTIAL_FILES)
    present = {p.name for p, _ in selected}
    missing_expected = [name for name in expected if name not in present]

    readme = f"""
L.D.PORTO VIDEO ANALYZER - PACOTE PARA SEGUNDA CURADORIA

Analise:
{analysis}

Objetivo:
Enviar evidencias textuais/estruturadas e imagens realmente referenciadas para
revisao editorial, camera e segunda curadoria no ChatGPT.

Ordem recomendada de leitura:
1. second_curation_package.json / .md (se existirem)
2. CHATGPT_ANALYSIS_HANDOFF.json / .md
3. video_understanding.json
4. main_moments.json / story_arcs.json
5. transcript.txt / transcript.srt / words.json
6. analysis_quality.json / quality_issues.json
7. camera_plan.json
8. camera_director_timeline.json / camera_director_debug.json
9. preview_validation.json
10. active_speaker.json / speaker-person mapping
11. master_timeline.json
12. analysis.json / evaluation_report

Exclui propositalmente:
- video/audio original
- cache/modelos/pesos
- previews de video pesados
- proxies
- credenciais/tokens detectados

Imagens referenciadas incluidas: {include_images}
Limite de imagens referenciadas: {max_images}

Use este ZIP quando a tarefa for analisar o RESULTADO de um video, escolher
melhores cortes ou fazer segunda curadoria. Nao precisa mandar o ZIP do projeto
junto, a menos que voce tambem queira alteracao de codigo.
"""

    return write_zip_atomic(
        output=output,
        files=files,
        package_type="LDPORTO_SECOND_CURATION_EXPORT",
        root_for_manifest=analysis,
        max_file_mb=max_file_mb,
        max_total_mb=max_total_mb,
        extra_manifest={
            "analysis_folder": analysis.name,
            "analysis_relative": analysis.relative_to(root).as_posix(),
            "referenced_images_enabled": include_images,
            "referenced_images_limit": max_images,
            "missing_expected_files": missing_expected,
            "source_running_lock":(analysis/'RUNNING.lock').is_file(),
        },
        readme_text=readme,
        manifest_name="ANALYSIS_EXPORT_MANIFEST.json",
        tree_name="ANALYSIS_EXPORT_TREE.txt",
        readme_name="ANALYSIS_EXPORT_README.txt",
    )


def print_package_result(label: str, path: Path, manifest: dict) -> None:
    print()
    print(f"[{label}] {manifest.get('export_state','ERROR')}")
    print(f"Arquivo : {path}")
    print(f"ZIP     : {human_size(path.stat().st_size)}")
    print(f"Arquivos: {manifest['included_file_count']}")
    print(f"Ignorados: {dict(Counter(x.get('reason', 'unknown') for x in manifest['skipped']))}")
    missing = manifest.get("missing_expected_files") or []
    if missing:
        print("Aviso - outputs esperados ainda ausentes:")
        for name in missing:
            print(f"  - {name}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="Raiz do projeto; auto-detectada por padrao.")
    parser.add_argument('--self-test',action='store_true',help='Validar exportador em pasta temporaria sem incluir dados pesados')
    parser.add_argument('--inspect-zip',help='Inspecionar integridade, colisoes e segredos de um ZIP existente sem modifica-lo')
    parser.add_argument('--visuals-on-demand', metavar='ZIP', help='Novo pacote com visuais de candidatos promovidos')
    parser.add_argument('--source-video', help='Fonte local para os visuais sob demanda')
    parser.add_argument('--candidate', action='append', default=[], help='Candidate ID solicitado; repetir para vários')
    parser.add_argument('--candidate-preview', action='store_true')
    parser.add_argument(
        "--mode",
        choices=("both", "project", "analysis"),
        default="both",
        help="O que exportar. Padrao: both.",
    )
    parser.add_argument(
        "--analysis",
        help="Pasta analysis/video_xxx especifica. Padrao: analise mais recente.",
    )
    parser.add_argument(
        "--output-dir",
        help="Pasta de saida. Padrao: <projeto>/pacotes_para_enviar.",
    )
    parser.add_argument("--project-max-file-mb", type=int, default=32)
    parser.add_argument("--project-max-total-mb", type=int, default=180)
    parser.add_argument("--analysis-max-file-mb", type=int, default=32)
    parser.add_argument("--analysis-max-total-mb", type=int, default=250)
    parser.add_argument("--max-images", type=int, default=40)
    parser.add_argument("--no-images", action="store_true")
    args = parser.parse_args()

    numeric = [
        args.project_max_file_mb,
        args.project_max_total_mb,
        args.analysis_max_file_mb,
        args.analysis_max_total_mb,
    ]
    if min(numeric) < 1 or args.max_images < 0:
        parser.error("Limites precisam ser positivos; --max-images pode ser zero.")
    return args


def main() -> int:
    args = parse_args()
    try:
        if args.inspect_zip:
            report=inspect_package(Path(args.inspect_zip).expanduser().resolve())
            print(json.dumps(report,ensure_ascii=False,indent=2))
            return 0 if report['status']=='PASS' else 2
        root = find_project_root(args.root)
        if args.self_test:
            report=exporter_self_test(root)
            print(json.dumps(report,ensure_ascii=False,indent=2))
            return 0 if report['status']=='PASS' else 2
        output_dir = (
            Path(args.output_dir).expanduser().resolve()
            if args.output_dir
            else (root / "pacotes_para_enviar").resolve()
        )
        output_dir.mkdir(parents=True, exist_ok=True)
        if args.visuals_on_demand:
            if not args.source_video or not args.candidate:
                raise ValueError('--visuals-on-demand exige --source-video e --candidate')
            sys.path.insert(0, str(root / 'src'))
            from ldporto.second_curation_export import generate_visuals_on_demand
            report = generate_visuals_on_demand(args.visuals_on_demand, args.source_video, args.candidate, output_dir, args.candidate_preview)
            print(json.dumps(report, ensure_ascii=False, indent=2))
            return 0
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")

        print("=" * 76)
        print("L.D.PORTO VIDEO ANALYZER - EXPORTADOR UNIFICADO")
        print("=" * 76)
        print("Projeto:", root)
        print("Saida  :", output_dir)
        print("Modo   :", args.mode)

        created: list[Path] = []
        complete=True

        if args.mode in {"both", "project"}:
            path, manifest = build_project_package(
                root,
                output_dir,
                stamp,
                args.project_max_file_mb,
                args.project_max_total_mb,
            )
            print_package_result("PROJETO", path, manifest)
            complete=complete and manifest.get('export_state')=='READY'
            created.append(path)

        if args.mode in {"both", "analysis"}:
            analysis = resolve_analysis_dir(root, args.analysis)
            if analysis is None:
                if args.mode == "analysis":
                    raise ValueError("Nenhuma pasta de analise encontrada em analysis/.")
                print()
                print("[ANALISE] Nao gerada: nenhuma pasta valida encontrada em analysis/.")
            else:
                print()
                print("Analise selecionada:", analysis)
                path, manifest = build_analysis_package(
                    root,
                    analysis,
                    output_dir,
                    stamp,
                    args.analysis_max_file_mb,
                    args.analysis_max_total_mb,
                    include_images=not args.no_images,
                    max_images=args.max_images,
                )
                print_package_result("ANALISE", path, manifest)
                complete=complete and manifest.get('export_state')=='READY'
                created.append(path)

        print()
        print("Concluido.")
        if created:
            print("Pacotes criados:")
            for p in created:
                print("  -", p)
        print()
        print("Dica: para uso normal, basta rodar:")
        print("  py -3.11 exportar_ldporto.py")
        return 0 if complete else 2

    except (OSError, ValueError, zipfile.BadZipFile) as exc:
        print(f"ERRO: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
