"""Download only official public vision assets; never downloads a video."""
from pathlib import Path
import hashlib
import urllib.request
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
ASSETS = {
    "face_detection_yunet_2023mar.onnx": (
        "https://media.githubusercontent.com/media/opencv/opencv_zoo/main/models/"
        "face_detection_yunet/face_detection_yunet_2023mar.onnx", 200000),
    "face_recognition_sface_2021dec.onnx": (
        "https://media.githubusercontent.com/media/opencv/opencv_zoo/main/models/"
        "face_recognition_sface/face_recognition_sface_2021dec.onnx", 30000000),
    "face_landmarker.task": (
        "https://storage.googleapis.com/mediapipe-models/face_landmarker/"
        "face_landmarker/float16/1/face_landmarker.task", 3000000),
}

# Generated by GitHub Copilot - Oct-05-2026
EXPECTED_SHA256 = {
    "face_detection_yunet_2023mar.onnx":"8f2383e4dd3cfbb4553ea8718107fc0423210dc964f9f4280604804ed2552fa4",
    "face_recognition_sface_2021dec.onnx":"0ba9fbfa01b5270c96627c4ef784da859931e02f04419c829e83484087c34e79",
    "face_landmarker.task":"64184e229b263107bc2b804c6625db1341ff2bb731874b0bcc2fe6544e0bc9ff",
}


# Generated by GitHub Copilot - Oct-05-2026
def checksum(path):
    """Stream a model checksum without loading its bytes into memory."""
    value=hashlib.sha256()
    with path.open('rb') as handle:
        for block in iter(lambda:handle.read(1024*1024),b''):
            value.update(block)
    return value.hexdigest()


# Generated by GitHub Copilot - Oct-05-2026
def main():
    """Download official models atomically and require the source-package trusted hashes."""
    folder = ROOT/"models"
    folder.mkdir(exist_ok=True)
    manifest = {}
    for name, (url, min_size) in ASSETS.items():
        path = folder/name
        if not path.is_file() or path.stat().st_size < min_size or checksum(path)!=EXPECTED_SHA256[name]:
            print("Baixando "+name+"…", flush=True)
            temporary = path.with_suffix(path.suffix+".part")
            temporary.unlink(missing_ok=True)
            request = urllib.request.Request(url, headers={"User-Agent": "LDPortoAnalyzer/1.0"})
            try:
                with urllib.request.urlopen(request, timeout=60) as response, temporary.open("wb") as handle:
                    total=0
                    while block := response.read(1024*1024):
                        total+=len(block)
                        if total>100*1024**2:
                            raise ValueError('Asset excede limite esperado.')
                        handle.write(block)
                if temporary.stat().st_size < min_size or checksum(temporary)!=EXPECTED_SHA256[name]:
                    raise ValueError('Hash de modelo diverge do manifesto confiavel; asset nao instalado.')
                temporary.replace(path)
            finally:
                temporary.unlink(missing_ok=True)
        h = hashlib.sha256()
        with path.open("rb") as f:
            while block := f.read(1024*1024):
                h.update(block)
        manifest[name] = {"url": url, "sha256": h.hexdigest(), "size": path.stat().st_size}
    temporary=folder/'vision_models_manifest.json.tmp'
    temporary.write_text(json.dumps(manifest,indent=2),encoding='utf-8')
    temporary.replace(folder/'vision_models_manifest.json')
    print("Modelos visuais disponíveis. Checksums locais registrados.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        raise SystemExit("Falha ao baixar modelos: "+str(exc))
