#!/usr/bin/env python3
"""Compare grounded analyzer outputs; tolerate missing legacy/review artifacts."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'src'))
from ldporto.core import write_json, scrub


# Generated by GitHub Copilot - Oct-05-2026
def analysis_folder(value):
    """Select an explicit run or the only extracted run; never pick ambiguously."""
    folder=Path(value).expanduser().resolve()
    if not folder.is_dir():
        raise ValueError('Use uma pasta extraida, nao um ZIP: '+str(folder))
    if any((folder/name).is_file() for name in ('run_manifest.json','analysis_summary.json','analysis_quality.json','analysis.json')):
        return folder
    runs=sorted({path.parent for path in folder.glob('analysis/*/run_manifest.json')})
    if len(runs)!=1:
        raise ValueError('Especifique a pasta de uma unica analise; encontrados '+str(len(runs)))
    return runs[0]


# Generated by GitHub Copilot - Oct-05-2026
def read_optional(folder,name,maximum=32*1024**2):
    """Treat absent or oversized review evidence as unavailable, not measured zero."""
    path=folder/name
    if not path.is_file() or path.stat().st_size>maximum:
        return None
    try:
        with path.open(encoding='utf-8-sig') as handle:
            return json.load(handle,parse_constant=lambda value: (_ for _ in ()).throw(ValueError('nonfinite JSON')))
    except (OSError,ValueError):
        return None


# Generated by GitHub Copilot - Oct-05-2026
def records(value,*keys):
    """Unwrap either a legacy list or an explicitly named collection envelope."""
    if isinstance(value,list):
        return value
    if isinstance(value,dict):
        for key in keys:
            if isinstance(value.get(key),list):
                return value[key]
    return None


# Generated by GitHub Copilot - Oct-05-2026
def collect_run_metrics(value):
    """Read observed metrics without inference from missing critical raw artifacts."""
    folder=analysis_folder(value)
    summary=read_optional(folder,'analysis_summary.json') or {}
    quality=read_optional(folder,'analysis_quality.json') or summary.get('analysis_quality') or {}
    manifest=read_optional(folder,'run_manifest.json') or {}
    old_summary=read_optional(folder,'video_summary.json') or {}
    words=records(read_optional(folder,'words.json'),'words')
    speakers=records(read_optional(folder,'speakers.json'),'speakers')
    participants=records(read_optional(folder,'participants.json'),'participants')
    moments=records(read_optional(folder,'main_moments.json'),'main_moments','candidates')
    qas=records(read_optional(folder,'questions_answers.json'),'questions_answers','question_candidates')
    qa_metrics=read_optional(folder,'qa_summary.json') or summary.get('qa_metrics') or {}
    semantic=summary.get('semantic_metrics') or quality
    candidate_metrics=summary.get('candidate_metrics') or quality
    preview=read_optional(folder,'preview_validation.json') or {}
    artifact_metrics=read_optional(folder,'artifact_metrics.json') or {}
    curation_export = read_optional(folder, 'second_curation_export.json') or summary.get('second_curation_export') or {}
    metadata=summary.get('metadata') or {}
    raw=read_optional(folder,'analysis.json',4*1024**2)
    if isinstance(raw,dict):
        metadata=metadata or raw.get('metadata') or {}
    director=records(read_optional(folder,'camera_director_timeline.json'),'timeline')
    duration=metadata.get('duration') or old_summary.get('duration')
    focus=quality.get('resolved_focus_coverage')
    if focus is None and director is not None and isinstance(duration,(int,float)) and duration>0:
        focus=sum(row.get('end',0)-row.get('start',0) for row in director if row.get('focus_person') or row.get('split'))/duration
    export_manifest=None
    for candidate in (folder/'ANALYSIS_EXPORT_MANIFEST.json',folder.parent.parent/'ANALYSIS_EXPORT_MANIFEST.json'):
        if candidate.is_file():
            export_manifest=read_optional(candidate.parent,candidate.name)
            break
    export_manifest=export_manifest or {}
    counts=summary.get('counts') or {}
    word_count=len(words) if words is not None else counts.get('words')
    low_words=records(read_optional(folder,'low_confidence_words.json'),'low_confidence_words','words')
    has_editorial_layer=participants is not None and all('status' in row for row in participants)
    answered=sum(bool(row.get('answer') and row.get('answer_segment_ids')) for row in qas) if qas is not None else None
    output={
        'analysis_status':manifest.get('analysis_status') or summary.get('analysis_status'),
        'root_cause_stage':manifest.get('root_cause_stage') or summary.get('root_cause_stage'),
        'root_cause_status':manifest.get('root_cause_status'), 'source_hash':metadata.get('sha256'),
        'runtime_by_stage':summary.get('stage_runtime') or (raw or {}).get('stage_runtime') if isinstance(raw,dict) else summary.get('stage_runtime'),
        'word_count':word_count,
        'low_confidence_word_fraction':quality.get('low_confidence_word_fraction',len(low_words)/word_count if low_words is not None and word_count else None),
        'diarization_available':quality.get('diarization_available',quality.get('diarization_availability')),
        'speaker_count':len(speakers) if speakers is not None else quality.get('speaker_count'),
        'diarization_coverage':quality.get('diarization_speech_coverage',quality.get('diarization_coverage')),
        'words_with_speaker_fraction':quality.get('words_with_speaker_fraction'),
        'raw_track_count':quality.get('raw_track_count'), 'valid_track_count':quality.get('valid_track_count'),
        'persistent_person_count':quality.get('persistent_person_count'),
        'meaningful_persistent_person_count':quality.get('meaningful_persistent_person_count'),
        'editorial_participant_count':len(participants) if has_editorial_layer else counts.get('editorial_participant_count'),
        'participant_count_reported_legacy':len(participants) if participants is not None and not has_editorial_layer else None,
        'median_track_duration':quality.get('median_track_duration'),
        'micro_track_ratio':quality.get('micro_track_ratio'), 'legacy_short_track_ratio':quality.get('short_track_ratio'),
        'tracks_without_face_embedding_fraction':quality.get('tracks_without_face_embedding_fraction'),
        'active_speaker_coverage':quality.get('active_speaker_coverage'),
        'topic_count':quality.get('topic_count',counts.get('topics')),
        'program_section_count':counts.get('program_sections'), 'story_arc_count':counts.get('story_arcs'),
        'question_candidate_count':qa_metrics.get('question_candidate_count',len(qas) if qas is not None else None),
        'answered_question_count':qa_metrics.get('answered_question_count',answered),
        'complete_qa_count':qa_metrics.get('complete_qa_count',sum(bool(row.get('question_answer_complete')) for row in qas) if qas is not None else None),
        'candidates_before_dedup':candidate_metrics.get('candidates_before_dedup'),
        'candidates_after_dedup':candidate_metrics.get('candidates_after_dedup',len(moments) if moments is not None else None),
        'commercial_candidate_count':sum(row.get('content_type') in ('advertisement','sponsor_read','merchandising') for row in moments)
                                     if moments is not None and all('content_type' in row for row in moments) else None,
        'final_shortlist_count':candidate_metrics.get('final_shortlist_count'),
        'semantic_fallback_ratio':semantic.get('semantic_fallback_ratio'),
        'semantic_seconds':semantic.get('semantic_seconds'), 'global_review_seconds':semantic.get('global_review_seconds'),
        'timeline_temporal_coverage':quality.get('timeline_temporal_coverage',quality.get('camera_timeline_coverage')),
        'resolved_focus_coverage':focus,
        'source_preservation_fraction':quality.get('source_preservation_fraction',quality.get('full_frame_fraction')),
        'switch_rate_per_minute':quality.get('switch_rate_per_minute',quality.get('director_switches_per_minute')),
        'preview_verifier_status':preview.get('status','skipped' if preview.get('verifier_uses_rendered_frames') is False else 'not_measured'),
        'artifact_bytes':artifact_metrics.get('artifact_bytes'),
        'export_state':export_manifest.get('export_state','legacy_state_not_recorded' if export_manifest else None),
        'review_skipped_artifact_count':len(export_manifest.get('skipped',[])) if export_manifest else None,
    }
    for name in ('topics','story_arcs','program_sections'):
        if output.get({'topics':'topic_count','story_arcs':'story_arc_count','program_sections':'program_section_count'}[name]) is None:
            collection=records(read_optional(folder,name+'.json'),name)
            if collection is not None:
                output[{'topics':'topic_count','story_arcs':'story_arc_count','program_sections':'program_section_count'}[name]]=len(collection)
    for key in ('track_duration_p25','track_duration_p50','track_duration_p75','track_duration_p95'):
        output[key]=quality.get(key)
    runtime = output.get('runtime_by_stage') or {}
    measured_stage_seconds = [row.get('elapsed_seconds') for row in runtime.values() if isinstance(row, dict) and isinstance(row.get('elapsed_seconds'), (int, float))]
    output['total_measured_stage_runtime_seconds'] = sum(measured_stage_seconds) if measured_stage_seconds else None
    output['execution_scope'] = summary.get('execution_scope') or metadata.get('execution_scope') or 'full_pipeline'
    for key in ('transcription_coverage', 'speech_coverage', 'timestamp_anomaly_count', 'segments_with_speaker_fraction',
                'micro_track_count', 'confirmed_track_count', 'embedding_success_fraction', 'id_switch_count', 'probable_id_switch_count',
                'simultaneous_identity_conflict_count', 'reid_merge_count', 'reid_rejected_merge_count',
                'speaker_person_mapping_coverage', 'speaker_person_high_confidence_coverage', 'active_speaker_high_confidence_coverage',
                'ambiguous_mapping_fraction', 'conflicting_mapping_fraction', 'mapping_support_window_count',
                'merged_topic_count', 'major_section_count', 'complete_story_arc_count', 'partial_story_arc_count', 'discussion_block_count',
                'story_payoff_coverage', 'duration_violation_count', 'excluded_commercial_count', 'excluded_eligibility_count',
                'editorial_decision_coverage', 'fallback_camera_fraction', 'safe_crop_coverage', 'quality_status',
                'smart_zoom_enabled', 'zoom_event_count', 'zoom_events_per_minute', 'mean_zoom_factor', 'max_zoom_factor',
                'rapid_zoom_reversal_count', 'short_zoom_count', 'zoom_pumping_score', 'zoom_jitter_score', 'zoom_target_loss_count',
                'safe_zoom_fraction', 'source_preserve_fraction', 'preview_zoom_validation_fraction',
                'candidate_topic_coverage', 'candidate_audio_quality_coverage', 'candidate_technical_quality_coverage'):
        output[key] = quality.get(key)
    for key in ('semantic_repair_attempt_ratio', 'semantic_repair_success_ratio', 'semantic_valid_chunk_ratio',
                'semantic_initial_valid_ratio', 'semantic_cache_hit_ratio', 'semantic_inference_call_count', 'total_inference_call_count'):
        output[key] = semantic.get(key)
    output.update(alternate_count=candidate_metrics.get('alternate_count'),
                  serialization_seconds=artifact_metrics.get('serialization_seconds'),
                  peak_process_memory_bytes=artifact_metrics.get('peak_process_memory'),
                  export_package_bytes=export_manifest.get('package_bytes') or export_manifest.get('compressed_bytes'),
                  dangling_reference_count=len(export_manifest.get('unresolved_package_references', [])) if export_manifest else None,
                  preview_canary_count=preview.get('canary_count'),
                  preview_validated=preview.get('status') == 'ok' and preview.get('verifier_uses_rendered_frames') is True,
                  second_curation_package_bytes=curation_export.get('bytes'), second_curation_file_count=curation_export.get('file_count'),
                  second_curation_dangling_refs=(curation_export.get('validation') or {}).get('dangling_references'),
                  second_curation_visual_count=curation_export.get('visual_count'), second_curation_candidates=curation_export.get('candidate_count'),
                  second_curation_state=curation_export.get('state'))
    for capability in ('editorial_ready', 'transcript_ready', 'visual_ready', 'speaker_person_ready', 'camera_ready', 'preview_ready'):
        output['second_curation_' + capability] = curation_export.get('readiness', {}).get(capability)
    curation = read_optional(folder, 'second_curation_package.json') or {}
    catalog = curation.get('candidates', [])
    if catalog:
        for key in ('topic', 'audio_quality', 'technical_quality'):
            output['candidate_' + key + '_coverage'] = sum(row.get(key) is not None for row in catalog) / len(catalog)
        coverage = [row['evidence_coverage'] for row in catalog if isinstance(row.get('evidence_coverage'), (int, float))]
        output['ranking_evidence_coverage_mean'] = sum(coverage) / len(coverage) if coverage else None
        shortlist = set((curation.get('filtering_summary') or {}).get('default_shortlist_ids', []))
        from ldporto.editorial import classify_content
        output['commercial_in_shortlist'] = sum(classify_content(row.get('transcript_literal', ''))['eligibility'] == 'excluded' for row in catalog if row['candidate_id'] in shortlist)
    else:
        output['ranking_evidence_coverage_mean'] = None
        output['commercial_in_shortlist'] = None
    if output.get('complete_story_arc_count') is None:
        arcs = records(read_optional(folder, 'story_arcs.json'), 'story_arcs')
        if arcs is not None:
            output['complete_story_arc_count'] = sum(row.get('kind') == 'complete_story' or row.get('completeness') == 'supported_setup_development_payoff' for row in arcs)
            output['story_payoff_coverage'] = sum(row.get('payoff') is not None for row in arcs) / len(arcs) if arcs else None
    export_skipped=export_manifest.get('skipped',[])
    return {'metrics':output,'provenance':{'folder_name':folder.name,
                'evidence_kind':'existing_run_artifacts_not_new_inference',
                'missing_in_review_package':[row.get('path') for row in export_skipped],
                'missing_in_original_run':'not_inferred_from_review_omissions',
                'runtime_accuracy_ground_truth':'not_supplied'}}


# Generated by GitHub Copilot - Oct-05-2026
def compare_runs(old,new):
    """Return descriptive deltas; claims of accuracy require annotated ground truth."""
    before,after=collect_run_metrics(old),collect_run_metrics(new)
    old_hash,new_hash=before['metrics']['source_hash'],after['metrics']['source_hash']
    same_source=bool(old_hash and new_hash and old_hash==new_hash)
    changes={}
    for key in sorted(set(before['metrics'])|set(after['metrics'])):
        left,right=before['metrics'].get(key),after['metrics'].get(key)
        numeric=all(isinstance(value,(int,float)) and not isinstance(value,bool) and math.isfinite(value) for value in (left,right))
        changes[key]={'old':left,'new':right,'delta':right-left if numeric else None,
                      'comparison_status':'measured' if left is not None and right is not None else 'missing_evidence'}
        if before['metrics'].get('execution_scope') != after['metrics'].get('execution_scope') and any(term in key for term in ('runtime', 'seconds', 'semantic_inference_call_count', 'total_inference_call_count')):
            changes[key]['delta'] = None
            changes[key]['comparison_status'] = 'not_comparable_execution_scope'
    return {'schema_version':'1.0','same_source_confirmed':same_source,
            'comparison_type':'descriptive_artifact_comparison_not_accuracy_validation',
            'old':before,'new':after,'changes':changes,
            'limitations':['Sem rerun do mesmo video nao ha melhoria runtime comprovada.',
                           'Sem anotacoes nao ha medida de acuracia.',
                           'Arquivo omitido pelo review exporter nao prova ausencia no run original.']}


# Generated by GitHub Copilot - Oct-05-2026
def comparison_markdown(report):
    """Render metrics only; never embed transcript or private benchmark passages."""
    lines=['# Comparacao De Execucoes','','Comparacao descritiva, nao validacao de acuracia.',
           '','Mesmo hash de fonte confirmado: '+str(report['same_source_confirmed']),
           '','| Metrica | OLD | NEW | Delta |','|---|---|---|---|']
    for name,change in report['changes'].items():
        if isinstance(change['old'],dict) or isinstance(change['new'],dict):
            continue
        lines.append('| '+name+' | '+str(change['old'])+' | '+str(change['new'])+' | '+str(change['delta'])+' |')
    lines.extend(['','## Limitacoes','',*['- '+item for item in report['limitations']]])
    return '\n'.join(lines)+'\n'


# Generated by GitHub Copilot - Oct-05-2026
def audit_existing_editorial(value):
    """Reprocess exported candidates only; no ASR/vision/LLM runtime or accuracy claim."""
    from ldporto.editorial import normalize_context,classify_content,rank_candidate,deduplicate_candidates,require_pt_br
    folder=analysis_folder(value)
    main=records(read_optional(folder,'main_moments.json'),'main_moments','candidates')
    if main is None:
        return {'status':'unavailable','reason':'main_moments_missing_in_review_package'}
    editorial=records(read_optional(folder,'editorial_moments.json'),'moments','editorial_moments') or []
    by_id={row.get('moment_id'):row for row in editorial if row.get('moment_id')}
    normalized=[]
    invalid=0
    for original in main:
        moment_id=original.get('moment_id')
        start,end=original.get('ideal_start'),original.get('ideal_end')
        if (not moment_id or not all(isinstance(time,(int,float)) and not isinstance(time,bool) and math.isfinite(time) for time in (start,end))
                or not 0<=start<end):
            invalid+=1
            continue
        literal=(original.get('core_moment') or {}).get('text') or by_id.get(moment_id,{}).get('text') or ''
        evidence=original.get('evidence_segment_ids',[])
        classification=classify_content(literal,evidence)
        row={**original,**normalize_context(original),'text':literal,'commercial_classification':classification,
             'content_type':classification['content_type'],'commercial_score':classification['commercial_score']}
        normalized.append(rank_candidate(row))
    deduped,metrics=deduplicate_candidates(normalized)
    review=read_optional(folder,'ollama_editorial_review.json') or {}
    wrong_language=None
    if isinstance(review,dict) and review.get('overview'):
        try:
            require_pt_br([review['overview']])
            wrong_language=False
        except ValueError:
            wrong_language=True
    return {'status':'measured_from_existing_review_artifacts','evidence_kind':'offline_rules_applied_to_real_exported_candidates',
            'new_video_runtime_executed':False,'asr_vision_llm_rerun':False,'accuracy_ground_truth':'not_supplied',
            'candidate_metrics':metrics,'invalid_candidate_count':invalid,
            'context_enum_values':sorted({row['context_requirement'] for row in normalized}),
            'commercial_candidate_count_before_dedup':sum(row['content_type'] in ('advertisement','sponsor_read','merchandising') for row in normalized),
            'commercial_candidate_count_after_dedup':sum(row['content_type'] in ('advertisement','sponsor_read','merchandising') for row in deduped),
            'editorial_shortlist_eligible_count':sum(row['default_shortlist_eligible'] for row in deduped),
            'legacy_global_review_language_rejected':wrong_language,
            'candidate_ids_after_dedup':[row['moment_id'] for row in deduped],
            'candidate_ids_reference_scope':'original_review_main_moments.json',
            'no_transcript_copied_into_report':True}


# Generated by GitHub Copilot - Oct-05-2026
def main():
    """Write comparison artifacts outside both read-only input directories."""
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('old')
    parser.add_argument('new')
    parser.add_argument('--output-dir',default='benchmark_comparison')
    parser.add_argument('--audit-editorial',action='store_true',help='Aplicar regras deterministicas aos candidatos exportados, sem rerun do video')
    args=parser.parse_args()
    output=Path(args.output_dir).expanduser().resolve()
    for source in (analysis_folder(args.old),analysis_folder(args.new)):
        if output==source or source in output.parents:
            parser.error('A comparacao deve ser escrita fora das pastas de evidencia.')
    report=compare_runs(args.old,args.new)
    if args.audit_editorial:
        report['existing_editorial_audit']=audit_existing_editorial(args.old)
    output.mkdir(parents=True,exist_ok=True)
    write_json(output/'benchmark_comparison.json',report)
    (output/'benchmark_comparison.md').write_text(comparison_markdown(report),encoding='utf-8')
    print(output/'benchmark_comparison.md')
    return 0


if __name__=='__main__':
    try:
        raise SystemExit(main())
    except (OSError,ValueError) as exc:
        print(scrub(exc),file=sys.stderr)
        raise SystemExit(1)