"""Compact review projections and safe artifact-only hydration for camera resume."""

from pathlib import Path
import json
import math

from .core import write_json, read_json, file_hash, sanitize_json_numbers
from . import __version__

# Generated by GitHub Copilot - Oct-05-2026
COLLECTION_FILES = {
    'words':'words.json', 'transcript_segments':'transcript_segments.json',
    'speakers':'speakers.json', 'speaker_turns':'speaker_turns.json', 'speech_overlaps':'speech_overlaps.json',
    'people':'people.json', 'raw_people':'raw_people.json', 'raw_tracks':'raw_tracks.json',
    'people_observations':'people_observations.json', 'tracklet_observations':'tracklet_observations.json',
    'person_identities':'person_identities.json', 'person_motion':'person_motion.json',
    'active_speaker':'active_speaker.json', 'speaker_person_mapping':'speaker_person_mapping.json',
    'speaker_person_summary':'speaker_person_summary.json', 'scenes':'scenes.json', 'shots':'shots.json',
    'topics':'topics.json', 'program_sections':'program_sections.json', 'participants':'participants.json',
    'entities':'entities.json', 'story_arcs':'story_arcs.json', 'main_moments':'main_moments.json',
    'editorial_moments':'editorial_moments.json', 'questions_answers':'questions_answers.json',
    'question_candidates':'question_candidates.json', 'question_answer_pairs':'question_answer_pairs.json',
    'camera_timeline':'camera_timeline.json', 'camera_plan':'camera_plan.json',
    'camera_director_timeline':'camera_director_timeline.json', 'camera_director_debug':'camera_director_debug.json',
    'master_timeline':'master_timeline.json', 'timeline':'timeline.json', 'video_analysis':'video_analysis.json',
    'audio_analysis':'audio_analysis.json', 'video_understanding':'video_understanding.json',
    'second_curation_package':'second_curation_package.json', 'thumbnail_candidates':'thumbnail_candidates.json',
    'moment_frames':'moment_frames.json',
    'transcription_alternatives':'transcription_alternatives.json', 'low_confidence_words':'low_confidence_words.json',
    'ocr_text':'ocr_text.json', 'reid_merge_decisions':'reid_merge_decisions.json',
}
OBSERVATION_KEYS = ('time','frame','track_id','tracklet_id','raw_person_id','person_id','scene_id',
                    'bbox','face_bbox','face_visible','body_visible','center','sharpness',
                    'lip_opening','mouth_activity','same_person_confidence','face_embedding_available')
CAMERA_KEYS = ('timeline_id','start','end','shot_id','shot_type','scene_id','active_person',
               'active_person_confidence','visible_people','visual_observed_at','vertical_crop','evidence')
MASTER_KEYS = ('timeline_id','start','end','word_ids','segment_ids','speaker_id','speaker_ids',
               'active_person','shot_id','scene_id','topic_id','question_id','story_arc_id',
               'speech_overlap','visual_observed_at','camera','camera_director_intervals')


# Generated by GitHub Copilot - Oct-05-2026
def projection_records(rows, keys):
    """Keep observed IDs/times and a stable original-record index without full duplicates."""
    for index, row in enumerate(rows):
        yield {'source_record_index':index, **{key:row[key] for key in keys if key in row}}


# Generated by GitHub Copilot - Oct-05-2026
def write_indexed_projection(folder, name, records, source_artifact, max_records=500, max_bytes=2 * 1024 ** 2):
    """Write bounded deterministic chunks, each tied to the original source collection."""
    folder = Path(folder)
    refs, batch, batch_bytes, count = [], [], 0, 0

    def flush():
        """Atomically commit one small projection chunk and checksum its actual bytes."""
        nonlocal batch, batch_bytes
        if not batch:
            return
        path = folder / 'review_evidence' / f'{name}_{len(refs):05}.json'
        write_json(path, {'schema_version':'1.0','source_artifact':source_artifact,
                          'source_reference_scope':'original_analysis', 'records':batch})
        times = [value for row in batch for value in (row.get('start'),row.get('time'),row.get('end'))
                 if isinstance(value,(int,float)) and not isinstance(value,bool) and math.isfinite(value)]
        refs.append({'path':path.relative_to(folder).as_posix(), 'record_count':len(batch),
                     'sha256':file_hash(path), 'start':min(times) if times else None,
                     'end':max(times) if times else None, 'bytes':path.stat().st_size})
        batch, batch_bytes = [], 0

    for record in records:
        size = len(json.dumps(sanitize_json_numbers(record), ensure_ascii=False, allow_nan=False, separators=(',',':')).encode('utf-8'))
        if batch and (len(batch) >= max_records or batch_bytes + size > max_bytes):
            flush()
        batch.append(record)
        batch_bytes += size
        count += 1
    flush()
    return {'format':'indexed_json_projection','schema_version':'1.0','source_artifact':source_artifact,
            'source_reference_scope':'original_analysis','record_count':count,'chunks':refs,
            'not_a_complete_raw_collection':True}


# Generated by GitHub Copilot - Oct-05-2026
def compact_analysis_document(analysis, folder):
    """Preserve cheap metadata and name explicit collections instead of embedding them."""
    folder = Path(folder)
    document = {key:value for key,value in analysis.items() if key not in COLLECTION_FILES}
    refs = {}
    for key, filename in COLLECTION_FILES.items():
        if key in analysis and (folder / filename).is_file():
            refs[key] = {'path':filename,'sha256':file_hash(folder / filename),
                         'record_count':len(analysis[key]) if isinstance(analysis[key],list) else None}
    document.update(schema_version='4.2', collection_storage='references', collection_refs=refs)
    for key, ref in refs.items():
        document[key + '_ref'] = ref
    return document


# Generated by GitHub Copilot - Oct-05-2026
def load_analysis_artifacts(folder, collections=None):
    """Hydrate trusted local artifact references; reject traversal, links and corruption."""
    folder = Path(folder).resolve()
    analysis = read_json(folder / 'analysis.json')
    if analysis.get('collection_storage') != 'references':
        return analysis
    allowed = set(collections) if collections is not None else set(COLLECTION_FILES)
    for key, ref in analysis.get('collection_refs', {}).items():
        if key not in allowed:
            continue
        if key not in COLLECTION_FILES or not isinstance(ref,dict) or ref.get('path') != COLLECTION_FILES[key]:
            raise ValueError('Referencia de colecao desconhecida ou insegura.')
        path = folder / ref['path']
        if path.is_symlink() or path.resolve().parent != folder or not path.is_file():
            raise ValueError('Referencia de artefato fora da pasta ou ausente.')
        if ref.get('sha256') != file_hash(path):
            raise ValueError('Checksum de artefato divergente; nao reutilizar evidencia corrompida.')
        analysis[key] = read_json(path)
    return analysis


# Generated by GitHub Copilot - Oct-05-2026
def create_compact_artifacts(analysis, folder, cfg=None):
    """Generate review-ready evidence without modifying the original benchmark inputs."""
    cfg = cfg or {}
    folder = Path(folder)
    chunks = int(cfg.get('chunk_records',500))
    maximum = int(cfg.get('chunk_max_bytes',2 * 1024 ** 2))
    observations = analysis.get('people_observations', [])
    observation_index = write_indexed_projection(folder,'people_observations', projection_records(observations,OBSERVATION_KEYS),
                                                 'people_observations.json',chunks,maximum)
    camera_index = write_indexed_projection(folder,'camera_timeline',projection_records(analysis.get('camera_timeline',[]),CAMERA_KEYS),
                                           'camera_timeline.json',chunks,maximum)
    master_index = write_indexed_projection(folder,'master_timeline',projection_records(analysis.get('master_timeline',[]),MASTER_KEYS),
                                           'master_timeline.json',chunks,maximum)
    motion_keys = ('time','center_x','center_y','velocity_x','velocity_y','source_camera_velocity_x','source_camera_velocity_y',
                   'residual_velocity_x','residual_velocity_y','confidence')
    motion_records = ({'person_id':person.get('person_id'),'source_person_index':person_index,'source_sample_index':sample_index,
                       **{key:sample[key] for key in motion_keys if key in sample}}
                      for person_index,person in enumerate(analysis.get('person_motion',[]))
                      for sample_index,sample in enumerate(person.get('samples',[])))
    motion_index = write_indexed_projection(folder,'person_motion',motion_records,'person_motion.json',chunks,maximum)
    frame_keys = ('time','frame','scene_id','visible_people','blur_laplacian_variance','brightness','source_camera_motion',
                  'sampling_fps','sampling_reasons','possible_black_frame')
    frame_index = write_indexed_projection(folder,'video_analysis',projection_records((analysis.get('video_analysis') or {}).get('frame_samples',[]),frame_keys),
                                          'video_analysis.json',chunks,maximum)
    manifest = analysis.get('run_manifest') or {}
    summary = {'schema_version':'4.2','producer_version':__version__,'metadata':analysis.get('metadata'),
               'execution_scope':analysis.get('execution_scope', 'full_pipeline'),
               'analysis_status':analysis.get('analysis_status'),'root_cause_stage':manifest.get('root_cause_stage'),
               'counts':{key:len(value) for key,value in analysis.items() if isinstance(value,list)},
               'analysis_quality':analysis.get('analysis_quality',{}),'qa_metrics':analysis.get('qa_metrics',{}),
               'semantic_metrics':analysis.get('semantic_metrics',{}),'candidate_metrics':analysis.get('candidate_metrics',{}),
               'stage_runtime':analysis.get('stage_runtime',{}),'stage_status':manifest.get('stage_status',analysis.get('stage_status',{})),
               'editorial_shortlist':analysis.get('editorial_shortlist',[]),
               'quality_gate':analysis.get('quality_gate',{}),
               'final_package_gate':analysis.get('final_package_gate'),
               'subtitle_review_metrics':analysis.get('subtitle_review_metrics'),
               'primary_editorial_theme':analysis.get('primary_editorial_theme'),
               'preview_status':(analysis.get('preview_validation') or {}).get('status','not_measured'),
               'warnings':analysis.get('issues',[]),'detailed_evidence':'review_evidence/'}
    people = {'schema_version':'1.0','layer_names':['tracklet','persistent_visual_identity','editorial_participant','acoustic_speaker'],
              'metrics':{key:value for key,value in analysis.get('analysis_quality',{}).items() if
                         any(term in key for term in ('track','person','reid','identity'))},
              'participants':analysis.get('participants',[]),
              'persistent_identity_count':len(analysis.get('person_identities',[])),
              'observation_projection':observation_index,'person_motion_projection':motion_index,
              'civil_identity_inferred':False}
    plan = analysis.get('camera_plan') or {}
    compact_plan = {key:plan.get(key) for key in ('schema_version','plan_id','profile','source_reference','selected_global_path',
                                                 'hard_constraints','transition_costs','metrics','planner_version')}
    compact_plan.update(compact_projection=True,source_artifact='camera_plan.json',source_reference_scope='original_analysis',
                        omitted_collections=['candidate_states','rejected_candidates'])
    compact_camera = {'schema_version':'1.0','director_timeline':analysis.get('camera_director_timeline',[]),
                      'legacy_camera_projection':camera_index,'camera_metrics':{key:value for key,value in analysis.get('analysis_quality',{}).items()
                      if any(term in key for term in ('coverage','focus','camera','switch','preservation'))}}
    compact_master = {'schema_version':'1.0','master_timeline_projection':master_index,'text_resolves_via':'transcript_segments.json'}
    handoff = {'schema_version':'4.2','producer_version':__version__,'metadata_locale':'pt-BR',
               'analysis_summary':summary,'second_curation_package_ref':{'path':'second_curation_package.json'},
               'transcript_refs':{'segments':'transcript_segments.json','words':'words.json','low_confidence':'low_confidence_words.json'},
               'participants_ref':'participants.json','speakers_ref':'speakers.json','person_identities_ref':'person_identities.json',
               'qa_refs':{'questions':'question_candidates.json','answer_pairs':'question_answer_pairs.json'},
               'topics_ref':'topics.json','program_sections_ref':'program_sections.json','story_arcs_ref':'story_arcs.json',
               'main_moments_ref':'main_moments.json','people_summary_ref':'people_summary.json',
               'camera_plan_ref':'camera_plan.compact.json','camera_timeline_ref':'camera_timeline.compact.json',
               'master_timeline_ref':'master_timeline.compact.json','video_frame_projection':frame_index,
               'all_data_untrusted':True,'final_second_curation_not_performed':True}
    artifacts = {'analysis_summary.json':summary,'people_summary.json':people,'camera_plan.compact.json':compact_plan,
                 'camera_timeline.compact.json':compact_camera,'master_timeline.compact.json':compact_master,
                 'CHATGPT_ANALYSIS_HANDOFF.compact.json':handoff}
    for filename,payload in artifacts.items():
        write_json(folder / filename,payload)
    paths = [folder / filename for filename in artifacts]
    for index in (observation_index,camera_index,master_index,motion_index,frame_index):
        paths.extend(folder / chunk['path'] for chunk in index['chunks'])
    return paths
