from copy import deepcopy
from pathlib import Path
import os
import yaml
from .director_config import DEFAULTS as DIRECTOR_DEFAULTS, resolve_config
from .editorial import DEFAULT_WEIGHTS

ROOT = Path(__file__).resolve().parents[2]
DEFAULTS = {
    "camera_director": {k: (v if k in ("enabled", "profile") else None) for k, v in DIRECTOR_DEFAULTS.items()},
    "language": "pt", "device": "auto", "compute_type": "auto",
    "offline": False, "strict": False,
    # Generated by GitHub Copilot - Oct-05-2026
    "preflight": {"allow_self_repair": False, "network_timeout_seconds": 5,
                  "repair_timeout_seconds": 600},
    "export": {"legacy_full_analysis": False, "chunk_records":500, "chunk_max_bytes":2097152},
    "download": {"max_height": 1080, "cookies_file": None},
    "audio": {"highpass_hz": 40, "denoise": False, "normalize": True,
              "silence_db": -40, "silence_min_seconds": 0.35,
              "separation": "off", "demucs_python": None,
              "isolated_file": None, "isolated_offset_seconds": 0.0},
    "transcription": {"model": "large-v3", "chunk_seconds": 240,
                      "overlap_seconds": 4, "beam_size": 5,
                      "vad_filter": True, "low_confidence": 0.60,
                      "multipass": True, "max_review_regions": 100,
                      "review_padding_seconds": 2, "import_file": None,
                      "glossary": "", "source_selection": "auto",
                      "allow_cpu_fallback": False},
    "diarization": {"enabled": True,
                    "model": "pyannote/speaker-diarization-community-1",
                    "num_speakers": None, "min_speakers": None,
                    "max_speakers": None, "import_file": None},
    "scenes": {"enabled": True, "threshold": 27, "min_seconds": 0.6},
    "shots": {"hard_cut_difference": 0.18},
    "vision": {"enabled": True, "adaptive_sampling": True, "sample_fps": 2, "speech_sample_fps": 6,
               "max_width": 960, "body_detection": True,
               "body_backend": "hog", "yolo_model": "yolo11n.pt",
               "yunet_model": "models/face_detection_yunet_2023mar.onnx",
               "sface_model": "models/face_recognition_sface_2021dec.onnx",
               "landmarker_model": "models/face_landmarker.task",
               "reid_threshold": 0.55, "reid_margin": 0.08,
               "track_max_gap_seconds": 1.2, "checkpoint_seconds": 30.0,
               # Generated by GitHub Copilot - Oct-05-2026
               "tracklet_min_visual_seconds": 1.0, "tracklet_min_observations": 3,
               "identity_min_visual_seconds": 3.0, "reid_candidate_limit": 64,
               "max_thumbnails": 120, "active_speaker": True,
               "association_min_correlation": 0.45,
               "association_min_margin": 0.20,
               "manual_mapping_file": None},
    "person_motion": {"smoothing_alpha": 0.35, "deadzone_per_second": 0.012,
                      "max_gap_seconds": 1.5},
    "active_speaker": {"backend": "heuristic_consensus", "min_consensus_windows": 2, "min_consensus_share": 0.67, "min_confidence": .55,
                       "window_seconds": .5, "max_observation_gap_seconds": .6},
    "camera_timeline": {"min_window_seconds": 0.25, "max_window_seconds": 1.0},
    "preview": {"enabled": False, "max_canaries": 4, "canary_seconds": 4.0,
                "output_width": 540, "output_height": 960, "max_repair_iterations": 1},
    "understanding": {"max_thumbnail_candidates": 80, "extract_frames": True,
                      "max_moments": 12,
                      "participant_min_visual_seconds": 8.0, "participant_min_observations": 12,
                      "participant_min_speech_seconds": 3.0, "participant_min_distinct_shots": 2,
                      "candidate_min_seconds": 8.0, "candidate_preferred_min_seconds": 30.0,
                      "candidate_preferred_max_seconds": 90.0, "candidate_soft_max_seconds": 120.0,
                      "candidate_hard_max_seconds": 180.0, "allow_commercial_candidates": False,
                      "commercial_penalty": .5, "ranking_weights": dict(DEFAULT_WEIGHTS)},
    "ocr": {"enabled": False, "languages": "por+eng",
            "tesseract_cmd": None, "max_frames": 80},
    "audio_events": {"enabled": False, "checkpoint": None,
                     "threshold": 0.50, "window_seconds": 10},
    "semantic_analysis": {"enabled": True, "backend": "heuristic",
                           "ollama_url": "http://127.0.0.1:11434",
                           "model": "qwen3:14b", "profile": "max",
                           "chunk_seconds": 180, "timeout_seconds": 600,
                           "max_chars": 24000, "keep_alive": "30m",
                           "global_review": True, "global_max_moments": 120,
                           "global_max_chars": 80000,
                           "num_ctx": None, "num_predict": None,
                           "temperature": None, "top_k": None, "top_p": None,
                           "repeat_penalty": None, "seed": None,
                           "max_calls_per_hour": 80, "fallback_warning_fraction": .1},
    "captions": {"max_words": 5, "max_chars": 38,
                 "max_seconds": 2.8, "max_gap_seconds": 0.45,
                 "uppercase_display": True},
}


def merge(base, extra, path=""):
    result = deepcopy(base)
    if not isinstance(extra, dict):
        raise ValueError("Configuração deve ser um objeto YAML.")
    for key, value in extra.items():
        if key not in base:
            raise ValueError(f"Opção desconhecida: {path}{key}")
        if isinstance(base[key], dict):
            result[key] = merge(base[key], value, f"{path}{key}.")
        else:
            result[key] = value
    return result


def load_config(path=None):
    cfg = deepcopy(DEFAULTS)
    if path:
        cfg = merge(cfg, yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {})
    validate(cfg)
    return cfg


def validate(cfg):
    resolve_config(cfg["camera_director"])
    # Generated by GitHub Copilot - Oct-05-2026
    import math
    if not isinstance(cfg["preflight"]["allow_self_repair"], bool):
        raise ValueError("preflight.allow_self_repair deve ser booleano")
    for key in ("network_timeout_seconds", "repair_timeout_seconds"):
        value = cfg["preflight"][key]
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or not 0 < value <= 3600:
            raise ValueError(f"preflight.{key} deve estar em (0, 3600]")
    # Generated by GitHub Copilot - Oct-05-2026
    for section,key in (('vision','tracklet_min_visual_seconds'),('vision','tracklet_min_observations'),
                        ('vision','identity_min_visual_seconds'),('vision','reid_candidate_limit'),
                        ('understanding','participant_min_visual_seconds'),('understanding','participant_min_observations'),
                        ('understanding','participant_min_speech_seconds'),('understanding','participant_min_distinct_shots'),
                        ('understanding','candidate_min_seconds'),('understanding','candidate_preferred_min_seconds'),
                        ('understanding','candidate_preferred_max_seconds'),('understanding','candidate_soft_max_seconds'),
                        ('understanding','candidate_hard_max_seconds'),('semantic_analysis','max_calls_per_hour'),
                        ('export','chunk_records'),('export','chunk_max_bytes')):
        value=cfg[section][key]
        if isinstance(value,bool) or not isinstance(value,(int,float)) or not math.isfinite(value) or value<=0:
            raise ValueError(f'{section}.{key} deve ser numero positivo finito')
    for section,key in (('export','legacy_full_analysis'),('understanding','allow_commercial_candidates'),
                        ('diarization','enabled'),('vision','enabled'),('vision','active_speaker'),('scenes','enabled'),
                        ('semantic_analysis','enabled'),('ocr','enabled'),('audio_events','enabled')):
        if not isinstance(cfg[section][key],bool):
            raise ValueError(f'{section}.{key} deve ser booleano')
    durations=[cfg['understanding'][key] for key in ('candidate_min_seconds','candidate_preferred_min_seconds',
                'candidate_preferred_max_seconds','candidate_soft_max_seconds','candidate_hard_max_seconds')]
    if durations!=sorted(durations) or durations[-1]>3600:
        raise ValueError('Duracoes de candidato devem ser crescentes e hard max <=3600')
    if not 0<=cfg['semantic_analysis']['fallback_warning_fraction']<=1:
        raise ValueError('semantic_analysis.fallback_warning_fraction fora de [0,1]')
    if not 0<=cfg['understanding']['commercial_penalty']<=1:
        raise ValueError('understanding.commercial_penalty fora de [0,1]')
    for key,weight in cfg['understanding']['ranking_weights'].items():
        if isinstance(weight,bool) or not isinstance(weight,(int,float)) or not math.isfinite(weight) or not 0<=weight<=1:
            raise ValueError('Peso editorial invalido: '+key)
    if sum(cfg['understanding']['ranking_weights'].values())<=0:
        raise ValueError('Ao menos um peso editorial deve ser positivo')
    if not 1<=cfg['export']['chunk_records']<=10000 or not 1024<=cfg['export']['chunk_max_bytes']<=8*1024**2:
        raise ValueError('Tamanho de chunk de exportacao invalido')
    if not isinstance(cfg["vision"]["adaptive_sampling"], bool):
        raise ValueError("vision.adaptive_sampling deve ser booleano")
    for k in ("window_seconds", "max_observation_gap_seconds"):
        v = cfg["active_speaker"][k]
        if isinstance(v, bool) or not isinstance(v, (int, float)) or not .1 <= v <= 2:
            raise ValueError(f"active_speaker.{k} inválido")
    for key in ("min_confidence", "min_consensus_share"):
        value = cfg["active_speaker"][key]
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not 0 <= value <= 1:
            raise ValueError(f"active_speaker.{key} inválido")
    if cfg["active_speaker"].get("backend") != "heuristic_consensus":
        raise ValueError("active_speaker.backend externo ainda requer adapter/benchmark local; use heuristic_consensus.")
    n = cfg["active_speaker"]["min_consensus_windows"]
    if isinstance(n, bool) or not isinstance(n, int) or n < 2:
        raise ValueError("min_consensus_windows deve ser inteiro >= 2")
    if cfg["device"] not in ("auto", "cpu", "cuda"):
        raise ValueError("device deve ser auto, cpu ou cuda. MPS não é backend CTranslate2.")
    for section, key in [("transcription", "chunk_seconds"), ("vision", "sample_fps"),
                         ("vision", "speech_sample_fps"), ("vision", "checkpoint_seconds"),
                         ("semantic_analysis", "chunk_seconds"),
                         ("captions", "max_words"), ("captions", "max_chars"),
                         ("captions", "max_seconds"),
                         ("person_motion", "smoothing_alpha"),
                         ("person_motion", "max_gap_seconds"),
                         ("camera_timeline", "min_window_seconds"),
                         ("camera_timeline", "max_window_seconds"),
                         ("preview", "max_canaries"), ("preview", "canary_seconds"),
                         ("preview", "output_width"), ("preview", "output_height")]:
        if not isinstance(cfg[section][key], (int, float)) or cfg[section][key] <= 0:
            raise ValueError(f"{section}.{key} precisa ser positivo.")
    t = cfg["transcription"]
    if not 0 <= t["overlap_seconds"] < t["chunk_seconds"] / 2:
        raise ValueError("overlap_seconds inválido.")
    if t["source_selection"] not in ("auto", "original", "speech_clean"):
        raise ValueError("source_selection inválido.")
    if cfg["audio"]["separation"] not in ("off", "demucs"):
        raise ValueError("audio.separation deve ser off ou demucs.")
    if cfg["semantic_analysis"]["backend"] not in ("heuristic", "ollama"):
        raise ValueError("semantic backend deve ser heuristic ou ollama.")
    if cfg["semantic_analysis"]["profile"] not in ("fast", "balanced", "max"):
        raise ValueError("semantic_analysis.profile deve ser fast, balanced ou max.")
    if cfg["semantic_analysis"]["global_max_moments"] <= 0:
        raise ValueError("semantic_analysis.global_max_moments precisa ser positivo.")
    if cfg["semantic_analysis"]["global_max_chars"] <= 0:
        raise ValueError("semantic_analysis.global_max_chars precisa ser positivo.")
    if cfg["vision"]["body_backend"] not in ("hog", "yolo"):
        raise ValueError("body_backend deve ser hog ou yolo.")
    if not 0 < cfg["person_motion"]["smoothing_alpha"] <= 1:
        raise ValueError("person_motion.smoothing_alpha deve estar em (0, 1].")
    if cfg["camera_timeline"]["min_window_seconds"] > cfg["camera_timeline"]["max_window_seconds"]:
        raise ValueError("camera_timeline min_window_seconds não pode exceder max_window_seconds.")
    if not 0 <= cfg["active_speaker"]["min_consensus_share"] <= 1:
        raise ValueError("active_speaker.min_consensus_share deve estar entre 0 e 1.")
    if not 0 <= t["low_confidence"] <= 1:
        raise ValueError("low_confidence deve estar entre 0 e 1.")
    if not isinstance(cfg["preview"]["enabled"], bool):
        raise ValueError("preview.enabled deve ser booleano")
    repairs = cfg["preview"]["max_repair_iterations"]
    if isinstance(repairs, bool) or not isinstance(repairs, int) or not 0 <= repairs <= 3:
        raise ValueError("preview.max_repair_iterations deve ser inteiro entre 0 e 3")


def asset_path(value):
    path = Path(value).expanduser()
    return path if path.is_absolute() else ROOT / path


def configure_local_mode(cfg):
    os.environ.setdefault("PYANNOTE_METRICS_ENABLED", "0")
    os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY", "1")
    os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")
    os.environ.setdefault("DO_NOT_TRACK", "1")
    if cfg["offline"]:
        os.environ["HF_HUB_OFFLINE"] = "1"
        os.environ["TRANSFORMERS_OFFLINE"] = "1"
