from copy import deepcopy
import gc
import os
import math
import numpy as np
import soundfile as sf
from .core import ok, Unavailable, read_json, overlap
from .config import asset_path
from .temporal import union_duration
from .model_cache import cached_pipeline_snapshot


def overlap_intervals(turns):
    events = []
    for i, turn in enumerate(turns):
        events.extend([(turn["start"], 1, i), (turn["end"], -1, i)])
    events.sort()
    active, previous, intervals = set(), None, []
    for time, delta, index in events:
        labels = sorted({turns[i]["speaker"] for i in active})
        if previous is not None and time > previous and len(labels) > 1:
            if intervals and intervals[-1]["end"] == previous and intervals[-1]["speakers"] == labels:
                intervals[-1]["end"] = time
            else:
                intervals.append({"start": previous, "end": time,
                                  "speakers": labels, "type": "speech_overlap",
                                  "inference": True, "confidence": None})
        if delta == 1:
            active.add(index)
        else:
            active.discard(index)
        previous = time
    return intervals


def diarization_capabilities(cfg):
    """Cheap diagnostics for GUI/startup without loading the heavy pipeline."""
    import importlib.util
    token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    model_path = asset_path(cfg.get("model", ""))
    cached = cached_pipeline_snapshot(cfg.get("model", ""))
    try:
        installed = importlib.util.find_spec("pyannote.audio") is not None
    except (ModuleNotFoundError, ValueError):
        installed = False
    return {
        "enabled": bool(cfg.get("enabled", True)),
        "hf_token_present": bool(token),
        "local_model_present": model_path.is_dir(),
        "hf_cached_model_present": cached is not None,
        "pyannote_installed": installed,
        "model": cfg.get("model"),
        "import_file": cfg.get("import_file"),
        "model_accessible": "requires_runtime_check" if cached or token or model_path.is_file() else None,
    }


class DiarizationEngine:
    def run(self, ctx, audio, metadata):
        cfg = ctx.config["diarization"]
        if not cfg["enabled"]:
            return ok({"turns": [], "overlaps": [], "speakers": []}, "skipped",
                      ["Diarização desativada; locutor desconhecido permanece null."])
        if cfg["import_file"]:
            data = read_json(asset_path(cfg["import_file"]))
            turns = data if isinstance(data, list) else data.get("turns", [])
            # Generated by GitHub Copilot - Oct-05-2026
            exclusive_turns = [] if isinstance(data, list) else data.get("exclusive_turns", [])
            method = "imported"
        else:
            from .media_runtime import bootstrap_ffmpeg_shared
            bootstrap_ffmpeg_shared(ctx.config.get('media_tools', {}).get('ffmpeg_shared_dir'))
            token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
            model_path = asset_path(cfg["model"])
            cached = cached_pipeline_snapshot(cfg["model"])
            if not token and cached is None and not model_path.is_file():
                raise Unavailable("Diarização precisa de HF_TOKEN e aceite de community-1 "
                                  "(ou modelo local já disponível). Não foi inventado um speaker.")
            try:
                import torch
                from pyannote.audio import Pipeline
            except ImportError:
                raise Unavailable("Instale requirements/diarization.txt para pyannote.")
            model = str(model_path) if model_path.is_dir() or model_path.is_file() else cfg["model"]
            # Generated by GitHub Copilot - Oct-05-2026
            pipeline = samples = output = annotation = exclusive = None
            try:
                pipeline = Pipeline.from_pretrained(model, token=token)
                if pipeline is None:
                    raise Unavailable("Community-1 nao carregou; verifique token e aceite do modelo.")
                device = "cuda" if ctx.config["device"] != "cpu" and torch.cuda.is_available() else "cpu"
                if ctx.config["device"] == "cuda" and device != "cuda":
                    raise Unavailable("CUDA solicitada para diarizacao, mas torch CUDA nao esta disponivel.")
                pipeline.to(torch.device(device))
                samples, rate = sf.read(audio["mono"], dtype="float32")
                args = {k: cfg[k] for k in ("num_speakers", "min_speakers", "max_speakers") if cfg[k] is not None}
                with torch.inference_mode():
                    output = pipeline({"waveform": torch.from_numpy(samples).unsqueeze(0), "sample_rate": rate}, **args)
                annotation = getattr(output, "speaker_diarization", output)
                exclusive = getattr(output, "exclusive_speaker_diarization", None)
                turns = [{"start": interval.start, "end": interval.end, "speaker": speaker, "confidence": None}
                         for interval, _, speaker in annotation.itertracks(yield_label=True)]
                exclusive_turns = ([{"start": interval.start, "end": interval.end, "speaker": speaker, "confidence": None}
                                    for interval, _, speaker in exclusive.itertracks(yield_label=True)] if exclusive is not None else [])
            finally:
                pipeline = samples = output = annotation = exclusive = None
                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
            method = "pyannote_community_1"
        duration = metadata["duration"]
        for t in turns + exclusive_turns:
            if not isinstance(t.get("speaker"), str) or not t["speaker"]:
                raise ValueError("Locutor inválido em diarização importada.")
            a, b = float(t["start"]), float(t["end"])
            if not math.isfinite(a+b) or not 0 <= a < b <= duration + 0.1:
                raise ValueError("Intervalo inválido em diarização.")
            t.update(start=a, end=min(b, duration), confidence=t.get("confidence"),
                     method=method, source=method, inference=True)
        turns.sort(key=lambda t: (t["start"], t["end"]))
        labels = {s: f"SPEAKER_{i:02}" for i, s in enumerate(dict.fromkeys(t["speaker"] for t in turns))}
        # Generated by GitHub Copilot - Oct-05-2026
        for t in turns + exclusive_turns:
            t["source_label"] = t["speaker"]
            if t["speaker"] not in labels:
                raise ValueError("Locutor exclusivo sem evidencia na diarizacao tradicional.")
            t["speaker"] = labels[t["speaker"]]
        exclusive_turns.sort(key=lambda turn: (turn["start"], turn["end"]))
        if any(right["start"] < left["end"] for left, right in zip(exclusive_turns, exclusive_turns[1:])):
            raise ValueError("Diarizacao exclusiva contem intervalos sobrepostos.")
        overlaps = overlap_intervals(turns)
        for t in turns:
            t["overlap"] = any(overlap(t["start"], t["end"], o["start"], o["end"]) > 0 for o in overlaps)
        speakers = [{"speaker_id": s, "name": None,
                     "speech_seconds": sum(t["end"]-t["start"] for t in turns if t["speaker"] == s),
                     "confidence": None, "method": method, "source": method} for s in labels.values()]
        return ok({"turns": turns, "exclusive_turns": exclusive_turns, "overlaps": overlaps, "speakers": speakers, "method": method,
                   "speaker_count": len(speakers), "capabilities": diarization_capabilities(cfg)},
                  notes=["IDs de locutores são agrupamentos acústicos. Confiança não fornecida "
                         "pelo modelo fica null; sobreposições foram preservadas."])


def align_speakers(transcript, diarization):
    data = deepcopy(transcript)
    # Generated by GitHub Copilot - Oct-05-2026
    exclusive = bool(diarization.get("exclusive_turns"))
    turns = sorted(diarization.get("exclusive_turns") or diarization.get("turns", []), key=lambda t: t["start"])
    overlaps = diarization.get("overlaps", [])
    pointer = 0
    for w in data["words"]:
        while pointer < len(turns) and turns[pointer]["end"] <= w["start"]:
            pointer += 1
        scores = {}
        for t in turns[pointer:]:
            if t["start"] >= w["end"]:
                break
            hit = overlap(w["start"], w["end"], t["start"], t["end"])
            if hit:
                scores[t["speaker"]] = scores.get(t["speaker"], 0) + hit
        order = sorted(scores, key=scores.get, reverse=True)
        w["speaker_candidates"] = order
        w["speech_overlap"] = any(overlap(w["start"], w["end"], t["start"], t["end"]) > 0 for t in overlaps)
        coverage = scores[order[0]] / max(w["end"]-w["start"], 1e-9) if order else 0
        ambiguous = len(order) > 1 and scores[order[1]] >= scores[order[0]] * 0.5
        w["speaker"] = order[0] if coverage >= 0.5 and not ambiguous else None
        w["speaker_assignment_method"] = ("exclusive_temporal_alignment" if exclusive else "maximum_temporal_overlap") if order else "unknown"
        w["speaker_overlap_fraction"] = min(1, coverage)
    # Split transcript at speaker changes without altering the recognized words.
    rows, current = [], []
    for w in data["words"]:
        if current and (w["speaker"] != current[-1]["speaker"] or
                        w["segment_id"] != current[-1]["original_segment_id"]):
            rows.append(current)
            current = []
        w["original_segment_id"] = w["segment_id"]
        current.append(w)
    if current:
        rows.append(current)
    from .transcription import word_text
    segments = []
    for i, group in enumerate(rows):
        sid = f"SEG_{i:05}"
        for w in group:
            w["segment_id"] = sid
        candidates = sorted({s for w in group for s in w.get("speaker_candidates", [])})
        segments.append({"segment_id": sid, "start": group[0]["start"], "end": group[-1]["end"],
                         "speaker": group[0]["speaker"], "speakers": candidates,
                         "text": word_text(group), "speech_overlap": any(w["speech_overlap"] for w in group),
                         "word_ids": [w.get("word_id") for w in group]})
    # Retain text-only imported segments; never generate fake word timestamps for them.
    if not data["words"]:
        segments = data["segments"]
        for s in segments:
            s["speaker"] = None
    data["segments"] = segments
    # Generated by GitHub Copilot - Oct-05-2026
    diarization["alignment_metrics"] = {
        "diarization_available": bool(diarization.get("turns")), "speaker_count": len(diarization.get("speakers", [])),
        "words_with_speaker_fraction": sum(bool(word.get("speaker")) for word in data["words"]) / len(data["words"]) if data["words"] else None,
        "segments_with_speaker_fraction": sum(bool(segment.get("speaker")) for segment in segments) / len(segments) if segments else None,
        "exclusive_alignment_coverage": sum(word["end"] - word["start"] for word in data["words"] if exclusive and word.get("speaker")) /
                                        max(sum(word["end"] - word["start"] for word in data["words"]), 1e-9) if exclusive else None,
        "overlap_seconds": sum(row["end"] - row["start"] for row in overlaps),
        "unmapped_speech_seconds": sum(word["end"] - word["start"] for word in data["words"] if not word.get("speaker")),
        "speech_seconds_by_speaker": {speaker["speaker_id"]: speaker.get("speech_seconds") for speaker in diarization.get("speakers", [])}}
    speech=union_duration(diarization.get('turns',[]))
    speech_words=union_duration(data['words'])
    overlap_seconds=union_duration(overlaps)
    diarization['alignment_metrics'].update(diarization_speech_seconds=speech,
        diarization_speech_coverage=min(1.0,speech/speech_words) if speech_words else None,
        overlap_seconds=overlap_seconds,overlap_fraction=overlap_seconds/speech if speech else None,
        overlap_fraction_denominator='union_diarized_speech_seconds')
    return data
