"""Pipeline and artifact-only resume integration; no ASR/decoder/model imports."""
from pathlib import Path
from bisect import bisect_right
from .core import Context, digest, read_json, write_json, setup_logging, output_lock, logging_session
from .camera_director import build_camera_director
from .global_camera_planner import build_global_camera_plan

PLANNER_CODE = ['global_camera_planner.py', 'director_config.py', 'camera_geometry.py', 'temporal.py', 'director_integration.py']
DIRECTOR_CODE = ['camera_director.py', 'director_config.py', 'camera_motion.py',
                 'camera_geometry.py', 'temporal.py', 'director_integration.py']


def run_planner_stage(ctx, metadata, vision, shots, camera_timeline, active, semantic, understanding):
    params = {'config': ctx.config['camera_director'], 'schema': '4.0',
              'inputs': digest({'metadata': {k: metadata.get(k) for k in ('duration','width','height','rotation')},
                                'camera_timeline': camera_timeline, 'shots': shots,
                                'active': active, 'vision': {'frames': vision.get('frames', []),
                                'observations': vision.get('observations', [])}})}
    scoped = Context(ctx.video, ctx.output, ctx.config, ctx.signature, ctx.logger, ctx.force)
    scoped.states.update(ctx.states)
    result = scoped.step('18b_global_camera_planner', params,
        lambda: build_global_camera_plan(metadata, vision, shots, camera_timeline,
            ctx.config['camera_director'], active, semantic, understanding),
        code_files=PLANNER_CODE, output_version='4.0', requires=['12_camera_timeline'])
    ctx.states.update({k:v for k,v in scoped.states.items() if k == '18b_global_camera_planner'})
    ctx.issues.extend(i for i in scoped.issues if i.get('stage') == '18b_global_camera_planner')
    return result


def run_director_stage(ctx, metadata, vision, shots, active, motion, semantic, understanding, camera_plan=None):
    vision = {'frames': vision.get('frames', []), 'observations': vision.get('observations', [])}
    params = {'config': ctx.config['camera_director'], 'schema': '3.0',
              'inputs': digest({'metadata': {k: metadata.get(k) for k in ('duration', 'width', 'height', 'rotation')},
                               'vision': vision, 'shots': shots, 'active': active, 'motion': motion,
                               'qas': semantic.get('questions_answers', []),
                               'arcs': understanding.get('story_arcs', []),
                               'moments': understanding.get('main_moments', []),
                               'camera_plan': (camera_plan or {}).get('selected_global_path', [])})}
    # Only actual inputs determine this cheap stage. Does not alter upstream checkpoint keys.
    scoped = Context(ctx.video, ctx.output, ctx.config, ctx.signature, ctx.logger, ctx.force)
    scoped.states.update(ctx.states)
    result = scoped.step('19_camera_director', params,
        lambda: build_camera_director(metadata, vision, shots, active, motion,
            ctx.config['camera_director'], semantic.get('questions_answers', []),
            understanding.get('story_arcs', []), understanding.get('main_moments', []), camera_plan),
        code_files=DIRECTOR_CODE, output_version='3.0',
        requires=['12_camera_timeline', '18b_global_camera_planner'] if ctx.config['camera_director'].get('enabled',True) else [])
    ctx.states.update(scoped.states)
    ctx.issues.extend(scoped.issues)
    metrics = result.get('metrics', {})
    ctx.logger.info('Camera Director: %s; intervalos=%s; trocas/min=%.2f; suprimidas=%s; cobertura=%.1f%%',
        scoped.states['19_camera_director']['status'], metrics.get('director_intervals', 0),
        metrics.get('director_switches_per_minute', 0), metrics.get('switches_suppressed', 0),
        metrics.get('camera_director_coverage', 0)*100)
    return result


def attach_director(analysis, director):
    rows = director.get('timeline', [])
    # Generated by GitHub Copilot - Oct-05-2026
    from .analysis_quality import camera_quality_metrics
    metrics = {**director.get('metrics', {}), **camera_quality_metrics(
        rows, analysis.get('metadata', {}).get('duration', 0), director.get('metrics', {}).get('switches_suppressed'))}
    analysis['camera_director_schema_version'] = '3.0'
    analysis['camera_director_timeline'] = rows
    analysis['camera_director_debug'] = director.get('debug')
    analysis['camera_director_config'] = director.get('config')
    old_metrics = ((analysis.get('video_understanding') or {}).get('camera_director') or {}).get('metrics', {})
    for key in old_metrics:
        analysis.setdefault('analysis_quality', {}).pop(key, None)
    analysis.setdefault('analysis_quality', {}).update(metrics)
    if analysis.get('video_understanding') is None:
        analysis['video_understanding'] = {}
    analysis['video_understanding']['camera_director'] = {
        'schema_version': '3.0', 'metrics': metrics, 'timeline_file': 'camera_director_timeline.json',
        'debug_file': 'camera_director_debug.json' if director.get('debug') is not None else None,
        'recommendations_only': True}
    starts = [r['start'] for r in rows]
    for window in analysis.get('master_timeline', []):
        i = max(0, bisect_right(starts, window['start'])-1)
        matches = []
        while i < len(rows) and rows[i]['start'] < window['end']:
            row = rows[i]
            if row['end'] > window['start']:
                matches.append({'director_id': row['director_id'],
                                'start': max(window['start'], row['start']),
                                'end': min(window['end'], row['end'])})
            i += 1
        window['camera_director_intervals'] = matches
    return analysis


def resume_director(folder, cfg, force=False):
    """Recompute from saved evidence. Never resolves/opens the original video."""
    folder = Path(folder).expanduser().resolve()
    source = folder/'analysis.json'
    if not source.is_file():
        raise ValueError('Director-only requer analysis.json completo. A amostra enxuta não contém esse arquivo.')
    # Generated by GitHub Copilot - Oct-05-2026
    from .compact_artifacts import load_analysis_artifacts
    analysis = load_analysis_artifacts(folder)
    metadata = analysis['metadata']
    signature = metadata.get('sha256') or digest(metadata)
    logger = setup_logging(folder)
    ctx = Context(Path(metadata.get('filename', 'unavailable.mp4')), folder, cfg, signature, logger, force)
    with logging_session(logger), output_lock(folder):
        vision = {'people': analysis.get('people', []), 'observations': analysis.get('people_observations', []),
                  'frames': (analysis.get('video_analysis') or {}).get('frame_samples', [])}
        plan = run_planner_stage(ctx, metadata, vision, analysis.get('shots', []),
            analysis.get('camera_timeline', []), analysis.get('active_speaker', []), analysis, analysis)
        analysis['camera_plan'] = plan
        result = run_director_stage(ctx, metadata, vision, analysis.get('shots', []),
            analysis.get('active_speaker', []), analysis.get('person_motion', []), analysis, analysis, plan)
        attach_director(analysis, result)
        analysis.setdefault('stage_status', {}).update(ctx.states)
        analysis['issues'] = [i for i in analysis.get('issues', []) if i.get('stage') != '19_camera_director']+ctx.issues
        analysis['analysis_status'] = 'partial' if any(s.get('status') in ('partial', 'unavailable', 'failed', 'blocked', 'cancelled')
            for s in analysis['stage_status'].values()) else 'complete'
        from .reports import ReportEngine
        captions_path = folder/'caption_segments.json'
        captions = read_json(captions_path) if captions_path.is_file() else []
        ReportEngine().run(ctx, analysis, captions)
    return folder, analysis
