"""Grounded editorial normalization and deterministic candidate utility."""

from collections import Counter
import heapq
import math
import re
import unicodedata

# Generated by GitHub Copilot - Oct-05-2026
CONTEXT_REQUIREMENTS = ("none", "helpful", "required", "unresolved")
CONTENT_TYPES = ("editorial_content", "editorial_product_discussion", "self_promotion", "event_promotion",
                 "commercial_promotion", "advertisement", "sponsor_read", "merchandising",
                 "housekeeping", "intro_outro", "station_identification", "uncertain")
COMMERCIAL_TYPES = {"advertisement", "sponsor_read", "merchandising", "commercial_promotion", "event_promotion", "self_promotion"}
GENERIC_TERMS = set("nao ele ela era deixa temos tem tinha foi sao esta estamos voces voce gente entao assim "
                    "aqui agora muito mais menos tudo coisa coisas fazer faz fazeram fazeria falar fala falando "
                    "dizer disse vou vamos vai pode poderia porque quando como onde qual quem deles delas "
                    "nossa nosso esse essa isso isto daquele aquela mesmo tambem ainda acho queria quero "
                    "sobre entre pelo pela para cada sera estava estou teve seja hoje depois antes anos ano "
                    "sempre nunca alguem algo bem sim sou meu minha nome meu me e o a os as de do da dos das "
                    "em um uma uns umas com por ao aos sem que se ou no na nos nas eu tu nos ne ai so ha".split())
DEFAULT_WEIGHTS = {"hook": .15, "standalone_clarity": .15, "clean_opening": .1, "clean_ending": .1,
                   "story_completeness": .1, "qa_completeness": .1, "information_density": .1,
                   "visual_viability": .05, "audio_quality": .05, "duration_suitability": .1}


# Generated by GitHub Copilot - Oct-05-2026
def fold_text(text):
    """Normalize PT-BR lexical comparisons without changing literal transcript."""
    return "".join(character for character in unicodedata.normalize("NFD", str(text).casefold())
                   if unicodedata.category(character) != "Mn")


# Generated by GitHub Copilot - Oct-05-2026
def terms(text):
    """Remove generic discourse terms from topic/entity/editorial comparisons."""
    return {term for term in re.findall(r"\b\w+\b", fold_text(text)) if len(term) >= 3 and term not in GENERIC_TERMS}


# Generated by GitHub Copilot - Oct-05-2026
def finite_score(value):
    """Keep missing evidence null and reject booleans/non-finite subjective scores."""
    return float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value) and 0 <= value <= 1 else None


# Generated by GitHub Copilot - Oct-05-2026
def normalize_context(row):
    """Project legacy free-form context into a strict enum without inventing certainty."""
    explicit = row.get("context_requirement")
    legacy = row.get("context_required")
    value = fold_text(legacy).strip() if legacy is not None else ""
    if explicit in CONTEXT_REQUIREMENTS:
        requirement = explicit
    elif legacy is False or value in {"none", "nao", "nenhum", "nenhuma", "sem contexto", "nao precisa", "nao necessario"}:
        requirement = "none"
    elif legacy is True or value in {"required", "necessario", "obrigatorio"}:
        requirement = "required"
    elif value in {"helpful", "util", "ajuda"}:
        requirement = "helpful"
    elif value and value not in {"null", "none", "unresolved"}:
        requirement = "required"
    else:
        requirement = "unresolved"
    reason = row.get("context_reason")
    if reason is None and isinstance(legacy, str) and value not in {"", "null", *CONTEXT_REQUIREMENTS, "nao", "nenhum", "nenhuma"}:
        reason = legacy
    result = {"context_requirement": requirement,
              "context_reason": reason[:1500] if isinstance(reason, str) and reason.strip() else None,
              "context_required": None if requirement == "unresolved" else requirement,
              "legacy_context_required": legacy}
    for key in ("context_seconds_before", "context_seconds_after"):
        value = row.get(key)
        result[key] = float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value) and 0 <= value <= 3600 else (0.0 if requirement == "none" else None)
    return result


# Generated by GitHub Copilot - Oct-05-2026
def require_pt_br(texts):
    """Reject clearly English metadata; lexical detection is not language accuracy."""
    vocabulary = re.findall(r"\b[a-z]+\b", fold_text(" ".join(str(text or "") for text in texts)))
    english = {"the", "this", "that", "with", "which", "because", "about", "are", "was", "were", "and", "their", "they", "would", "from"}
    portuguese = {"que", "com", "porque", "sobre", "uma", "para", "das", "dos", "fala", "historia", "trecho", "momento", "contexto", "nao"}
    english_hits = [word for word in vocabulary if word in english]
    portuguese_hits = [word for word in vocabulary if word in portuguese]
    if len(set(english_hits)) >= 3 and len(english_hits) > 2 * len(portuguese_hits):
        raise ValueError("language_mismatch: metadata deve ser PT-BR; detector lexical nao calibrado.")
    return True


# Generated by GitHub Copilot - Oct-05-2026
def classify_content(text, evidence_segment_ids=None, visual_evidence=None):
    """Ground multicue sales decisions in source spans, not brand/keyword alone."""
    literal = str(text or "")
    normalized = fold_text(literal)
    offsets = [index for index, character in enumerate(literal) for _ in fold_text(character)]
    signals = {
        "price": r"\br\s*\$\s*\d[\d.,]*|\b\d[\d.,]*\s*(?:reais|mil)\b|\b\d{1,5},\d{2}\b|\bpreco\b.{0,35}\d|\bpor apenas\b|\bde (?:cento|cinquenta|sessenta|setenta|oitenta|noventa)\b.{0,90}\bpor (?:cento|cinquenta|sessenta|setenta|oitenta|noventa)\b",
        "installment": r"\b\d{1,3}\s*(?:x\b|de\s+\d[\d.,]*|vezes\b)|\b(?:em|ate)\s+(?:\d{1,3}|dez|doze)\s*vezes\b|\bparcelas?\b|\btaxa zero\b|\bsem entrada e sem juros\b",
        "discount": r"\b(descontos?|cupom|promocao|promocoes|ofertas?|parcelamento|metade do preco)\b",
        "store": r"\b(lojas?|estoque|vendas? abertas?|pronta entrega|campanha de vendas)\b",
        "product": r"\b(produtos?|suplementos?|magnesio|vitaminas?|colageno|sofa(?:-?cama)?|poltronas?|cadeiras?|moveis|mobiliario|decoracoes?|couro|carros?|veiculos?|capsulas?|medicamentos?|cursos?|livros?)\b",
        "sales_cta": r"\b(compre|adquira|aproveit[ae]|garant[ae]|(?:ja |voce ja )?garantiu|peca agora|ligue|acesse a loja|venha conferir|corre la|correria agora|pode ir na loja|quer patrocinar)\b",
        "recommendation": r"\b(use|tome|experimente)\s+(?:(?:o|a|os|as|este|esse|essa|esta)\s+)?\w+",
        "contact": r"\b(telefone|whatsapp|entre em contato)\b|\b[\w.+-]+@[\w.-]+\.[a-z]{2,}\b",
        "domain": r"\b(?:https?://|www\.)?[a-z0-9-]+(?:\.[a-z0-9-]+)*\.(?:com|net|org|com\.br|br)\b",
        "urgency": r"\b(imperdivel|so hoje|ultima oportunidade|ultimos dias|vai esgotar|vendas abertas|pronta entrega|super valorizacao)\b",
        "payment": r"\b(pix|sem juros|sem entrada)\b",
        "health_claim": r"\bdesinflam\w*|\balivi\w*.{0,45}\bdor\b|\b(?:combate|elimina).{0,30}\b(?:dores?|inflamacao)\b",
        "benefit_claim": r"\b(melhor produto|resultado garantido|super valorizacao|qualidade superior)\b",
        "event": r"\b(ingressos?|bilheteria|shows?|eventos?|tickets?)\b",
        "sponsor": r"\b(oferecimento|oferecido por|conteudo patrocinado|patrocinado por|nosso patrocinador|patrocinador deste programa)\b",
        "sponsorship_mention": r"\b(patrocinador|patrocinio|patrocinar)\b",
    }
    spans = []
    for signal, pattern in signals.items():
        for match in list(re.finditer(pattern, normalized))[:3]:
            prefix = normalized[max(0, match.start() - 24):match.start()]
            if signal in {"sales_cta", "recommendation", "health_claim", "discount", "sponsor", "urgency"} and re.search(r"\b(?:nao|nunca|sem)\s+(?:\w+\s+){0,2}$", prefix):
                continue
            start, end = offsets[match.start()], offsets[match.end() - 1] + 1
            while end < len(literal) and unicodedata.category(literal[end]) == "Mn":
                end += 1
            spans.append({"signal": signal, "start_char": start, "end_char": end,
                          "text": literal[start:end], "segment_ids": list(evidence_segment_ids or [])})
    # OCR is observed text, with its own offsets/provenance; never fabricate a logo cue.
    for row in visual_evidence or []:
        if not isinstance(row, dict) or not row.get('text') or row.get('source') not in {'ocr', 'visual_text'}:
            continue
        result = classify_content(row['text'], [])
        for span in result['evidence_spans']:
            spans.append({**span, 'modality': 'visual_text', 'source_text': row['text'],
                          'observed_start': row.get('start'), 'observed_end': row.get('end'), 'source': row['source']})
    reasons = list(dict.fromkeys(span["signal"] for span in spans))
    cues = set(reasons)
    sales = "sales_cta" in cues
    offer = {"installment", "urgency"} <= cues or {"price", "installment", "store"} <= cues
    health_promotion = {"recommendation", "product", "health_claim"} <= cues
    strong = offer or health_promotion or {"store", "discount", "payment"} <= cues or (sales and bool(cues & {"price", "discount", "domain", "store", "contact", "event"}))
    if "sponsor" in cues:
        content_type, score = "sponsor_read", .85
    elif strong and "event" in cues:
        content_type, score = "event_promotion", min(.96, .7 + .04 * len(cues))
    elif strong and re.search(r"\b(meu livro|meu curso|meu show)\b", normalized):
        content_type, score = "self_promotion", .8
    elif health_promotion:
        content_type, score = "commercial_promotion", .85
    elif strong:
        content_type, score = "advertisement", min(.96, .65 + .05 * len(cues))
    elif re.search(r"\b(inscreva|se inscreve|compartilhe|deixe o like|segue o canal)\b", normalized):
        content_type, score = "housekeeping", 0.0
    elif re.search(r"\b(bem vindos|boa noite pessoal|ate o proximo programa|encerramos)\b", normalized):
        content_type, score = "intro_outro", 0.0
    elif sales or "recommendation" in cues and cues & {"price", "domain", "health_claim"}:
        content_type, score = "uncertain", .35
    elif cues & {"product", "price", "sponsorship_mention"}:
        content_type, score = "editorial_product_discussion", 0.0
    elif not literal.strip():
        content_type, score = "uncertain", None
    else:
        content_type, score = "editorial_content", 0.0
    eligibility = "excluded" if content_type in COMMERCIAL_TYPES else "review" if content_type == "uncertain" else "eligible"
    return {"content_type": content_type, "commercial_score": score, "reasons": reasons,
            "signals": reasons, "evidence_spans": spans, "eligibility": eligibility,
            "evidence_segment_ids": list(evidence_segment_ids or []),
            "classifier_method": "pt_br_grounded_commercial_gate_v3", "needs_review": eligibility != "eligible",
            "confidence_is_calibrated": False}


# Generated by GitHub Copilot - Oct-05-2026
def normalize_moment(moment):
    """Normalize control fields and preserve actual model/source provenance."""
    row = {**moment, **normalize_context(moment)}
    row.setdefault('reason', 'Justificativa nao fornecida pelo snapshot; revisar evidencia literal.')
    row.setdefault('categories', [])
    row.setdefault('complete_sentence', (row.get('text') or '').rstrip().endswith(('.', '?', '!')))
    if row.get("standalone_class") not in {"excellent", "good", "needs_context", "poor"}:
        row["standalone_class"] = "needs_context"
    row["needs_review"] = row.get("needs_review") if isinstance(row.get("needs_review"), bool) else True
    row["metadata_locale"] = "pt-BR"
    row["confidence_method"] = "subjective_llm_judgment" if row.get("method") == "ollama" else "lexical_heuristic"
    row["commercial_classification"] = classify_content(row.get("text", ""), row.get("evidence_segment_ids", []))
    row.update({key: row["commercial_classification"][key] for key in ("content_type", "commercial_score")})
    return row


# Generated by GitHub Copilot - Oct-05-2026
def topic_hierarchy(topics, segments):
    """Merge adjacent equivalent topics and keep the primary theme evidence-qualified."""
    by_id = {segment["segment_id"]: segment for segment in segments}
    merged = []
    merge_count = 0
    merge_decisions = []
    for original in topics:
        topic = {**original, **normalize_context(original), "metadata_locale": "pt-BR"}
        topic["merged_topic_ids"] = [topic["topic_id"]]
        ids = topic.get("evidence_segment_ids", [])
        literal = " ".join(by_id[segment_id].get("text", "") for segment_id in ids if segment_id in by_id)
        topic.update({key: value for key, value in classify_content(literal, ids).items() if key in ("content_type", "commercial_score")})
        previous = merged[-1] if merged else None
        lexical = terms(topic.get("topic", ""))
        before = terms(previous.get("topic", "")) if previous else set()
        label_similarity = len(lexical & before) / len(lexical | before) if lexical and before else 0.
        current_terms = terms(literal)
        previous_literal = " ".join(by_id[segment_id].get('text', '') for segment_id in previous.get('evidence_segment_ids', []) if segment_id in by_id) if previous else ''
        previous_terms = terms(previous_literal)
        shared_fraction = len(current_terms & previous_terms) / max(1, min(len(current_terms), len(previous_terms)))
        speaker_continuity = bool(set(topic.get('speakers', [])) & set(previous.get('speakers', []))) if previous else False
        equivalent = label_similarity >= .8 or (label_similarity >= .5 and shared_fraction >= .5 and speaker_continuity)
        if previous:
            merge_decisions.append({'previous_topic_id': previous['topic_id'], 'topic_id': topic['topic_id'],
                                    'decision': 'merge' if equivalent and topic['start'] - previous['end'] <= 3 and previous['content_type'] == topic['content_type'] else 'keep_separate',
                                    'label_similarity': label_similarity, 'shared_grounded_term_fraction': shared_fraction,
                                    'speaker_continuity': speaker_continuity, 'method': 'lexical_and_grounded_continuity_not_embedding_similarity'})
        if previous and equivalent and topic["start"] - previous["end"] <= 3 and previous["content_type"] == topic["content_type"]:
            previous["end"] = topic["end"]
            previous["evidence_segment_ids"] = list(dict.fromkeys(previous["evidence_segment_ids"] + ids))
            previous["merged_topic_ids"].extend(topic["merged_topic_ids"])
            previous['speakers'] = sorted(set(previous.get('speakers', [])) | set(topic.get('speakers', [])))
            merge_count += 1
        else:
            merged.append(topic)
    sections=[]
    for topic in merged:
        topic['parent_episode_id'] = 'EPISODE'
        previous=sections[-1] if sections else None
        lexical=terms(topic.get('topic',''))
        preceding=terms(previous['title']) if previous else set()
        related=bool(lexical and preceding and len(lexical & preceding)/len(lexical | preceding)>=.35)
        if (previous and related and previous['content_type']==topic['content_type'] and
                topic['start']-previous['end']<=3 and topic['end']-previous['start']<=900):
            previous['end']=topic['end']
            previous['topic_ids'].append(topic['topic_id'])
            previous['evidence_segment_ids']=list(dict.fromkeys(previous['evidence_segment_ids']+topic.get('evidence_segment_ids',[])))
        else:
            sections.append({
                'section_id': f'SECTION_{len(sections):04}', 'start': topic['start'], 'end': topic['end'],
                'parent_episode_id': 'EPISODE', 'level': 'major_section',
                'title': topic['topic'], 'topic_ids': [topic['topic_id']],
                'evidence_segment_ids': list(topic.get('evidence_segment_ids', [])),
                'content_type': topic['content_type'], 'method': 'adjacent_topic_lexical_relatedness_grouping',
                'needs_review': True,
            })
        topic['parent_section_id'] = sections[-1]['section_id']
    qualified = [topic for topic in merged if topic.get("method") == "ollama" and topic["content_type"] not in COMMERCIAL_TYPES
                 and terms(topic.get("topic", "")) and topic.get("evidence_segment_ids")]
    qualified.sort(key=lambda topic: (-(topic["end"] - topic["start"]), topic["topic_id"]))
    primary = {key: qualified[0].get(key) for key in ("topic_id", "topic", "summary", "evidence_segment_ids", "method")} if qualified else None
    covered = {segment_id for topic in merged for segment_id in topic.get("evidence_segment_ids", [])}
    count = len(merged)
    quality = {"topic_count": count, "merged_topic_count": merge_count,
               "major_section_count": len(sections), "topic_merge_decisions": merge_decisions,
               "heuristic_topic_fraction": sum(topic.get("method") != "ollama" for topic in merged) / count if count else None,
               "LLM_topic_fraction": sum(topic.get("method") == "ollama" for topic in merged) / count if count else None,
               "uncovered_segment_fraction": len(set(by_id) - covered) / len(by_id) if by_id else None,
               "commercial_topic_fraction": sum(topic["content_type"] in COMMERCIAL_TYPES for topic in merged) / count if count else None,
               "primary_theme_status": "grounded_model_topic_requires_review" if primary else "unresolved_no_qualified_theme",
               "duplicate_topic_similarity_warnings": []}
    return merged, sections, primary, [topic["topic_id"] for topic in qualified[1:]], quality


# Generated by GitHub Copilot - Oct-05-2026
def duration_contract(cfg=None):
    cfg = cfg or {}
    return {"target_min_seconds": cfg.get("target_min_seconds", cfg.get("candidate_preferred_min_seconds", 30)),
            "target_max_seconds": cfg.get("target_max_seconds", cfg.get("candidate_preferred_max_seconds", 90)),
            "hard_min_seconds": cfg.get("hard_min_seconds", cfg.get("candidate_min_seconds", 8)),
            "hard_max_seconds": cfg.get("hard_max_seconds", cfg.get("candidate_hard_max_seconds", 180)),
            "allow_story_exception": cfg.get("allow_story_exception", True)}


_STORY_COMPONENT_KEYS = ("setup", "development", "payoff")


def _story_component_ids(story, key):
    """Read a real arc component or a legacy duration-proof list of source IDs.

    A duration exception is saved as ``{setup: [IDs], ...}`` by assess_duration.
    A regular story arc uses ``{setup: {segment_ids: [IDs]}, ...}`` instead.
    Both encode the *same observed segment evidence*. Reject all other shapes;
    never synthesize a missing component, ID, or timestamp.
    """
    if not isinstance(story, dict):
        return []
    value = story.get(key)
    if isinstance(value, dict):
        value = value.get("segment_ids")
    if not isinstance(value, (list, tuple)) or not value:
        return []
    if not all(isinstance(item, str) and item.strip() for item in value):
        return []
    if len(set(value)) != len(value):
        return []
    return list(value)


def _complete_story(story, segment_ids):
    if not isinstance(story, dict) or story.get("kind") not in (None, "complete_story"):
        return False
    if story.get("kind") is None and story.get("completeness") != "supported_setup_development_payoff":
        return False
    if not isinstance(segment_ids, (list, tuple)) or not segment_ids:
        return False
    # Validate against the selected contiguous source sequence, not arbitrary
    # semantic IDs. Unknown components or overlapping/reversed arcs cannot earn
    # an exception just because the clip happens to be long.
    source_indices = {segment_id: index for index, segment_id in enumerate(segment_ids)
                      if isinstance(segment_id, str)}
    indices = []
    for key in _STORY_COMPONENT_KEYS:
        component = _story_component_ids(story, key)
        if not component or any(segment_id not in source_indices for segment_id in component):
            return False
        indices.append([source_indices[segment_id] for segment_id in component])
    return max(indices[0]) < min(indices[1]) and max(indices[1]) < min(indices[2])


def assess_duration(start, end, cfg=None, story=None, segment_ids=None):
    contract = duration_contract(cfg)
    duration = end - start
    hard = contract["hard_min_seconds"] <= duration <= contract["hard_max_seconds"]
    target = contract["target_min_seconds"] <= duration <= contract["target_max_seconds"]
    exception = bool(hard and duration > contract["target_max_seconds"] and contract["allow_story_exception"] and
                     _complete_story(story, segment_ids or []))
    # Public duration-proof contract is a mapping of source-ID lists. The
    # ranking stage must be able to consume exactly this representation.
    proof = {key: _story_component_ids(story, key) for key in _STORY_COMPONENT_KEYS} if exception else None
    return {"duration_contract": contract, "duration_exception": exception,
            "duration_exception_reason": "grounded_complete_story_requires_contiguous_setup_and_payoff" if exception else None,
            "duration_exception_evidence": proof,
            "duration_in_target_range": target, "duration_within_hard_range": hard,
            "duration_default_eligible": target or exception,
            "duration_suitability_score": 1.0 if target else .75 if exception else .35 if hard else 0.0,
            "duration_requires_review": not target,
            "duration_soft_max_exceeded": duration > contract["target_max_seconds"]}


def opening_quality(segment, previous=None):
    text = (segment.get("text") or "").strip()
    reasons = []
    if not text:
        reasons.append("missing_text")
    if re.match(r"^(ele|ela|eles|elas|isso|aquilo|esse|essa|mas|porque|entao|ai|e)\b", fold_text(text)):
        reasons.append("missing_antecedent_or_continuation")
    if re.match(r"^(bom[,.]|assim[,.]|quer dizer|tipo assim|tudo bem|tudo bacana|tudo certo)\b", fold_text(text)):
        reasons.append("generic_preamble")
    if previous and previous.get("speaker") == segment.get("speaker") and segment["start"] - previous["end"] < 1 and not (previous.get("text") or "").rstrip().endswith((".", "?", "!")):
        reasons.append("mid_sentence")
    if segment.get("timestamp_anomaly_count") or segment.get("timestamp_suspect"):
        reasons.append("suspect_timestamp")
    return {"clean": not reasons, "reasons": reasons, "method": "grounded_sentence_and_context_boundary"}


def ending_quality(segment):
    text = (segment.get("text") or "").rstrip()
    complete = text.endswith((".", "?", "!")) and not text.endswith(("...", "\u2026"))
    if re.search(r"\b(?:e|mas|porque|que|entao)[.!?]*$", fold_text(text)):
        complete = False
    return {"clean": complete, "reasons": [] if complete else ["incomplete_sentence_or_handoff"],
            "method": "observed_sentence_ending_not_semantic_payoff_probability"}


def optimize_boundaries(moment, segments, cfg=None, story=None, qa_pairs=None):
    """Choose source sentence/story boundaries; never fabricate times to meet duration."""
    cfg = cfg or {}
    by_id = {segment["segment_id"]: index for index, segment in enumerate(segments)}
    indices = [by_id[segment_id] for segment_id in moment.get("evidence_segment_ids", []) if segment_id in by_id]
    if not indices:
        indices = [index for index, segment in enumerate(segments)
                   if segment["start"] < moment["end"] and moment["start"] < segment["end"]]
    if not indices:
        return {"ideal_start": moment["start"], "ideal_end": moment["end"],
                "alternate_starts": [], "alternate_ends": [], "boundary_reason": "unresolved_no_segment_evidence",
                "context_added_before": 0.0, "context_added_after": 0.0, "duration_suitability_score": None}
    first, last = min(indices), max(indices)
    core_start, core_end = segments[first]["start"], segments[last]["end"]
    opening = fold_text(segments[first].get("text", "")).strip()
    context = normalize_context(moment)["context_requirement"]
    reference = bool(re.match(r"^(ele|ela|eles|elas|isso|aquilo|esse|essa|mas|porque|entao|ai)\b", opening))
    if first and (reference or context in {"required", "helpful"}) and core_start - segments[first - 1]["start"] <= 30:
        first -= 1
    story_supported = _complete_story(story, [segment["segment_id"] for segment in segments])
    if story_supported and story["start"] <= core_start and core_end <= story["end"] and story["end"] - story["start"] <= duration_contract(cfg)["hard_max_seconds"]:
        story_indices = [index for index, segment in enumerate(segments) if story["start"] <= segment["start"] and segment["end"] <= story["end"]]
        if story_indices:
            first, last = min(first, min(story_indices)), max(last, max(story_indices))
    # A reply is not standalone if the source question is missing. Join only
    # a grounded, contiguous, temporally relevant Q&A span within hard limits.
    qa_expansion = []
    core_duration = max(core_end - core_start, 1e-6)
    for pair in qa_pairs or []:
        if not pair.get('question_answer_complete') or pair.get('answer_start') is None:
            continue
        answer_start, answer_end = pair['answer_start'], pair['answer_end']
        relevant = max(0.0, min(core_end, answer_end) - max(core_start, answer_start)) / core_duration
        if relevant < .25 or abs(pair['question_start'] - core_start) > 40:
            continue
        pair_ids = pair.get('evidence_segment_ids') or []
        if not pair_ids or any(sid not in by_id for sid in pair_ids):
            continue
        q_indices = [by_id[sid] for sid in pair_ids]
        a, b = min(first, min(q_indices)), max(last, max(q_indices))
        if segments[b]['end'] - segments[a]['start'] > duration_contract(cfg)['hard_max_seconds']:
            continue
        first, last = a, b
        qa_expansion.append(pair.get('question_id'))
    if last + 1 < len(segments) and not segments[last].get("text", "").rstrip().endswith((".", "?", "!")):
        if segments[last + 1]["end"] - core_end <= 30:
            last += 1
    start, end = segments[first]["start"], segments[last]["end"]
    duration = end - start
    selected_ids = [segment["segment_id"] for segment in segments[first:last + 1]]
    opening_assessment = opening_quality(segments[first], segments[first - 1] if first else None)
    ending_assessment = ending_quality(segments[last])
    assessment = assess_duration(start, end, cfg, story, selected_ids)
    return {"ideal_start": start, "ideal_end": end,
            "alternate_starts": sorted({core_start, start}), "alternate_ends": sorted({core_end, end}),
            "boundary_reason": "grounded_sentence_reference_story_and_qa_completion",
            "qa_boundary_expansion_ids": qa_expansion,
            "context_added_before": max(0.0, core_start - start), "context_added_after": max(0.0, end - core_end),
            "clean_opening": opening_assessment["clean"], "opening_assessment": opening_assessment,
            "clean_ending": ending_assessment["clean"], "ending_assessment": ending_assessment,
            **assessment, "boundary_segment_ids": selected_ids}


# Generated by GitHub Copilot - Oct-05-2026
def rank_candidate(candidate, cfg=None):
    """Expose explicit weighted editorial utility and penalties, never viral probability."""
    cfg = cfg or {}
    literal = candidate.get("text") or (candidate.get("core_moment") or {}).get("text")
    classification = classify_content(literal, candidate.get("evidence_segment_ids", []), candidate.get('commercial_visual_evidence')) if literal is not None else candidate.get("commercial_classification")
    if classification:
        candidate = {**candidate, "commercial_classification": classification,
                     "content_type": classification["content_type"], "commercial_score": classification["commercial_score"]}
    start, end = candidate.get("ideal_start", 0), candidate.get("ideal_end", 0)
    exception_proof = candidate.get("duration_exception_evidence")
    # Legacy proof has ID lists, whereas a story arc has component objects.
    # Revalidate the recorded proof as source IDs, without assuming .get() on
    # a list and without promoting malformed/partial evidence to a story.
    story = ({"kind": "complete_story", "completeness": "supported_setup_development_payoff",
              **{key: {"segment_ids": _story_component_ids(exception_proof, key)}
                 for key in _STORY_COMPONENT_KEYS}}
             if candidate.get("duration_exception") and isinstance(exception_proof, dict) else None)
    duration = assess_duration(start, end, cfg, story, candidate.get("boundary_segment_ids") or candidate.get("evidence_segment_ids", []))
    candidate = {**candidate, **duration,
                 "duration_exception_proof_rejected": bool(candidate.get("duration_exception") and
                                                           not duration["duration_exception"])}
    components = {"hook": finite_score(candidate.get("hook_score")),
                  "standalone_clarity": finite_score(candidate.get("standalone_score")),
                  "clean_opening": float(candidate["clean_opening"]) if isinstance(candidate.get("clean_opening"), bool) else None,
                  "clean_ending": float(candidate["clean_ending"]) if isinstance(candidate.get("clean_ending"), bool) else None,
                  "story_completeness": finite_score(candidate.get("story_completeness")),
                  "qa_completeness": 1.0 if candidate.get("question_answer_complete") else None,
                  "information_density": finite_score(candidate.get("information_score")),
                  "curiosity": finite_score(candidate.get("curiosity_score")), "emotion": finite_score(candidate.get("emotion_score")),
                  "surprise": finite_score(candidate.get("surprise_score")), "controversy": finite_score(candidate.get("conflict_score")),
                  "humor": finite_score(candidate.get("humor_score")), "visual_viability": finite_score(candidate.get("visual_score")),
                  "audio_quality": finite_score(candidate.get("audio_quality")),
                  "duration_suitability": finite_score(candidate.get("duration_suitability_score"))}
    weights = cfg.get("ranking_weights", DEFAULT_WEIGHTS)
    observed_weight = sum(weight for key, weight in weights.items() if components.get(key) is not None)
    available_weight = sum(weights.values())
    evidence_coverage = observed_weight / available_weight if available_weight else None
    required_components = {'hook', 'standalone_clarity', 'clean_opening', 'clean_ending', 'duration_suitability'}
    missing_required = sorted(key for key in required_components if components.get(key) is None)
    uncertainty_penalty = .08 * (1 - evidence_coverage) if evidence_coverage is not None else .08
    raw = sum(components[key] * weight for key, weight in weights.items() if components.get(key) is not None) / observed_weight if observed_weight else None
    commercial = bool(classification and classification.get("eligibility") == "excluded") or candidate.get("content_type") in COMMERCIAL_TYPES
    commercial = commercial and not cfg.get("allow_commercial_candidates", False)
    context = candidate.get("context_requirement", "unresolved")
    penalties = {"commercial": cfg.get("commercial_penalty", .5) if commercial else 0.0,
                 "missing_evidence_uncertainty": uncertainty_penalty,
                 "incomplete_ending": .15 if candidate.get('clean_ending') is False else 0.0,
                 "context_dependency": .1 if context == "required" else 0.0,
                 "unresolved_evidence": .05 if context == "unresolved" else 0.0,
                 "duplicate": 0.0,
                 "editorial_incomplete": .25 if candidate.get("editorial_blockers") else 0.0}
    final = max(0.0, min(1.0, raw - sum(penalties.values()))) if raw is not None else None
    return {**candidate, "editorial_score_raw": raw, "score_components": components, "penalties": penalties,
            "editorial_quality_score": round(raw, 3) if raw is not None else None,
            "evidence_coverage": round(evidence_coverage, 3) if evidence_coverage is not None else None,
            "ranking_confidence": 'low' if missing_required or (evidence_coverage or 0) < .55 else 'medium' if evidence_coverage < .85 else 'high',
            "ranking_uncertainty": {'missing_required_components': missing_required,
                                    'missing_optional_components': sorted(key for key, value in components.items() if value is None and key not in required_components),
                                    'story_not_required_for_monologue': True, 'qa_not_required_for_monologue': True,
                                    'score_is_probability': False},
            "score_weights": weights, "observed_weight": observed_weight,
            "editorial_score_final": round(final, 3) if final is not None else None, "editorial_score": round(final, 3) if final is not None else None, "ranking_version": "4.9.3",
            "score_method": "explicit_weighted_observed_utility_not_probability",
            "default_shortlist_eligible": not commercial and (not classification or classification.get("eligibility") not in {"review", "excluded"}) and
                duration["duration_default_eligible"] and candidate.get("clean_opening") is True and candidate.get("clean_ending") is True and
                not missing_required and not candidate.get("editorial_blockers")}


# Generated by GitHub Copilot - Oct-05-2026
def _equivalent(left, right):
    """Require temporal and editorial equivalence for non-exact deduplication."""
    left_start, left_end = left["ideal_start"], left["ideal_end"]
    right_start, right_end = right["ideal_start"], right["ideal_end"]
    intersection = max(0.0, min(left_end, right_end) - max(left_start, right_start))
    if not intersection:
        return False, False
    exact = abs(left_start-right_start)<=1e-6 and abs(left_end-right_end)<=1e-6
    if exact:
        return True, True
    union = max(left_end, right_end) - min(left_start, right_start)
    shorter = min(left_end - left_start, right_end - right_start)
    overlap = intersection / shorter if shorter > 0 else 0.0
    left_ids, right_ids = set(left.get("evidence_segment_ids", [])), set(right.get("evidence_segment_ids", []))
    evidence_share = len(left_ids & right_ids) / max(1, min(len(left_ids), len(right_ids)))
    left_terms = terms(left.get("core_moment", {}).get("text") or left.get("text", ""))
    right_terms = terms(right.get("core_moment", {}).get("text") or right.get("text", ""))
    lexical_share = len(left_terms & right_terms) / max(1, len(left_terms | right_terms))
    return (intersection / union >= .8 or overlap >= .8) and (evidence_share >= .8 or lexical_share >= .85), False


# Generated by GitHub Copilot - Oct-05-2026
def deduplicate_candidates(candidates):
    """Sweep overlapping intervals, preserving stronger primaries and all alternates."""
    active, expirations, primaries = {}, [], []
    exact_count = overlap_count = 0
    for candidate in sorted(candidates, key=lambda row: (row["ideal_start"], row["ideal_end"], row["moment_id"])):
        start = candidate["ideal_start"]
        while expirations and expirations[0][0] <= start:
            end, handle = heapq.heappop(expirations)
            if handle in active and active[handle]["ideal_end"] == end:
                del active[handle]
        matches = []
        for handle, previous in active.items():
            equivalent, exact = _equivalent(candidate, previous)
            if equivalent:
                matches.append((handle, previous, exact))
        if not matches:
            handle = len(primaries)
            row = {**candidate, "alternates": list(candidate.get("alternates", []))}
            active[handle] = row
            primaries.append(row)
            heapq.heappush(expirations, (row["ideal_end"], handle))
            continue
        handle, previous, exact = max(matches, key=lambda match: (match[1].get("editorial_score_final") or 0, -match[0]))
        stronger, alternate = (candidate, previous) if (candidate.get("editorial_score_final") or 0) > (previous.get("editorial_score_final") or 0) else (previous, candidate)
        alternates = list(previous.get("alternates", [])) + [{key: value for key, value in alternate.items() if key != "alternates"}]
        row = {**stronger, "alternates": alternates,
               "deduplicated_moment_ids": list(dict.fromkeys(previous.get("deduplicated_moment_ids", [previous["moment_id"]]) + [candidate["moment_id"]]))}
        primaries[handle] = active[handle] = row
        heapq.heappush(expirations, (row["ideal_end"], handle))
        exact_count += int(exact)
        overlap_count += int(not exact)
    primaries.sort(key=lambda row: (-(row.get("editorial_score_final") or 0), row["ideal_start"], row["moment_id"]))
    return primaries, {"candidates_before_dedup": len(candidates), "candidates_after_dedup": len(primaries),
                       "exact_duplicate_count": exact_count, "high_overlap_merge_count": overlap_count,
                       "alternate_count": sum(len(row.get("alternates", [])) for row in primaries),
                       "dedup_method": "overlap_sweep_temporal_and_editorial_nms"}
