"""Global editorial camera planning above the stateful Camera Director.

The planner is intentionally deterministic and geometry-driven. It selects a coarse
editorial path over a larger horizon; CameraDirector still owns hysteresis, safety,
smoothing and physical camera motion. No LLM is used for per-frame geometry.
"""
from collections import Counter
import math
from .core import ok, digest
from .director_config import resolve_config
from .camera_geometry import geometry
from .temporal import VisualIndex, number

PRESERVE = {'broll', 'b_roll', 'screen', 'screen_capture', 'screen_content',
            'logo', 'title_card', 'empty', 'black'}


def _state_key(candidate):
    return (candidate['state'], candidate.get('focus_person'), tuple(candidate.get('people') or ()))


def _profile_weights(profile):
    # Transparent, reversible preferences. Safety is never encoded here: unsafe
    # candidates are removed before scoring.
    return {
        'podcast': {'source': .20, 'stay': .34, 'switch': .34, 'split': .32, 'single': .12},
        'dynamic_short': {'source': .10, 'stay': .16, 'switch': .18, 'split': .24, 'single': .24},
        'documentary': {'source': .30, 'stay': .24, 'switch': .26, 'split': .34, 'single': .14},
        'conservative': {'source': .42, 'stay': .40, 'switch': .44, 'split': .46, 'single': .08},
        'natural': {'source': .22, 'stay': .28, 'switch': .28, 'split': .34, 'single': .16},
    }[profile]


def _transition_cost(previous, current, weights):
    if previous is None:
        return 0.0
    if _state_key(previous) == _state_key(current):
        return -weights['stay']  # negative cost == explicit stay-put reward
    cost = weights['switch']
    if previous['state'] != current['state']:
        cost += .08
    if previous.get('focus_person') != current.get('focus_person'):
        cost += .08
    if current['state'] == 'SPLIT':
        cost += weights['split']
    return cost


def _candidate(state, layout, focus, people, components, evidence, reason):
    return {
        'state': state, 'layout': layout, 'focus_person': focus,
        'people': list(people or []), 'components': components,
        'utility': round(sum(components.values()), 6),
        'evidence': list(evidence), 'reason_code': reason,
    }


# Generated by GitHub Copilot - Oct-05-2026
def _micro_interruptions(timeline, cfg):
    """Recognize A-B-A runs only within one source shot, without inventing a return."""
    runs = []
    for index, row in enumerate(timeline):
        signature = row.get('active_person'), row.get('shot_id')
        if runs and runs[-1]['signature'] == signature and abs(runs[-1]['end'] - row['start']) < 1e-6:
            runs[-1]['end'] = row['end']
            runs[-1]['indices'].append(index)
        else:
            runs.append({'signature': signature, 'start': row['start'], 'end': row['end'], 'indices': [index]})
    holds = {}
    for index in range(1, len(runs) - 1):
        previous, interruption, following = runs[index - 1:index + 2]
        person, shot = previous['signature']
        if (person and previous['signature'] == following['signature'] and shot == interruption['signature'][1]
                and interruption['signature'][0] != person
                and interruption['end'] - interruption['start'] <= cfg['short_interruption_seconds'] + 1e-7):
            for window in interruption['indices']:
                holds[window] = {'person': person, 'duration': interruption['end'] - interruption['start']}
    return holds


def build_global_camera_plan(metadata, vision, shots, camera_timeline, cfg=None,
                             active_speaker=None, semantic=None, understanding=None):
    cfg = resolve_config(cfg)
    profile = cfg['profile']
    weights = _profile_weights(profile)
    duration = number(metadata.get('duration'))
    if duration <= 0 or not camera_timeline:
        return ok({'schema_version': '4.0', 'selected_global_path': [], 'candidate_states': [],
                   'rejected_candidates': [], 'metrics': {}, 'profile': profile},
                  'unavailable', ['Global Planner sem camera_timeline/duração válida.'])

    visual = VisualIndex(vision)
    mapped_people = {row['person_id'] for row in active_speaker or [] if row.get('person_id') and
                     ('active_person' not in row or row['active_person'] == row['person_id']) and
                     row.get('active_speaker_state') not in {'UNCERTAIN', 'OFFSCREEN', 'PROBABLE'} and
                     number(row.get('confidence', row.get('mapping_confidence'))) >= cfg['enter_confidence']}
    shot_map = {s.get('shot_id'): s for s in (shots or [])}
    windows, rejected = [], []
    # Generated by GitHub Copilot - Oct-05-2026
    interruption_holds = _micro_interruptions(camera_timeline, cfg)
    for index, row in enumerate(camera_timeline):
        start, end = number(row.get('start')), number(row.get('end'))
        if end <= start:
            continue
        mid = (start + end) / 2
        shot = shot_map.get(row.get('shot_id')) or {}
        lo, hi = number(shot.get('start'), start), number(shot.get('end'), end)
        frame, observations = visual.near(mid, lo, hi, cfg['max_observation_gap_seconds'])
        preserve = row.get('shot_type') in PRESERVE or shot.get('shot_type') in PRESERVE
        candidates = []
        source_components = {
            'source_composition': weights['source'],
            'continuity': .18,
            'no_resolution_loss': .18,
            'fallback_safety': .22 if not frame else .08,
        }
        candidates.append(_candidate('SOURCE_FULL_FRAME', 'full_frame', None, [], source_components,
                                     ['source_frame'], 'SOURCE_FRAME_SELECTED'))
        if preserve or not frame:
            windows.append({'start': start, 'end': end, 'shot_id': row.get('shot_id'),
                            'candidates': candidates, 'preserve_source': True})
            continue

        active = row.get('active_person')
        confidence = number(row.get('active_person_confidence'))
        hold = interruption_holds.get(index)
        if hold and hold['person'] in observations:
            hold_geometry = geometry([observations[hold['person']]], metadata, cfg)
            if hold_geometry.get('safe'):
                candidates.append(_candidate('SINGLE_PERSON_MEDIUM_CLOSE', 'single_person', hold['person'], [hold['person']],
                    {'micro_interruption_continuity': .44, 'observed_return_evidence': .24, 'crop_safety': .22, 'visual_quality': .08},
                    ['same_source_shot', 'observed_A_B_A_run', 'contemporary_presence', 'safe_geometry'],
                    'MICRO_INTERRUPTION_HOLD'))
        if active and active in observations and confidence >= cfg['enter_confidence']:
            geo = geometry([observations[active]], metadata, cfg)
            if geo.get('safe'):
                comp = {'speaker_relevance': .42 + .20 * confidence, 'crop_safety': .22,
                        'visual_quality': .08, 'single_person_preference': weights['single']}
                candidates.append(_candidate('SINGLE_PERSON_MEDIUM_CLOSE', 'single_person', active, [active], comp,
                                             ['active_speaker', 'sampled_frame', 'safe_geometry'], 'SWITCH_ACCEPTED'))
            else:
                rejected.append({'interval': [start, end], 'state': 'SINGLE_PERSON_MEDIUM_CLOSE',
                                 'person_id': active, 'reason': 'unsafe_crop'})

        safe_people = []
        for pid, obs in sorted(observations.items()):
            geo = geometry([obs], metadata, cfg)
            if geo.get('safe') and pid in mapped_people:
                safe_people.append(pid)
        if len(safe_people) >= 2:
            # Pick two strongest observed subjects deterministically by effective face/body area.
            pair = sorted(safe_people, key=lambda p: (
                number((observations[p].get('face_bbox') or observations[p].get('bbox') or {}).get('width')) *
                number((observations[p].get('face_bbox') or observations[p].get('bbox') or {}).get('height')), p), reverse=True)[:2]
            pair = tuple(sorted(pair))
            pair_geo = geometry([observations[p] for p in pair], metadata, cfg)
            conversation = bool(row.get('speech_overlap')) or row.get('vertical_crop', {}).get('recommended_layout') in ('two_person', 'split_candidate')
            if pair_geo.get('safe') and conversation:
                comp = {'conversation_grammar': .34 if conversation else .18, 'crop_safety': .24,
                        'continuity': .14, 'source_context': .10}
                candidates.append(_candidate('TWO_SHOT', 'two_shot', None, pair, comp,
                                             ['simultaneous_presence', 'safe_union_geometry'], 'TWO_SHOT_SELECTED_QUICK_EXCHANGE' if conversation else 'TWO_SHOT_SELECTED'))
            elif cfg['enable_split'] and conversation:
                comp = {'conversation_grammar': .32, 'independent_crop_safety': .22,
                        'split_cost': -weights['split'], 'continuity': .08}
                candidates.append(_candidate('SPLIT', 'split_candidate', None, pair, comp,
                                             ['simultaneous_presence', 'independent_safe_crops'], 'SPLIT_SELECTED'))
            elif conversation:
                rejected.append({'interval': [start, end], 'state': 'SPLIT', 'people': list(pair),
                                 'reason': 'unsafe_split_or_union_geometry'})

        windows.append({'start': start, 'end': end, 'shot_id': row.get('shot_id'),
                        'candidates': candidates, 'preserve_source': False})

    if not windows:
        return ok({'schema_version': '4.0', 'selected_global_path': [], 'candidate_states': [],
                   'rejected_candidates': rejected, 'metrics': {}, 'profile': profile},
                  'unavailable', ['Global Planner sem janelas válidas.'])

    # Dynamic programming / Viterbi-like bounded search. Candidate set is deliberately
    # small per window, so this remains O(n*k²) for long videos with tiny k.
    back = []
    scores = {}
    for i, window in enumerate(windows):
        current_scores, current_back = {}, {}
        for ci, candidate in enumerate(window['candidates']):
            key = _state_key(candidate)
            best_score, best_prev = -math.inf, None
            if i == 0:
                best_score = candidate['utility']
            else:
                for pi, previous in enumerate(windows[i-1]['candidates']):
                    pkey = _state_key(previous)
                    if pkey not in scores:
                        continue
                    transition = _transition_cost(previous, candidate, weights)
                    value = scores[pkey] + candidate['utility'] - transition
                    # deterministic tie-break by lexicographic state key
                    if value > best_score + 1e-12 or (abs(value-best_score) <= 1e-12 and (best_prev is None or str(pkey) < str(best_prev))):
                        best_score, best_prev = value, pkey
            if key not in current_scores or best_score > current_scores[key]:
                current_scores[key] = best_score
                current_back[key] = best_prev
        scores = current_scores
        back.append(current_back)

    final_key = max(scores, key=lambda key: (scores[key], str(key)))
    path_keys = [final_key]
    for i in range(len(windows)-1, 0, -1):
        path_keys.append(back[i][path_keys[-1]])
    path_keys.reverse()

    selected = []
    switches = 0
    state_transitions = 0
    previous_key = None
    candidate_dump = []
    for window, key in zip(windows, path_keys):
        chosen = next(c for c in window['candidates'] if _state_key(c) == key)
        if previous_key is not None and key != previous_key and window.get('shot_id') == selected[-1].get('shot_id'):
            state_transitions += 1
            previous_targets = (previous_key[1], previous_key[2])
            current_targets = (key[1], key[2])
            switches += int(previous_targets != current_targets)
        transition_cost = _transition_cost(
            next((c for c in windows[max(0, len(selected)-1)]['candidates'] if _state_key(c) == previous_key), None) if previous_key else None,
            chosen, weights) if selected else 0.0
        selected.append({
            'planner_id': f'PLAN_{len(selected):06}', 'start': window['start'], 'end': window['end'],
            'shot_id': window.get('shot_id'), 'state': chosen['state'], 'layout': chosen['layout'],
            'focus_person': chosen.get('focus_person'), 'people': chosen.get('people', []),
            'utility': chosen['utility'], 'objective_components': dict(chosen['components']),
            'transition_cost': round(transition_cost, 6), 'reason_code': chosen['reason_code'],
            'evidence': chosen['evidence'], 'uncertainty': 'sampled_visual_evidence',
        })
        candidate_dump.append({'start': window['start'], 'end': window['end'],
                               'states': window['candidates']})
        previous_key = key

    # Compact identical adjacent plan states within the same source shot.
    compact = []
    for row in selected:
        signature = (row['shot_id'], row['state'], row['layout'], row['focus_person'], tuple(row['people']))
        if compact and compact[-1]['_signature'] == signature:
            compact[-1]['end'] = row['end']
            compact[-1]['objective_components']['accumulated_windows'] = compact[-1]['objective_components'].get('accumulated_windows', 1) + 1
        else:
            compact.append({**row, '_signature': signature})
    for row in compact:
        row.pop('_signature', None)

    plan_id = 'CAMERA_PLAN_' + digest({'video': metadata.get('sha256'), 'profile': profile,
                                      'path': [(r['start'], r['end'], r['state'], r['focus_person']) for r in compact]})[:12]
    metrics = {
        'planner_windows': len(windows), 'planner_segments': len(compact),
        'expected_switches': switches, 'expected_switches_per_minute': switches*60/duration if duration else 0.0,
        'state_transition_count': state_transitions, 'switch_count_method': 'changes_of_resolved_editorial_targets_not_uncertain_state_labels',
        'source_frame_fraction': sum(r['end']-r['start'] for r in compact if r['state']=='SOURCE_FULL_FRAME')/duration,
        'split_fraction': sum(r['end']-r['start'] for r in compact if r['state']=='SPLIT')/duration,
        'two_shot_fraction': sum(r['end']-r['start'] for r in compact if r['state']=='TWO_SHOT')/duration,
        'single_person_fraction': sum(r['end']-r['start'] for r in compact if r['state'].startswith('SINGLE_PERSON'))/duration,
        'rejected_candidates': len(rejected),
        'micro_interruption_windows': len(interruption_holds),
        'micro_interruption_hold_count': sum(row['reason_code'] == 'MICRO_INTERRUPTION_HOLD' for row in selected),
    }
    return ok({
        'schema_version': '4.0', 'plan_id': plan_id, 'profile': profile,
        'target_aspect': [cfg['output_width'], cfg['output_height']],
        'source_reference': metadata.get('sha256') or metadata.get('filename'),
        'candidate_states': candidate_dump, 'selected_global_path': compact,
        'rejected_candidates': rejected, 'hard_constraints': [
            'temporal_integrity', 'source_preserve', 'contemporary_visual_evidence',
            'crop_safety', 'simultaneous_identity_compatibility', 'resolution_limits'],
        'transition_costs': {'switch_base': weights['switch'], 'stay_put_reward': weights['stay'],
                             'split_extra': weights['split']},
        'metrics': metrics, 'planner_version': '4.0.0',
    }, 'ok' if compact else 'partial', [
        'Global Planner usa otimização determinística; Camera Director continua responsável por hard safety, hold e movimento.'])
