"""Windows NVIDIA runtime helpers for CTranslate2/faster-whisper.

The NVIDIA pip packages install their DLLs inside the virtual environment.
Windows does not automatically search those directories, so we register them
before importing CTranslate2.
"""
from __future__ import annotations

import os
from pathlib import Path
import site
import sys
from typing import Dict, List
from .core import scrub

_DLL_HANDLES = []
_DLL_DIRECTORIES = set()


def _site_packages() -> List[Path]:
    roots = []
    try:
        roots.extend(Path(p) for p in site.getsitepackages())
    except Exception:
        pass
    roots.append(Path(sys.prefix) / "Lib" / "site-packages")
    out = []
    seen = set()
    for p in roots:
        try:
            p = p.resolve()
        except Exception:
            continue
        if p not in seen and p.is_dir():
            seen.add(p)
            out.append(p)
    return out


def configure_windows_nvidia_runtime() -> Dict[str, object]:
    """Expose CUDA/cuBLAS/cuDNN DLL folders installed by NVIDIA pip wheels."""
    info: Dict[str, object] = {"platform": sys.platform, "dll_dirs": [], "dlls": []}
    if os.name != "nt":
        return info

    candidates = []
    for root in _site_packages():
        nvidia = root / "nvidia"
        for rel in (
            Path("cuda_runtime") / "bin",
            Path("cublas") / "bin",
            Path("cudnn") / "bin",
            Path("nvjitlink") / "bin",
        ):
            p = nvidia / rel
            if p.is_dir():
                candidates.append(p)

    unique = []
    seen = set()
    for p in candidates:
        key = str(p).lower()
        if key not in seen:
            seen.add(key)
            unique.append(p)

    # Put NVIDIA folders first in PATH for subprocesses and LoadLibrary.
    if unique:
        current = os.environ.get("PATH", "")
        existing={entry.casefold() for entry in current.split(os.pathsep)}
        additions=[str(path) for path in unique if str(path).casefold() not in existing]
        if additions:
            os.environ["PATH"] = os.pathsep.join(additions) + os.pathsep + current

    if hasattr(os, "add_dll_directory"):
        for p in unique:
            if str(p).casefold() in _DLL_DIRECTORIES:
                continue
            try:
                _DLL_HANDLES.append(os.add_dll_directory(str(p)))
                _DLL_DIRECTORIES.add(str(p).casefold())
            except OSError:
                pass

    dlls = []
    wanted = ("cudart64", "cublas64", "cublaslt64", "cudnn64")
    for p in unique:
        try:
            for f in p.glob("*.dll"):
                if f.name.lower().startswith(wanted):
                    dlls.append(f.name)
        except OSError:
            pass

    info["dll_dirs"] = [str(p) for p in unique]
    info["dlls"] = sorted(set(dlls))
    return info


# Generated by GitHub Copilot - Oct-05-2026
def cuda_library_status():
    """Load required NVIDIA DLLs without inference; report actual loader failures."""
    if os.name!='nt':
        return {'checked':False,'status':'not_applicable','libraries':{}}
    import ctypes
    libraries={}
    for name in ('cublas64_12.dll','cudnn64_9.dll','cudart64_12.dll'):
        try:
            ctypes.WinDLL(name)
            libraries[name]={'loaded':True}
        except OSError:
            libraries[name]={'loaded':False}
    return {'checked':True,'status':'available' if all(item['loaded'] for item in libraries.values()) else 'missing',
            'libraries':libraries,'inference_executed':False}


def ctranslate2_cuda_info() -> Dict[str, object]:
    runtime = configure_windows_nvidia_runtime()
    result: Dict[str, object] = {"runtime": runtime, "device_count": None, "supported_compute_types": [],"import_succeeds":False}
    result['dll_status']=cuda_library_status()
    try:
        import ctranslate2
        result['import_succeeds']=True
        result["device_count"] = ctranslate2.get_cuda_device_count()
        try:
            result["supported_compute_types"] = sorted(ctranslate2.get_supported_compute_types("cuda"))
        except Exception as exc:
            result["compute_types_error"] = scrub(f"{type(exc).__name__}: {exc}")
    except Exception as exc:
        result["error"] = scrub(f"{type(exc).__name__}: {exc}")
    return result
