from pathlib import Path
from urllib.parse import urlsplit, parse_qs
import json
import math
import re
import shutil
from .core import run_command, file_hash, read_json, write_json, ok, Unavailable


def youtube_id(source):
    u = urlsplit(source)
    host = (u.hostname or "").lower()
    if u.scheme not in ("http", "https") or u.username or u.password:
        raise ValueError("Use um link HTTP/HTTPS de vídeo do YouTube.")
    if host in ("youtu.be", "www.youtu.be"):
        value = u.path.strip("/").split("/")[0]
    elif host in ("youtube.com", "www.youtube.com", "m.youtube.com", "music.youtube.com"):
        value = parse_qs(u.query).get("v", [""])[0]
        if not value and u.path.startswith(("/shorts/", "/live/", "/embed/")):
            value = u.path.split("/")[2]
    else:
        raise ValueError("URL precisa ser de um vídeo do YouTube.")
    if not re.fullmatch(r"[A-Za-z0-9_-]{11}", value):
        raise ValueError("Não foi encontrado um ID de vídeo válido. Playlists não são entrada.")
    return value


def resolve_input(source, cfg, root):
    if not source.startswith(("http://", "https://")):
        video = Path(source).expanduser().resolve()
        if not video.is_file():
            raise FileNotFoundError(f"Vídeo não encontrado: {video}")
        return video, {"type": "local", "filename": video.name}
    if cfg["offline"]:
        raise ValueError("Modo offline: selecione um arquivo local.")
    vid = youtube_id(source)
    directory = Path(root) / "input" / "youtube" / vid
    directory.mkdir(parents=True, exist_ok=True)
    record = directory / "download.json"
    height = cfg["download"]["max_height"]
    if record.exists():
        # Generated by GitHub Copilot - Oct-05-2026
        try:
            previous = read_json(record)
        except (ValueError,OSError):
            previous={}
        filename=previous.get('filename')
        if filename is not None and (not isinstance(filename,str) or Path(filename).name!=filename or
                '\\' in filename or '/' in filename or ':' in filename or '..' in filename):
            raise ValueError('Cache de download referencia caminho inseguro fora da pasta do video.')
        path = directory / (filename or '__missing_cache_file__')
        if path.is_symlink() or path.resolve().parent!=directory.resolve():
            raise ValueError('Cache de download nao pode seguir links para fora da pasta do video.')
        if path.is_file() and previous.get("max_height") == height:
            if previous.get("sha256") == file_hash(path):
                return path.resolve(), previous["source"]
    try:
        import yt_dlp
    except ImportError:
        raise Unavailable("Instale yt-dlp[default] para URLs do YouTube.")
    options = {
        "format": f"bv*[height<={height}]+ba/b[height<={height}]",
        "outtmpl": str(directory / "%(id)s.%(ext)s"),
        "merge_output_format": "mp4", "noplaylist": True,
        "restrictfilenames": True, "retries": 3,
        "continuedl": True, "overwrites": False,
        "socket_timeout":30,
    }
    if cfg["download"]["cookies_file"]:
        options["cookiefile"] = str(Path(cfg["download"]["cookies_file"]).expanduser())
    runtimes = {name: {} for name in ("deno", "node") if shutil.which(name)}
    if runtimes:
        options["js_runtimes"] = runtimes
    with yt_dlp.YoutubeDL(options) as ydl:
        info = ydl.extract_info(f"https://www.youtube.com/watch?v={vid}", download=True)
        candidates = [directory / f"{vid}.mp4",
                      Path(ydl.prepare_filename(info))]
        candidates.extend(directory.glob(f"{vid}.*"))
        video = next((p for p in candidates if p.is_file()
                      and p.suffix.lower() in (".mp4", ".mkv", ".webm", ".mov")), None)
        if video is None:
            raise RuntimeError("Download terminou sem um vídeo utilizável.")
    metadata = {"type": "youtube", "url": f"https://www.youtube.com/watch?v={vid}",
                "id": vid, "title": info.get("title"), "channel": info.get("channel"),
                "upload_date": info.get("upload_date"), "filename": video.name}
    write_json(record, {"filename": video.name, "max_height": height,
                        "sha256": file_hash(video), "source": metadata})
    return video.resolve(), metadata


def inspect(video):
    for tool in ("ffmpeg", "ffprobe"):
        if not shutil.which(tool):
            raise Unavailable(f"{tool} não encontrado no PATH.")
    out, _ = run_command(["ffprobe", "-v", "error", "-show_streams",
                          "-show_format", "-of", "json", video])
    data = json.loads(out)
    v = next((s for s in data["streams"] if s["codec_type"] == "video"), None)
    a = next((s for s in data["streams"] if s["codec_type"] == "audio"), None)
    if not v or not a:
        raise ValueError("O arquivo deve conter vídeo e áudio.")
    duration = float(data["format"].get("duration") or v.get("duration") or 0)
    if duration <= 0 or not math.isfinite(duration):
        raise ValueError("Duração inválida.")
    rate = v.get("avg_frame_rate", "0/1").split("/")
    fps = float(rate[0]) / max(1, float(rate[1]))
    raw_rate = v.get("r_frame_rate", "0/1").split("/")
    raw_fps = float(raw_rate[0]) / max(1, float(raw_rate[1]))
    vfr_likely = bool(fps and raw_fps and abs(fps-raw_fps) > max(.01, fps*.001))
    width, height = v["width"], v["height"]
    rotation = int(next((s.get("rotation", 0) for s in v.get("side_data_list", [])
                         if "rotation" in s), v.get("tags", {}).get("rotate", 0)))
    notes = []
    if rotation % 180:
        notes.append("Vídeo com rotação: OpenCV deverá aplicar orientação automaticamente; verifique as miniaturas antes de usar as caixas.")
    if vfr_likely:
        notes.append("Container sugere VFR: timestamps do decoder/container têm prioridade sobre frame_index/FPS nominal.")
    return ok({"filename": Path(video).name, "duration": duration, "fps": fps,
               "width": width, "height": height, "rotation": rotation,
               "orientation": "landscape" if width > height else "portrait" if height > width else "square",
               "audio_sample_rate": int(a["sample_rate"]), "audio_channels": a.get("channels"),
               "container_start_time": float(data["format"].get("start_time", 0) or 0),
               "audio_start_time": float(a.get("start_time", 0) or 0),
               "video_start_time": float(v.get("start_time", 0) or 0),
               "audio_video_start_offset": float(a.get("start_time",0) or 0)-float(v.get("start_time",0) or 0),
               "video_time_base": v.get("time_base"), "audio_time_base": a.get("time_base"),
               "video_start_pts": v.get("start_pts"), "audio_start_pts": a.get("start_pts"),
               "video_duration_ts": v.get("duration_ts"), "audio_duration_ts": a.get("duration_ts"),
               "avg_frame_rate": v.get("avg_frame_rate"), "r_frame_rate": v.get("r_frame_rate"),
               "variable_frame_rate_likely": vfr_likely,
               "timestamp_reference": "decoder/container PTS when available; frame_index/fps only fallback",
               "interval_convention": "[start,end)", "time_unit": "seconds",
               "audio_codec": a.get("codec_name"), "video_codec": v.get("codec_name"),
               "file_size_bytes": Path(video).stat().st_size}, notes=notes)
