from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import time
import urllib.error
import urllib.request
from urllib.parse import urlsplit
from .core import scrub, digest


LOOPBACK_HOSTS = {"127.0.0.1", "localhost", "::1"}


# Generated by GitHub Copilot - Oct-05-2026
def validate_url(url: str) -> str:
    """Allow only a credential-free loopback API base without query or fragment."""
    url = (url or "").rstrip("/")
    parsed = urlsplit(url)
    if (parsed.scheme != "http" or parsed.hostname not in LOOPBACK_HOSTS or
            parsed.username or parsed.password or parsed.query or parsed.fragment or parsed.path not in ('','/')):
        raise ValueError("Ollama deve usar HTTP em loopback (127.0.0.1/localhost) para manter a analise local.")
    return url


# Generated by GitHub Copilot - Oct-05-2026
class LoopbackRedirectHandler(urllib.request.HTTPRedirectHandler):
    """Prevent local inference from exfiltrating transcript via an HTTP redirect."""

    def redirect_request(self, request, response, code, message, headers, new_url):
        """Reject redirects: the Ollama control plane is a fixed loopback API."""
        raise ValueError('Redirecionamento HTTP bloqueado no cliente Ollama local.')


def _request_json(url: str, path: str, payload=None, timeout: float = 5.0):
    base = validate_url(url)
    data = None
    headers = {}
    method = "GET"
    if payload is not None:
        method = "POST"
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(base + path, data=data, headers=headers, method=method)
    # Generated by GitHub Copilot - Oct-05-2026
    opener=urllib.request.build_opener(urllib.request.ProxyHandler({}),LoopbackRedirectHandler())
    with opener.open(req,timeout=timeout) as response:
        data=response.read(8 * 1024 ** 2 + 1)
        if len(data)>8 * 1024 ** 2:
            raise ValueError('Resposta Ollama excede limite de payload.')
        return json.loads(data,parse_constant=lambda value: (_ for _ in ()).throw(ValueError('JSON nao finito: '+value)))


def service_info(url: str, timeout: float = 2.0) -> dict:
    info = {
        "reachable": False,
        "version": None,
        "models": [],
        "running": [],
        "cli": shutil.which("ollama"),
        "error": None,
    }
    try:
        version = _request_json(url, "/api/version", timeout=timeout)
        tags = _request_json(url, "/api/tags", timeout=timeout)
        info["version"] = version.get("version")
        info["models"] = tags.get("models", []) or []
        info["reachable"] = True
        try:
            ps = _request_json(url, "/api/ps", timeout=timeout)
            info["running"] = ps.get("models", []) or []
        except Exception:
            pass
    except Exception as exc:
        info["error"] = scrub(f"{type(exc).__name__}: {exc}")
    return info


def installed_model_names(url: str, timeout: float = 2.0) -> list[str]:
    return [m.get("name") for m in service_info(url, timeout).get("models", []) if m.get("name")]


def resolve_model(requested: str, installed: list[dict] | list[str]) -> str:
    names = []
    sizes = {}
    for item in installed:
        if isinstance(item, dict):
            name = item.get("name") or item.get("model")
            if name:
                names.append(name)
                sizes[name] = int(item.get("size") or 0)
        elif item:
            names.append(str(item))
    if requested and requested != "auto":
        return requested
    if not names:
        return "qwen3:14b"
    # Prefer larger general-purpose local text models while avoiding obvious embedding-only models.
    usable = [n for n in names if not re.search(r"embed|embedding|nomic|bge|snowflake", n, re.I)] or names
    preferred = [n for n in usable if re.search(r"qwen|gemma|llama|mistral|gpt-oss|phi", n, re.I)] or usable
    return max(preferred, key=lambda n: (sizes.get(n, 0), n))


def profile_options(cfg: dict) -> dict:
    profile = cfg.get("profile", "max")
    presets = {
        "fast": {
            "num_ctx": 8192,
            "num_predict": 2048,
            "temperature": 0.0,
            "top_k": 40,
            "top_p": 0.90,
            "repeat_penalty": 1.05,
            "seed": 42,
        },
        "balanced": {
            "num_ctx": 16384,
            "num_predict": 4096,
            "temperature": 0.0,
            "top_k": 40,
            "top_p": 0.90,
            "repeat_penalty": 1.05,
            "seed": 42,
        },
        "max": {
            "num_ctx": 32768,
            "num_predict": 6144,
            "temperature": 0.0,
            "top_k": 40,
            "top_p": 0.90,
            "repeat_penalty": 1.05,
            "seed": 42,
        },
    }
    options = dict(presets.get(profile, presets["max"]))
    for key in ("num_ctx", "num_predict", "temperature", "top_k", "top_p", "repeat_penalty", "seed"):
        value = cfg.get(key)
        if value is not None:
            options[key] = value
    return options


class OllamaContentError(ValueError):
    def __init__(self, message, metadata):
        super().__init__(message)
        self.metadata = metadata


def chat(url: str, model: str, messages: list[dict], schema: dict, cfg: dict) -> tuple[dict, dict]:
    options = profile_options(cfg)
    payload = {
        "model": model,
        "stream": False,
        "format": schema,
        "messages": messages,
        "options": options,
        "keep_alive": cfg.get("keep_alive", "30m"),
    }
    if cfg.get('think') is not None:
        payload['think'] = cfg['think']
    timeout = float(cfg.get("timeout_seconds", 600))
    started = time.monotonic()
    result = _request_json(url, "/api/chat", payload=payload, timeout=timeout)
    message = result.get('message') or {}
    content = message.get("content")
    meta = {
        "request_id": digest(payload)[:20], "duration_seconds": time.monotonic() - started,
        "model": result.get("model") or model,
        "profile": cfg.get("profile", "max"),
        "options": options,
        "total_duration_ns": result.get("total_duration"),
        "load_duration_ns": result.get("load_duration"),
        "prompt_eval_count": result.get("prompt_eval_count"),
        "eval_count": result.get("eval_count"),
        "eval_duration_ns": result.get("eval_duration"),
        "prompt_eval_duration_ns": result.get("prompt_eval_duration"),
        "thinking_chars": len(message.get('thinking') or ''), "thinking_requested": cfg.get('think'),
        "response_fields": sorted(message),
        "done_reason": result.get("done_reason"),
        "input_chars":sum(len(message.get('content','')) for message in messages),
        "output_chars":len(content or ''),
        "confidence_is_calibrated":False,
    }
    if not isinstance(content, str) or not content.strip():
        meta['failure_category'] = 'empty_thinking_only' if message.get('thinking') else 'empty_content'
        meta['recommended_action'] = 'disable_thinking_or_reduce_structured_output_budget' if result.get('done_reason') == 'length' else 'check_model_and_api_contract'
        raise OllamaContentError('Ollama retornou resposta sem message.content; done_reason=' + str(result.get('done_reason')) + '; ' + meta['failure_category'], meta)
    try:
        parsed = json.loads(content,parse_constant=lambda value: (_ for _ in ()).throw(ValueError('JSON nao finito: '+value)))
    except ValueError as exc:
        meta['failure_category'] = 'invalid_json'
        raise OllamaContentError('Ollama retornou JSON invalido.', meta) from exc
    return parsed, meta


def nvidia_smi() -> dict:
    exe = shutil.which("nvidia-smi")
    if not exe:
        return {"available": False, "gpus": []}
    cmd = [exe, "--query-gpu=name,memory.total,memory.free,driver_version", "--format=csv,noheader,nounits"]
    try:
        cp = subprocess.run(cmd, capture_output=True, text=True, timeout=5, check=True)
        gpus = []
        for line in cp.stdout.splitlines():
            parts = [p.strip() for p in line.split(",")]
            if len(parts) >= 4:
                gpus.append({"name": parts[0], "vram_total_mib": int(float(parts[1])),
                             "vram_free_mib": int(float(parts[2])), "driver": parts[3]})
        return {"available": bool(gpus), "gpus": gpus}
    except Exception as exc:
        return {"available": False, "gpus": [], "error": f"{type(exc).__name__}: {exc}"}


def windows_install_command() -> str:
    return "winget install --id Ollama.Ollama -e --accept-source-agreements --accept-package-agreements"
