"""Conservative tracklet-to-person consolidation, separate from the online tracker."""

from collections import defaultdict
import math
import numpy as np
from .core import ok


# Generated by GitHub Copilot - Oct-05-2026
def _quantile(values, fraction):
    """Return an observed distribution quantile, or null for absent measurements."""
    ordered = sorted(values)
    if not ordered:
        return None
    position = (len(ordered) - 1) * fraction
    lower = int(position)
    upper = min(lower + 1, len(ordered) - 1)
    return ordered[lower] + (ordered[upper] - ordered[lower]) * (position - lower)


# Generated by GitHub Copilot - Oct-05-2026
def _embedding(rows):
    """Aggregate compatible finite samples robustly; never average dimensions."""
    samples = defaultdict(list)
    for row in rows:
        value = row.get("face_embedding")
        if value is None:
            continue
        vector = np.asarray(value, dtype=float).reshape(-1)
        norm = float(np.linalg.norm(vector))
        if 1 < len(vector) <= 4096 and np.isfinite(vector).all() and norm > 1e-8:
            samples[len(vector)].append(vector / norm)
    if not samples:
        return None
    vectors = max(samples.values(), key=len)
    if len(vectors) > 32:
        vectors = [vectors[index] for index in np.linspace(0, len(vectors) - 1, 32, dtype=int)]
    template = np.median(np.stack(vectors), axis=0)
    norm = float(np.linalg.norm(template))
    return template / norm if norm > 1e-8 else None


# Generated by GitHub Copilot - Oct-05-2026
def _buckets(vector):
    """Use deterministic banded signs to bound candidate retrieval on long videos."""
    size = len(vector)
    for band in range(4):
        indices = [(band * 29 + offset * 17) % size for offset in range(8)]
        yield size, band, tuple(bool(vector[index] >= 0) for index in indices)


# Generated by GitHub Copilot - Oct-05-2026
def _face_neighbors(vector, people, limit=12):
    """Exact, bounded cosine retrieval; never uses appearance, screen position or identity names.

    Returns candidates plus the nearest competitor(s), so a weak indexed match
    cannot win simply because a stronger face fell on another hash boundary.
    The identity count bound prevents adversarial inputs from exhausting memory.
    """
    valid = [(pid, person["template"]) for pid, person in people.items()
             if person.get("template") is not None and len(person["template"]) == len(vector)]
    if not valid or len(valid) > 2500:
        return []
    matrix = np.stack([value for _, value in valid])
    scores = matrix @ vector
    positions = np.argsort(-scores, kind="stable")[:max(2, min(int(limit), len(valid)))]
    return [(float(scores[index]), valid[index][0]) for index in positions
            if np.isfinite(scores[index])]


def _conflict(track, person):
    """Never merge simultaneous tracklets, including observations on one frame."""
    for interval in person["intervals"]:
        if track["first_seen"] <= interval[1] and interval[0] <= track["last_seen"]:
            return True
    return False


# Generated by GitHub Copilot - Oct-05-2026
def build_person_identities(vision, cfg=None):
    """Consolidate qualified tracklets with facial evidence, not screen position."""
    cfg = cfg or {}
    min_seconds = cfg.get("tracklet_min_visual_seconds", 1.0)
    min_observations = cfg.get("tracklet_min_observations", 3)
    threshold, required_margin = cfg.get("reid_threshold", .55), cfg.get("reid_margin", .08)
    candidate_limit = int(cfg.get("reid_candidate_limit", 64))
    max_gap = cfg.get("track_max_gap_seconds", 1.2)
    grouped = defaultdict(list)
    raw_people={person['person_id']:person for person in vision.get('people',[]) if person.get('person_id')}
    orphan_count = 0
    for row in vision.get("observations", []):
        track_id = row.get("track_id")
        if not track_id:
            orphan_count += 1
            continue
        if isinstance(row.get("time"), (int, float)) and math.isfinite(row["time"]):
            grouped[track_id].append(row)
    tracks, templates = [], {}
    for track_id, rows in sorted(grouped.items()):
        rows.sort(key=lambda row: row["time"])
        times = sorted({row["time"] for row in rows})
        visual_seconds = sum(right - left for left, right in zip(times, times[1:]) if 0 < right - left <= max_gap)
        vector = _embedding(rows)
        if vector is not None:
            templates[track_id] = vector
        legacy_scores = [row["same_person_confidence"] for row in rows
                         if row.get("tracking_method") == "anonymous_face_embedding" and
                         isinstance(row.get("same_person_confidence"), (int, float)) and
                         math.isfinite(row["same_person_confidence"])]
        tracks.append({"tracklet_id": track_id, "track_id": track_id,
                       "first_seen": times[0], "last_seen": times[-1], "duration": times[-1] - times[0],
                       "visual_seconds": visual_seconds, "observation_count": len(times),
                       "source_person_ids": sorted({row["person_id"] for row in rows if row.get("person_id")}),
                       "scene_ids": sorted({row["scene_id"] for row in rows if row.get("scene_id")}),
                       "face_samples": sum(bool(row.get("face_visible")) for row in rows),
                       "embedding_sample_count": sum(row.get("face_embedding") is not None for row in rows),
                       "embedding_aggregation": "normalized_coordinate_median_max_32_samples",
                       "tracklet_state": "stable_tracklet" if visual_seconds >= min_seconds and len(times) >= min_observations else "micro_tracklet",
                       "face_embedding_available": vector is not None or bool(legacy_scores),
                       "legacy_embedding_similarity": min(legacy_scores) if legacy_scores else None,
                       "qualified": visual_seconds >= min_seconds and len(times) >= min_observations,
                       "person_id": None, "identity_status": "insufficient_evidence"})
    tracks.sort(key=lambda track: (track["first_seen"], track["track_id"]))
    persons, mapping, decisions = {}, {}, []
    index, legacy_index = defaultdict(set), defaultdict(set)
    stable_fallback_attached = 0
    for track in tracks:
        track_id = track["track_id"]
        if not track["qualified"]:
            mapping[track_id] = None
            decisions.append({"tracklet_id": track_id, "accepted": False, "reason": "insufficient_tracklet_evidence"})
            continue
        vector = templates.get(track_id)
        candidates = set()
        if vector is not None:
            for bucket in _buckets(vector):
                candidates.update(index[bucket])
        if track["legacy_embedding_similarity"] is not None:
            for source_id in track["source_person_ids"]:
                candidates.update(legacy_index[source_id])
        scored = []
        for person_id in sorted(candidates)[:candidate_limit]:
            person = persons[person_id]
            existing = person.get("template")
            similarity = (float(np.dot(vector, existing)) if vector is not None and existing is not None and len(vector) == len(existing)
                          else track["legacy_embedding_similarity"] if person_id in candidates and
                          set(track["source_person_ids"]) & set(person["source_person_ids"]) else None)
            if similarity is None:
                continue
            temporal_conflict = _conflict(track, person)
            scored.append((similarity, person_id, temporal_conflict))
        scored.sort(key=lambda score: (-score[0], score[1]))
        eligible = [score for score in scored if not score[2]]
        best = eligible[0] if eligible else None
        alternatives = [score[0] for score in scored if best is None or score[1] != best[1]]
        margin = best[0] - max(alternatives) if best and alternatives else (1.0 if best else None)
        accepted = bool(best and best[0] >= threshold and margin >= required_margin)
        # Hash buckets are for speed, not an identity oracle: a very strong
        # candidate on the opposite side of a sign boundary should be tested.
        # Only use the expensive global search for otherwise-unmatched stable
        # tracks, with stricter thresholds than ordinary Re-ID.
        stable_fallback = False
        if not accepted and vector is not None and persons:
            nearest = _face_neighbors(vector, persons, candidate_limit)
            if nearest:
                candidate, similarity = nearest[0][1], nearest[0][0]
                competitor = nearest[1][0] if len(nearest) > 1 else -1.
                strict_threshold = max(float(threshold) + .23, .80)
                strict_margin = max(float(required_margin) + .06, .14)
                if (similarity >= strict_threshold and similarity - competitor >= strict_margin
                        and not _conflict(track, persons[candidate])):
                    scored = [(similarity, candidate, False)]
                    best, margin, accepted, stable_fallback = scored[0], similarity - competitor, True, True
        for similarity, candidate, conflict in scored:
            decisions.append({"tracklet_id": track_id, "candidate_person_id": candidate,
                              "accepted": accepted and candidate == best[1],
                              "embedding_similarity": similarity, "threshold": threshold, "margin": margin,
                              "required_margin": required_margin, "temporal_conflict": conflict,
                              "reason": "simultaneous_identity_conflict" if conflict else
                                        "strong_face_evidence" if accepted and candidate == best[1] else "threshold_or_margin_not_met",
                              "candidate_search": "strict_full_face_fallback" if stable_fallback else "bounded_banded_face_templates",
                              "screen_position_used": False})
        if accepted:
            person_id = best[1]
            stable_fallback_attached += int(stable_fallback)
        else:
            preferred = next((source_id for source_id in track["source_person_ids"] if source_id not in persons), None)
            person_id = preferred or f"PERSON_REID_{len(persons) + 1:05}"
            while person_id in persons:
                person_id += "_N"
            persons[person_id] = {"person_id": person_id, "track_ids": [], "intervals": [], "template": vector,
                                  "templates": [], "embedding_sample_count": 0,
                                  "source_person_ids": [], "first_seen": track["first_seen"], "last_seen": track["last_seen"],
                                  "observation_count": 0, "face_samples": 0, "total_visual_seconds": 0.0,
                                  "scene_ids": [], "name": None, "civil_identity_inferred": False,
                                  "reid_confidence": None, "same_person_confidence": None,
                                  "identity_methods": ["qualified_tracklet"], "identity_status": "within_track_only"}
            if not scored:
                decisions.append({"tracklet_id": track_id, "accepted": False,
                                  "reason": "no_face_embedding" if vector is None else "no_supported_match"})
        person = persons[person_id]
        person["embedding_sample_count"] += track["embedding_sample_count"]
        if vector is not None:
            person["templates"].append(vector)
            person["templates"] = person["templates"][-32:]
            aggregate = np.median(np.stack(person["templates"]), axis=0)
            norm = float(np.linalg.norm(aggregate))
            if norm > 1e-8:
                person["template"] = aggregate / norm
        person["track_ids"].append(track_id)
        person["intervals"].append((track["first_seen"], track["last_seen"]))
        person["last_seen"] = max(person["last_seen"], track["last_seen"])
        person["total_visual_seconds"] += track["visual_seconds"]
        person["observation_count"] += track["observation_count"]
        person["face_samples"] += track["face_samples"]
        person["source_person_ids"] = sorted(set(person["source_person_ids"]) | set(track["source_person_ids"]))
        person["scene_ids"] = sorted(set(person["scene_ids"]) | set(track["scene_ids"]))
        if accepted:
            person["identity_status"] = "face_supported_across_tracks"
            person["reid_confidence"] = min(best[0], person["reid_confidence"] or best[0])
            person["same_person_confidence"] = person["reid_confidence"]
            person["identity_methods"] = ["qualified_tracklet", "face_embedding_or_legacy_face_evidence"]
        if person["template"] is not None:
            for bucket in _buckets(person["template"]):
                index[bucket].add(person_id)
        for source_id in track["source_person_ids"]:
            legacy_index[source_id].add(person_id)
        track.update(person_id=person_id, identity_status=person["identity_status"])
        mapping[track_id] = person_id

    micro_threshold = max(float(cfg.get("micro_reid_threshold", threshold + .17)), threshold + .12)
    micro_margin = max(float(cfg.get("micro_reid_margin", required_margin + .05)), required_margin + .04)
    micro_attached = 0
    micro_retrieval_fallback_attempts = 0
    micro_retrieval_fallback_matches = 0
    micro_retrieval_fallback_accepted = 0
    for track in [row for row in tracks if not row["qualified"]]:
        track_id = track["track_id"]
        vector = templates.get(track_id)
        if vector is None or not persons:
            mapping[track_id] = None
            decisions.append({"tracklet_id": track_id, "accepted": False,
                              "reason": "micro_tracklet_without_face_template" if vector is None else "no_established_identity",
                              "micro_tracklet": True, "screen_position_used": False})
            continue
        # Scan the full established gallery for *every* face-supported micro.
        # An indexed candidate can be wrong even when the bucket is populated;
        # include the nearest competing identity before accepting a merge.
        micro_retrieval_fallback_attempts += 1
        nearest = _face_neighbors(vector, persons, candidate_limit)
        if nearest:
            micro_retrieval_fallback_matches += 1
        fallback_search = True
        scored = [(similarity, candidate, _conflict(track, persons[candidate]))
                  for similarity, candidate in nearest]
        scored.sort(key=lambda score: (-score[0], score[1]))
        # Do not attach to runner-up when the nearest face has a temporal
        # conflict. Likewise, margin must consider ALL competitors, not only
        # conflict-free identities. Ambiguity is a rejection, not an invitation
        # to reinterpret identity using location or time.
        best = scored[0] if scored else None
        margin = best[0] - scored[1][0] if len(scored) > 1 else (1.0 if best else None)
        observed_samples = track["embedding_sample_count"]
        evidence_threshold = max(micro_threshold, .86) if observed_samples == 1 else micro_threshold
        accepted = bool(best and not best[2] and best[0] >= evidence_threshold and margin >= micro_margin)
        for similarity, candidate, conflict in scored:
            decisions.append({"tracklet_id": track_id, "candidate_person_id": candidate,
                              "accepted": accepted and candidate == (best[1] if best else None),
                              "embedding_similarity": similarity, "threshold": evidence_threshold,
                              "embedding_sample_count": observed_samples,
                              "margin": margin, "required_margin": micro_margin,
                              "temporal_conflict": conflict, "micro_tracklet": True,
                              "reason": "simultaneous_identity_conflict" if conflict else
                                        "strict_face_supported_micro_reentry" if accepted and candidate == best[1] else
                                        "micro_threshold_or_margin_not_met",
                              "candidate_search": "strict_nearest_face_fallback" if fallback_search else "bounded_banded_face_templates",
                              "screen_position_used": False})
        if not accepted:
            mapping[track_id] = None
            if not scored:
                decisions.append({"tracklet_id": track_id, "accepted": False, "micro_tracklet": True,
                                  "reason": "micro_no_supported_match", "screen_position_used": False})
            continue
        person_id = best[1]
        person = persons[person_id]
        person["track_ids"].append(track_id)
        person["intervals"].append((track["first_seen"], track["last_seen"]))
        person["first_seen"] = min(person["first_seen"], track["first_seen"])
        person["last_seen"] = max(person["last_seen"], track["last_seen"])
        person["total_visual_seconds"] += track["visual_seconds"]
        person["observation_count"] += track["observation_count"]
        person["face_samples"] += track["face_samples"]
        person["embedding_sample_count"] += track["embedding_sample_count"]
        person["source_person_ids"] = sorted(set(person["source_person_ids"]) | set(track["source_person_ids"]))
        person["scene_ids"] = sorted(set(person["scene_ids"]) | set(track["scene_ids"]))
        person["identity_methods"] = sorted(set(person.get("identity_methods", [])) | {"strict_micro_face_reentry"})
        person["identity_status"] = "face_supported_across_tracks"
        track.update(person_id=person_id, identity_status="face_supported_micro_reentry")
        mapping[track_id] = person_id
        micro_attached += 1
        if fallback_search:
            micro_retrieval_fallback_accepted += 1

    identities = []
    for person in sorted(persons.values(), key=lambda person: person["person_id"]):
        identities.append({key: value for key, value in person.items() if key not in ("template", "templates", "intervals")})
        identities[-1].update(persistent_across_tracks=len(person["track_ids"]) > 1,
                              robust_face_embedding=person["template"].tolist() if person["template"] is not None else None,
                              face_embedding_templates=[sample.tolist() for sample in person["templates"]],
                              embedding_aggregation="normalized_coordinate_median_max_32_templates",
                              meaningful=person["total_visual_seconds"] >= cfg.get("identity_min_visual_seconds", 3.0),
                              visual_seconds_method="sum_observed_tracklet_gaps_with_continuity_limit",
                              portrait=next((raw_people[source_id].get('portrait') for source_id in person['source_person_ids']
                                             if raw_people.get(source_id,{}).get('portrait')),None))
    durations = [track["duration"] for track in tracks]
    raw = len(tracks)
    micro = sum(not track["qualified"] for track in tracks)
    missing_embeddings = sum(not track["face_embedding_available"] for track in tracks)
    attached_micro = [track for track in tracks if not track["qualified"] and mapping.get(track["track_id"])]
    micro_with_embeddings = sum(not track["qualified"] and track["embedding_sample_count"] > 0 for track in tracks)
    metrics = {"raw_track_count": raw, "valid_track_count": raw - micro, "micro_track_count": micro,
               "micro_with_embedding_count": micro_with_embeddings,
               "micro_without_embedding_count": micro - micro_with_embeddings,
               "micro_face_attachment_fraction": micro_attached / micro_with_embeddings if micro_with_embeddings else None,
               "micro_reid_attached_one_sample_count": sum(t["embedding_sample_count"] == 1 for t in attached_micro),
               "micro_track_ratio": micro / raw if raw else None,
               "micro_reid_attachment_count": micro_attached,
               "micro_retrieval_fallback_attempts": micro_retrieval_fallback_attempts,
               "micro_retrieval_fallback_matches": micro_retrieval_fallback_matches,
               "micro_retrieval_fallback_accepted": micro_retrieval_fallback_accepted,
               "micro_exact_gallery_search_count": micro_retrieval_fallback_attempts,
               "micro_exact_gallery_contract": "bounded_full_cosine_gallery_with_runner_up_and_temporal_conflicts",
               "stable_exact_fallback_accepted": stable_fallback_attached,
               "micro_track_mapped_fraction": micro_attached / micro if micro else None,
               "unmapped_micro_track_count": micro - micro_attached,
               "short_track_ratio": sum(duration < 1 for duration in durations) / raw if raw else None,
               "median_track_duration": _quantile(durations, .5), "orphan_track_count": orphan_count,
               "persistent_person_count": len(identities), "meaningful_persistent_person_count": sum(person["meaningful"] for person in identities),
               "tracks_without_face_embedding_fraction": missing_embeddings / raw if raw else None,
               "identity_fragmentation_score": (micro + missing_embeddings) / (2 * raw) if raw else None,
               "identity_fragmentation_method": "heuristic_microtrack_and_missing_embedding_indicator_not_accuracy",
               "track_fragmentation_ratio": None, "id_switch_count": None,
               "id_switch_measurement": "requires_annotated_identity_ground_truth",
               "probable_id_switch_count": sum(
                   1 for rows in grouped.values()
                   for previous, current in zip([row for row in rows if row.get("face_embedding") is not None],
                                                [row for row in rows if row.get("face_embedding") is not None][1:])
                   if len(previous["face_embedding"]) == len(current["face_embedding"]) and
                   np.dot(previous["face_embedding"], current["face_embedding"]) < .3),
               "probable_id_switch_method": "within_track_embedding_contradiction_proxy_not_accuracy",
               "confirmed_track_count": raw - micro,
               "embedding_success_fraction": (raw - missing_embeddings) / raw if raw else None,
               "reid_merge_count": sum(bool(decision["accepted"]) for decision in decisions),
               "reid_rejected_merge_count": sum(not decision["accepted"] for decision in decisions),
               "simultaneous_identity_conflict_count": sum(decision.get("temporal_conflict", False) for decision in decisions),
               "tracks_per_person": {person["person_id"]: len(person["track_ids"]) for person in identities},
               "person_total_visual_seconds": {person["person_id"]: person["total_visual_seconds"] for person in identities}}
    for label, fraction in (("p25", .25), ("p50", .5), ("p75", .75), ("p95", .95)):
        metrics["track_duration_" + label] = _quantile(durations, fraction)
        metrics["observations_per_track_" + label] = _quantile([track["observation_count"] for track in tracks], fraction)
        metrics["tracks_per_person_" + label] = _quantile([len(person["track_ids"]) for person in identities], fraction)
    from .visual_identity_audit import audit_embedding_gaps
    gap_audit = audit_embedding_gaps(vision, {'tracklets': tracks})
    metrics['embedding_gap_tracklet_count'] = gap_audit['tracklets_without_embedding']
    metrics['micro_embedding_absence_by_cause'] = gap_audit['micro_without_embedding_by_cause']
    return ok({"identities": identities, "tracklets": tracks, "tracklet_to_person": mapping,
               "merge_decisions": decisions, "metrics": metrics,
               "embedding_gap_audit": gap_audit}, "ok" if identities else "partial",
              ["Identidades sao anonimas dentro do video, nao pessoas civis unicas.",
               "Micro-tracklets ficam na evidencia bruta; somente reentrada facial estrita pode anexa-los a identidade existente; posicao nao e usada."])


# Generated by GitHub Copilot - Oct-05-2026
def apply_person_identities(vision, reid):
    """Project persistent IDs for downstream consumers, retaining all raw tracklets."""
    mapping = reid.get("tracklet_to_person", {})
    observations = []
    by_time = defaultdict(set)
    for row in vision.get("observations", []):
        person_id = mapping.get(row.get("track_id"))
        if person_id:
            observations.append({**row, "raw_person_id": row.get("person_id"),
                                 "person_id": person_id, "persistent_person_id": person_id,
                                 "tracklet_id": row.get("track_id")})
            by_time[row["time"]].add(person_id)
    return {**vision, "raw_people": vision.get("people", []),
            "tracklet_observations": vision.get("observations", []),
            "people": reid.get("identities", []), "observations": observations,
            "frames": [{**frame, "raw_visible_people": frame.get("visible_people", []),
                        "visible_people": sorted(by_time[frame["time"]])} for frame in vision.get("frames", [])],
            "tracking_metrics": reid.get("metrics", {})}
