from pathlib import Path
from collections import Counter, defaultdict
from datetime import datetime, timezone
import re
from . import __version__, __build__
from .config import ROOT, configure_local_mode
from .core import Context, file_hash, setup_logging, output_lock, logging_session, external_fingerprints, ok, digest
from .media import resolve_input, inspect
from .audio import extract_audio, audio_metrics, sound_events
from .transcription import TranscriptionEngine
from .diarization import DiarizationEngine, align_speakers
from .scenes import SceneEngine
from .vision import VisionEngine, ActiveSpeakerEngine
from .visual_sampling import speaker_sampling_fingerprint
from .person_reid import build_person_identities, apply_person_identities
from .person_motion import build_person_motion
from .active_speaker import build_active_speaker
from .shots import build_shots
from .camera_timeline import build_camera_timeline
from .ocr import OcrEngine
from .semantic import SemanticEngine
from .timeline import build_timeline, captions, enrich_editorial
from .understanding import run_understanding
from .master_timeline import build_master_timeline
from .analysis_quality import build_analysis_quality
from .reports import ReportEngine
from .director_integration import run_planner_stage, run_director_stage, attach_director
from .preview_integration import run_preview_stage
from .preflight import require_preflight


def _active_stage(ctx, audio, diarization, vision, metadata, cfg):
    # Generated by GitHub Copilot - Oct-05-2026
    if not ctx.config['vision']['enabled'] or not ctx.config['vision']['active_speaker']:
        return ok({'mappings':[],'mapping_summary':[],'intervals':[],'coverage':0.0},'skipped',
                  ['Active speaker desabilitado explicitamente; pessoa vinculada permanece desconhecida.'])
    raw_result = ActiveSpeakerEngine().run(ctx, audio, diarization, vision, metadata)
    raw = raw_result.get("data", {})
    refined = build_active_speaker(diarization, vision, raw.get("mappings", []), cfg)
    refined["notes"] = list(raw_result.get("notes", [])) + list(refined.get("notes", []))
    raw_status = raw_result.get("status", "partial")
    if raw_status in ("unavailable", "failed"):
        refined["status"] = raw_status
    elif raw_status == "partial" and refined.get("status") == "ok":
        refined["status"] = "partial"
    return refined


def analyze(source, cfg, output=None, force=False):
    configure_local_mode(cfg)
    from .progress import emit_event
    emit_event({'event':'stage_progress', 'stage':'00_preflight', 'status':'running', 'current':None, 'total':None})
    # Generated by GitHub Copilot - Oct-05-2026
    readiness=require_preflight(cfg, output)
    emit_event({'event':'stage_progress', 'stage':'00_preflight', 'status':'ok', 'current':1, 'total':1})
    emit_event({'event':'stage_progress', 'stage':'00_source', 'status':'running', 'current':None, 'total':None})
    video, provenance = resolve_input(source, cfg, ROOT)
    emit_event({'event':'stage_progress', 'stage':'00_source', 'status':'ok', 'current':1, 'total':1})
    signature = file_hash(video)
    stem = re.sub(r"[^\w-]+", "_", video.stem)[:70] or "video"
    destination = Path(output).expanduser().resolve() if output else ROOT/"analysis"/f"{stem}_{signature[:8]}"
    if destination == video or destination in video.parents:
        raise ValueError("A saída deve ser uma pasta separada do arquivo de entrada.")
    logger = setup_logging(destination)
    # Generated by GitHub Copilot - Oct-05-2026
    logger.info("00_preflight: READY | diarization=%s | vision=%s | semantic=%s",
                cfg["diarization"]["enabled"], cfg["vision"]["enabled"], cfg["semantic_analysis"]["backend"])
    ctx = Context(video, destination, cfg, signature, logger, force)
    # Generated by GitHub Copilot - Oct-05-2026
    external = {stage:external_fingerprints(cfg,stage) for stage in ('02_audio','04_transcription','05_diarization',
                                                                   '07_people_tracking','10_active_speaker','14_audio_events')}
    capabilities=readiness['capabilities']
    model_fingerprints={'asr':capabilities['asr']['checks'].get('configuration',{}).get('model_fingerprint'),
                        'diarization':capabilities['diarization']['checks'].get('model_access',{}).get('model_fingerprint'),
                        'semantic':capabilities['semantic']['checks'].get('model',{}).get('model_fingerprint')}

    from .storage import media_lease
    with logging_session(logger), output_lock(destination), media_lease(video):
        metadata = ctx.step("01_metadata", {}, lambda: inspect(video), required=True,
                            code_files=["media.py", "core.py"])
        metadata.update(
            source=provenance, sha256=signature, analyzer_version=__version__,
            schema_version='2.0', camera_director_version='4.4.0',
            analyzed_at_utc=datetime.now(timezone.utc).isoformat(),
        )
        from .runtime_metrics import historical_stage_estimates
        ctx.progress('01_metadata', status='ok', metadata=metadata,
                     historical_stage_estimates=historical_stage_estimates(metadata, cfg))

        audio = ctx.step("02_audio", {"audio": cfg["audio"], "external": external['02_audio']},
                         lambda: extract_audio(ctx, metadata), required=True,
                         code_files=["audio.py", "core.py"])
        metrics = ctx.step("03_audio_quality", cfg["audio"],
                           lambda: audio_metrics(ctx, audio, metadata),
                           code_files=["audio.py", "core.py"])
        transcript = ctx.step(
            "04_transcription",
            {"transcription": cfg["transcription"], "device": cfg["device"],
             "compute": cfg["compute_type"], "language":cfg['language'],"offline": cfg["offline"], "external": external['04_transcription'],
             "model_fingerprint":model_fingerprints['asr']},
            lambda: TranscriptionEngine(ctx).run(audio, metrics, metadata), required=True,
            code_files=["transcription.py", "gpu_runtime.py", "audio.py", "core.py"])
        # Generated by GitHub Copilot - Oct-05-2026
        raw_transcript = transcript

        diarization = ctx.step(
            "05_diarization",
            {"config": cfg["diarization"], "external": external['05_diarization'],"device":cfg['device'],"offline":cfg['offline'],
             "model_fingerprint":model_fingerprints['diarization'],
             "token_available": bool(__import__("os").environ.get("HF_TOKEN") or
                                     __import__("os").environ.get("HUGGING_FACE_HUB_TOKEN"))},
            lambda: DiarizationEngine().run(ctx, audio, metadata),
            code_files=["diarization.py", "model_cache.py", "core.py"])
        transcript = align_speakers(transcript, diarization)

        scene_data = ctx.step("06_scenes", cfg["scenes"],
                              lambda: SceneEngine().run(ctx, metadata),
                              code_files=["scenes.py", "core.py"])
        scenes = scene_data.get("scenes") or [{
            "scene_id": "SCENE_00000", "start": 0, "end": metadata["duration"],
            "duration": metadata["duration"], "scene_type": "unknown", "detected": False,
            "keyframe": None, "visible_people": [], "predominant_person": None,
        }]
        scene_metrics = scene_data.get("scene_metrics", {})

        vision = ctx.step(
            "07_people_tracking", {"config": cfg["vision"], "external": external['07_people_tracking'],
                                   "speaker_sampling_fingerprint": speaker_sampling_fingerprint(transcript)},
            lambda: VisionEngine().run(ctx, metadata, scenes, transcript),
            code_files=["vision.py", "visual_sampling.py", "core.py"])
        # Generated by GitHub Copilot - Oct-05-2026
        reid_cfg = {key: cfg["vision"][key] for key in ("reid_threshold", "reid_margin", "track_max_gap_seconds",
                "tracklet_min_visual_seconds", "tracklet_min_observations", "identity_min_visual_seconds", "reid_candidate_limit",
                "micro_reid_threshold", "micro_reid_margin")}
        reid = ctx.step("08_person_reid", reid_cfg,
                lambda: build_person_identities(vision, reid_cfg),
                        code_files=["person_reid.py", "vision.py", "core.py"], requires=["07_people_tracking"])
        vision = apply_person_identities(vision, reid)
        motion = ctx.step("09_person_motion", cfg["person_motion"],
                          lambda: build_person_motion(vision, cfg["person_motion"]),
                          code_files=["person_motion.py", "core.py"], requires=["08_person_reid"])
        active = ctx.step(
            "10_active_speaker",
            {"vision": cfg["vision"], "active_speaker": cfg["active_speaker"], "external": external['10_active_speaker']},
            lambda: _active_stage(ctx, audio, diarization, vision, metadata, cfg["active_speaker"]),
            code_files=["vision.py", "active_speaker.py", "speaker_signals.py", "perception_diagnostics.py", "temporal.py", "core.py"],
            requires=["05_diarization", "08_person_reid"])

        shot_data = ctx.step("11_shots", cfg["shots"],
                             lambda: build_shots(scenes, vision, metadata, cfg["shots"]),
                             code_files=["shots.py", "core.py"], requires=["06_scenes", "08_person_reid"])
        shots = shot_data.get("shots", [])
        camera_data = ctx.step(
            "12_camera_timeline", cfg["camera_timeline"],
            lambda: build_camera_timeline(metadata, vision, shots, active.get("intervals", []),
                                          motion.get("people", []), cfg["camera_timeline"]),
            code_files=["camera_timeline.py", "temporal.py", "core.py"],
            requires=["08_person_reid", "09_person_motion", "10_active_speaker", "11_shots"])
        camera_timeline = camera_data.get("timeline", [])

        ocr = ctx.step("13_ocr", cfg["ocr"], lambda: OcrEngine().run(ctx, vision),
                       code_files=["ocr.py", "core.py"])
        events = ctx.step("14_audio_events", {"config": cfg["audio_events"], "external": external['14_audio_events']},
                          lambda: sound_events(ctx, audio, transcript),
                          code_files=["audio.py", "core.py"])
        semantic = ctx.step("15_semantic", {'config':cfg["semantic_analysis"],'model_fingerprint':model_fingerprints['semantic']},
                            lambda: SemanticEngine().run(ctx, transcript),
                            code_files=["semantic.py", "editorial.py", "ollama_local.py", "core.py"])

        # Legacy timeline remains available for the existing Curator contract.
        mappings = active.get("mappings", [])
        timeline = build_timeline(metadata, transcript, scenes, semantic.get("topics", []),
                                  vision, mappings, diarization)
        semantic = enrich_editorial(semantic, timeline, mappings, transcript)
        enrich_scenes(scenes, vision, metadata)
        captions_data = captions(transcript["words"], cfg["captions"])

        understanding = ctx.step(
            "16_understanding", cfg["understanding"],
            lambda: run_understanding(ctx, metadata, transcript, diarization, vision, active,
                                      semantic, shots, cfg["understanding"]),
            code_files=["understanding.py", "story_recovery.py", "semantic.py", "editorial.py", "core.py"])
        master_data = ctx.step(
            "17_master_timeline", {"schema": "2.0"},
            lambda: build_master_timeline(metadata, transcript, scenes, semantic.get("topics", []),
                                          semantic.get("questions_answers", []),
                                          understanding.get("story_arcs", []), camera_timeline,
                                          active.get("intervals", [])),
            code_files=["master_timeline.py", "core.py"])
        master_timeline = master_data.get("timeline", [])
        from .broadcast_graphics import inspect_candidate_graphics
        graphics_candidates = understanding.get('main_moments', [])
        graphics = ctx.step('17b_broadcast_graphics',
            {'ranges': digest([{k: r.get(k) for k in ('moment_id', 'start', 'end', 'editorial_score')} for r in graphics_candidates]),
             'limit': cfg['export']['second_curation_visual_candidate_limit']},
            lambda: ok(inspect_candidate_graphics(ctx.video, graphics_candidates,
                       cfg['export']['second_curation_visual_candidate_limit'])),
            code_files=['broadcast_graphics.py'], requires=['16_understanding'])
        vision['broadcast_graphics'] = graphics
        from .commercial_gate import targeted_ocr, apply_commercial_refinement
        commercial_visual = ctx.step('17c_commercial_visual',
            {'ranges': digest(graphics_candidates), 'ocr': cfg['ocr'], 'limit': cfg['export']['second_curation_visual_candidate_limit']},
            lambda: ok(targeted_ocr(ctx.video, graphics_candidates, cfg['ocr'], cfg['export']['second_curation_visual_candidate_limit'])),
            code_files=['commercial_gate.py'], requires=['16_understanding'])
        understanding = apply_commercial_refinement(understanding, transcript['segments'],
            [{**r, 'source': 'ocr'} for r in ocr.get('texts', [])] + commercial_visual.get('texts', []), cfg['understanding'])
        from .targeted_asr import run_targeted_repair
        targeted_asr = ctx.step('17d_targeted_asr',
            {'config': {k: cfg['transcription'].get(k) for k in ('targeted_repair_enabled', 'targeted_max_regions', 'targeted_max_audio_seconds', 'model', 'beam_size', 'vad_filter', 'glossary', 'import_file')},
             'candidate_ranges': digest(understanding['main_moments']), 'arcs': digest(understanding.get('story_arcs', []))},
            lambda: ok(run_targeted_repair(ctx, audio, transcript, understanding['main_moments'],
                      understanding.get('story_arcs', []), semantic.get('questions_answers', []), metadata['duration'])),
            code_files=['targeted_asr.py'], requires=['04_transcription', '16_understanding'])
        transcript.setdefault('transcription_alternatives', []).extend(targeted_asr.get('alternatives', []))

        for window in metrics.get("quality_windows", []):
            selected = [word for word in transcript["words"]
                        if window["start"] <= word["start"] < window["end"]]
            if selected:
                window["transcription_difficulty"] = sum(x.get("needs_review", False) for x in selected)/len(selected)
                window["difficulty_method"] = "fraction_low_model_probability_words"

        quality = ctx.step(
            "18_analysis_quality", {"schema": "2.0"},
            lambda: build_analysis_quality(metadata, transcript, diarization, vision, active, shots,
                                           semantic, camera_timeline, list(ctx.issues)),
            code_files=["analysis_quality.py", "core.py"])

        camera_plan = run_planner_stage(ctx, metadata, vision, shots, camera_timeline,
                                        active.get("intervals", []), semantic, understanding)
        director = run_director_stage(ctx, metadata, vision, shots, active.get("intervals", []),
                                      motion.get("people", []), semantic, understanding, camera_plan)
        preview = run_preview_stage(ctx, metadata, director, cfg["preview"])
        if preview.get("repaired_timeline"):
            from .preview_verifier import zoom_diagnostics
            delivered_zoom, _ = zoom_diagnostics(preview['repaired_timeline'], metadata['duration'], cfg['camera_director']['smart_zoom']['min_zoom_duration'])
            director = {**director, "timeline": preview["repaired_timeline"],
                        'metrics': {**director.get('metrics', {}), **delivered_zoom,
                                    'proposed_zoom_event_count': len(director.get('zoom_events', []))}}

        analysis_status = "partial" if any(
            s["status"] in ("partial", "unavailable", "failed", "blocked", "cancelled") for s in ctx.states.values()) else "complete"
        if not transcript["words"]:
            ctx.issues.append({"stage": "04_transcription", "status": "partial",
                               "message": "Nenhuma palavra alinhada. Não usar como transcrição completa sem ouvir."})
            analysis_status = "partial"

        analysis = {
            "schema_version": "2.0", "metadata": metadata, "analysis_status": analysis_status,
            "audio_analysis": {**audio, **metrics, **{k: v for k, v in events.items() if k != "events"}},
            "video_analysis": {"metadata": metadata, "quality": vision.get("quality", {}),
                               "frame_samples": vision.get("frames", [])},
            # Legacy contract
            "speakers": diarization.get("speakers", []), "speaker_turns": diarization.get("turns", []),
            "people": vision.get("people", []), "people_observations": vision.get("observations", []),
            "scenes": scenes, "scene_metrics": scene_metrics, "topics": semantic.get("topics", []),
            "words": transcript["words"], "transcript_segments": transcript["segments"],
            "speaker_person_mapping": mappings, "speech_overlaps": diarization.get("overlaps", []),
            "questions_answers": semantic.get("questions_answers", []),
            "question_candidates": semantic.get("question_candidates", []),
            "question_answer_pairs": semantic.get("question_answer_pairs", []),
            "qa_metrics": semantic.get("qa_metrics", {}),
            "program_sections": semantic.get("program_sections", []),
            "primary_editorial_theme": semantic.get("primary_editorial_theme"),
            "secondary_editorial_themes": semantic.get("secondary_editorial_themes", []),
            "topic_quality": semantic.get("topic_quality", {}),
            "semantic_metrics": semantic.get("semantic_metrics", {}),
            "semantic_chunk_profile": semantic.get("semantic_chunk_profile", []),
            "editorial_moments": semantic.get("moments", []),
            "ollama_editorial_review": semantic.get("editorial_review"),
            "candidate_hooks": semantic.get("candidate_hooks", []),
            "candidate_endings": semantic.get("candidate_endings", []),
            "silences": metrics.get("silences", []), "audio_events": events.get("events", []),
            "ocr_text": ocr.get("texts", []), "timeline": timeline,
            "broadcast_graphics": graphics,
            "low_confidence_words": transcript.get("low_confidence_words", []),
            "transcription_alternatives": transcript.get("transcription_alternatives", []),
            "targeted_asr_repair": targeted_asr,
            "unaligned_segments": transcript.get("unaligned_segments", []),
            # v2 perception/understanding contract
            "person_identities": reid.get("identities", []),
            "raw_tracks": reid.get("tracklets", []), "raw_people": vision.get("raw_people", []),
            "tracklet_observations": vision.get("tracklet_observations", []),
            "reid_merge_decisions": reid.get("merge_decisions", []),
            "transcription_quality": transcript.get("quality_metrics", {}),
            "diarization_quality": diarization.get("alignment_metrics", {}),
            "person_motion": motion.get("people", []),
            "speaker_person_summary": active.get("mapping_summary", []),
            "speaker_person_diagnostics": active.get("speaker_person_diagnostics", []),
            "speaker_person_affinity": active.get("affinity", []),
            "active_speaker_evidence": active.get("active_speaker_evidence", []),
            "active_speaker": active.get("intervals", []),
            "shots": shots,
            "camera_timeline": camera_timeline,
            "camera_plan": camera_plan,
            "preview_validation": preview.get("validation", {}),
            "preview_initial_validation": preview.get("initial_validation", {}),
            "preview_canaries": preview.get("canaries", []),
            "preview_closed_loop": preview.get("closed_loop", {}),
            "participants": understanding.get("participants", []),
            "participant_catalog": understanding.get("participant_catalog", []),
            "participant_metrics": understanding.get("participant_metrics", {}),
            "entities": understanding.get("entities", []),
            "story_arcs": understanding.get("story_arcs", []),
            "main_moments": understanding.get("main_moments", []),
            "candidate_metrics": understanding.get("candidate_metrics", {}),
            "editorial_shortlist": understanding.get("editorial_shortlist", []),
            "thumbnail_candidates": understanding.get("thumbnail_candidates", []),
            "moment_frames": understanding.get("moment_frames", []),
            "video_understanding": understanding.get("video_understanding"),
            "master_timeline": master_timeline,
            "analysis_quality": quality,
            "transcription_provenance": {k: transcript.get(k) for k in
                ("engine", "model", "device", "compute_type", "source", "source_comparisons",
                 "timestamp_method", "confidence_is_calibrated", "word_timestamps_are_estimates")},
            "semantic_provenance": {k: semantic.get(k) for k in
                ("requested_backend", "resolved_model", "profile", "ollama_reachable_at_start",
                 "ollama_version", "ollama_call_count", "ollama_calls", "global_review_call",
                 "heuristic_chunks", "total_chunks", "editorial_metrics_are_subjective")},
            "issues": ctx.issues, "stage_status": dict(ctx.states), "stage_runtime": dict(ctx.stage_metrics),
            "no_final_video_rendered": True,
        }

        attach_director(analysis, director)
        # Generated by GitHub Copilot - Oct-05-2026
        analysis['analysis_quality'].update(shot_data.get('metrics',{}))
        analysis['analysis_quality'].update(understanding.get('candidate_metrics',{}))
        analysis['analysis_quality']['editorial_participant_count']=len(analysis.get('participants',[]))
        analysis['vision_performance']=vision.get('performance',{})
        analysis['provenance']={'producer_version':__version__,'build_label':__build__,'config_digest':__import__('ldporto.core',fromlist=['digest']).digest(cfg),
                    'source_hash':signature,'python':__import__('sys').version.split()[0],
                    'platform':__import__('platform').platform(),'model_names':{
                    'asr':cfg['transcription']['model'],'diarization':cfg['diarization']['model'],'semantic':cfg['semantic_analysis']['model']},
                    'external_fingerprints':external,'runtime_target':{'os':'Windows 10/11','python':'3.11.x'}}
        analysis['provenance']['model_fingerprints']=model_fingerprints
        from .run_status import build_run_manifest
        analysis["run_manifest"] = build_run_manifest(metadata, analysis["stage_status"], analysis["issues"])
        analysis["analysis_status"] = analysis["run_manifest"]["analysis_status"]

        # Exports are cheap and rewritten even after cache reuse; never trust missing old reports.
        result = ReportEngine().run(ctx, analysis, captions_data)["data"]
        logger.info("Finalizado (%s). Arquivo principal: %s", analysis_status, result["insights"])
        return destination, analysis


def enrich_scenes(scenes, vision, metadata):
    frames_by_scene, obs_by_scene = defaultdict(list), defaultdict(list)
    for f in vision.get("frames", []):
        frames_by_scene[f["scene_id"]].append(f)
    for o in vision.get("observations", []):
        obs_by_scene[o["scene_id"]].append(o)
    thumb_map = {t["time"]: t["path"] for t in vision.get("thumbnails", []) if t["reason"] == "scene_start"}
    for scene in scenes:
        frames, obs = frames_by_scene[scene["scene_id"]], obs_by_scene[scene["scene_id"]]
        counts = Counter(o["person_id"] for o in obs)
        scene["visible_people"] = sorted(counts)
        scene["predominant_person"] = counts.most_common(1)[0][0] if counts else None
        # Legacy scene_type remains for compatibility; v2 uses shots.json for camera shot classification.
        max_people = max((len(f["visible_people"]) for f in frames), default=0)
        if max_people > 2:
            scene["scene_type"] = "group"
        elif max_people == 2:
            scene["scene_type"] = "two_shot"
        elif obs:
            face_sizes = [o["face_bbox"]["height"] for o in obs if o.get("face_bbox")]
            scene["scene_type"] = "close_up" if face_sizes and max(face_sizes) > 0.4 else "medium_shot"
        scene["shot_type_method"] = "sampled_geometry" if obs else "unknown"
        scene["shot_type_inference"] = bool(obs)
        for f in frames:
            if f["time"] in thumb_map:
                scene["keyframe"] = thumb_map[f["time"]]
                break
