"""Causal stage-status summary for reproducible runs."""
from .core import digest

# Generated by GitHub Copilot - Oct-05-2026
DEPENDENCIES = {
    '01_metadata': [],
    '02_audio': ['01_metadata'],
    '03_audio_quality': ['01_metadata', '02_audio'],
    '04_transcription': ['01_metadata', '02_audio', '03_audio_quality'],
    '05_diarization': ['01_metadata', '02_audio'],
    '06_scenes': ['01_metadata'],
    '07_people_tracking': ['01_metadata', '04_transcription', '06_scenes'],
    '08_person_reid': ['07_people_tracking'],
    '09_person_motion': ['08_person_reid'],
    '10_active_speaker': ['02_audio', '05_diarization', '08_person_reid'],
    '11_shots': ['06_scenes', '08_person_reid'],
    '12_camera_timeline': ['08_person_reid', '09_person_motion', '10_active_speaker', '11_shots'],
    '13_ocr': ['07_people_tracking'],
    '14_audio_events': ['02_audio', '04_transcription'],
    '15_semantic': ['04_transcription', '05_diarization'],
    '16_understanding': ['04_transcription', '05_diarization', '08_person_reid', '10_active_speaker', '11_shots', '15_semantic'],
    '17_master_timeline': ['04_transcription', '05_diarization', '12_camera_timeline', '15_semantic', '16_understanding'],
    '18_analysis_quality': ['04_transcription', '05_diarization', '08_person_reid', '10_active_speaker', '11_shots', '12_camera_timeline', '15_semantic'],
    '18b_global_camera_planner': ['12_camera_timeline', '15_semantic', '16_understanding'],
    '19_camera_director': ['18b_global_camera_planner', '12_camera_timeline'],
    '19b_preview_verifier': ['19_camera_director'],
    '20_handoff': ['18_analysis_quality', '16_understanding', '19_camera_director', '19b_preview_verifier'],
}
STAGE_PACKAGES = {
    '04_transcription': {'numpy', 'faster-whisper', 'ctranslate2'},
    '05_diarization': {'numpy', 'pyannote.audio', 'torch', 'torchaudio', 'torchcodec'},
    '06_scenes': {'scenedetect', 'opencv-contrib-python', 'opencv-python'},
    '07_people_tracking': {'numpy', 'opencv-contrib-python', 'opencv-python', 'mediapipe', 'ultralytics'},
    '13_ocr': {'pytesseract'}, '14_audio_events': {'panns-inference', 'torch'},
}


def _children(stage):
    return sorted(name for name, deps in DEPENDENCIES.items() if stage in deps)


def descendants(stage):
    out, queue = [], [stage]
    while queue:
        parent = queue.pop(0)
        for child in _children(parent):
            if child not in out:
                out.append(child); queue.append(child)
    return out


# Generated by GitHub Copilot - Oct-05-2026
def build_run_manifest(metadata, stage_status, issues):
    """Distinguish direct failures, degraded descendants and unaffected valid modules."""
    states = {k: dict(v) for k, v in stage_status.items()}
    hard_failures = [k for k, v in states.items() if v.get('status') == 'failed']
    unavailable = [k for k, v in states.items() if v.get('status') == 'unavailable']
    blocked = [k for k, v in states.items() if v.get('status') == 'blocked']
    direct = sorted(set(hard_failures + unavailable + [key for key, state in states.items() if state.get('status') == 'cancelled']))
    root = direct[0] if direct else None
    causes = {child: [] for stage in direct for child in descendants(stage) if child in states}
    for stage in direct:
        for child in descendants(stage):
            if child in causes:
                causes[child].append(stage)
    affected = sorted(causes)
    degraded = []
    source_preserving = []
    for name, state in states.items():
        if name in causes and name not in direct and state.get('status') not in ('skipped', 'blocked'):
            state['effective_status'] = 'source_preservation_fallback' if name in ('12_camera_timeline', '18b_global_camera_planner', '19_camera_director') else 'degraded_by_missing_capability'
            state['dependency_reasons'] = [{'stage': stage, 'status': states[stage].get('status')} for stage in causes[name]]
            degraded.append(name)
            if state['effective_status'] == 'source_preservation_fallback':
                source_preserving.append(name)
        else:
            state['effective_status'] = state.get('status')
    valid = [name for name, state in states.items() if state.get('status') == 'ok' and name not in causes]
    first_reprocess = root or (blocked[0] if blocked else None)
    return {
        'schema_version': '1.0',
        'run_id': (metadata.get('sha256') or digest(metadata))[:16],
        'analyzer_version': metadata.get('analyzer_version'),
        'analysis_status': 'partial' if any(v.get('status') in ('partial','unavailable','failed','blocked','cancelled') for v in states.values()) else 'complete',
        'root_cause_stage': root,
        'root_cause_status': states.get(root, {}).get('status') if root else None,
        'descendants_affected': affected,
        'modules_still_valid': valid,
        'direct_failures': direct,
        'degraded_descendants': degraded,
        'partially_valid_modules': [name for name, state in states.items() if state.get('status') == 'partial'],
        'unaffected_modules': [name for name in states if name not in causes and name not in direct],
        'source_preserving_fallback_modules': source_preserving,
        'dependency_reasons': causes,
        'unavailable_capabilities': unavailable,
        'blocked_stages': blocked,
        'recommended_action': (f'Reprocessar a partir de {first_reprocess} após corrigir a causa raiz.' if first_reprocess else 'Nenhuma falha causal registrada.'),
        'first_stage_to_reprocess': first_reprocess,
        'stage_status': states,
        'issues': issues,
    }
