from collections import Counter, defaultdict
from pathlib import Path
import math
import re
from .core import ok, overlap, run_command
from .editorial import (GENERIC_TERMS, fold_text, normalize_moment, optimize_boundaries,
                        rank_candidate, deduplicate_candidates, classify_content)

_CAP = r"[A-ZÁÀÂÃÉÊÍÓÔÕÚÜÇ][A-Za-zÀ-ÖØ-öø-ÿ0-9'’_-]*"
_NAME = rf"{_CAP}(?:\s+{_CAP}){{0,4}}"
_CUES = {
    "artist_or_band": r"(?:banda|grupo|cantor(?:a)?|artista)",
    "song": r"(?:música|musica|canção|cancao|faixa)",
    "album": r"(?:álbum|album|disco)",
    "company": r"(?:empresa|companhia|gravadora|marca)",
    "program": r"(?:programa|podcast|rádio|radio|canal)",
    "place": r"(?:cidade|estado|país|pais|bairro)",
    "person": r"(?:senhor|senhora|doutor|doutora|professor|professora|apresentador|apresentadora)",
}


def extract_entities(transcript):
    """Conservative textual entities. No external recognition or face naming."""
    found = {}
    for segment in transcript.get("segments", []):
        text = segment.get("text") or ""
        for entity_type, cue in _CUES.items():
            pattern = re.compile(rf"(?i:\b{cue})\s+(?:(?i:do|da|de|o|a)\s+)?({_NAME})")
            for match in pattern.finditer(text):
                name = match.group(1).strip(" .,;:!?\"'()[]")
                # Generated by GitHub Copilot - Oct-05-2026
                if not entity_name_valid(name):
                    continue
                key = (name.casefold(), entity_type)
                row = found.setdefault(key, {"name": name, "type": entity_type,
                                             "mentions": 0, "first_time": segment["start"],
                                             "evidence_segment_ids": [], "confidence": None,
                                             "source": "transcript_textual_cue", "inference": True})
                row["method"] = "strong_textual_cue"
                row["confidence_is_calibrated"] = False
                row["mentions"] += 1
                row["first_time"] = min(row["first_time"], segment["start"])
                if segment["segment_id"] not in row["evidence_segment_ids"]:
                    row["evidence_segment_ids"].append(segment["segment_id"])
        # Explicit self-introduction is strong textual evidence for a name mention.
        intro = re.search(rf"(?i:\b(?:eu sou|me chamo|meu nome é|meu nome e))\s+({_NAME})", text)
        if intro:
            name = intro.group(1).strip(" .,;:!?\"'()[]")
            if not entity_name_valid(name):
                continue
            key = (name.casefold(), "person")
            row = found.setdefault(key, {"name": name, "type": "person", "mentions": 0,
                                         "first_time": segment["start"], "evidence_segment_ids": [],
                                         "confidence": 0.95, "source": "explicit_self_introduction",
                                         "inference": False})
            row["method"] = "explicit_self_introduction"
            row["confidence_is_calibrated"] = False
            row["mentions"] += 1
            if segment["segment_id"] not in row["evidence_segment_ids"]:
                row["evidence_segment_ids"].append(segment["segment_id"])
    rows = sorted(found.values(), key=lambda r: (-r["mentions"], r["first_time"], r["name"].casefold()))
    return rows


# Generated by GitHub Copilot - Oct-05-2026
def entity_name_valid(name):
    """Reject PT-BR pronouns, common verbs and sentence-initial false positives."""
    words = re.findall(r"\w+", fold_text(name))
    return bool(words and len(name) >= 2 and words[0] not in GENERIC_TERMS and
                not all(word in GENERIC_TERMS for word in words))


def _speaker_name_evidence(transcript):
    out = {}
    for s in transcript.get("segments", []):
        if not s.get("speaker"):
            continue
        match = re.search(rf"(?i:\b(?:eu sou|me chamo|meu nome é|meu nome e))\s+({_NAME})", s.get("text", ""))
        if match and entity_name_valid(match.group(1)):
            out.setdefault(s["speaker"], {"possible_name": match.group(1).strip(" .,;:!?"),
                                          "name_source": "explicit_self_introduction",
                                          "name_evidence_segment_id": s["segment_id"],
                                          "name_confidence": 0.95})
    return out


# Generated by GitHub Copilot - Oct-05-2026
def build_participants(transcript, diarization, vision, mapping_summary, questions_answers, cfg=None, shots=None, include_background=False):
    """Separate editorial participants from raw tracks and anonymous visual candidates."""
    cfg = cfg or {}
    shots = shots or []
    min_visual = cfg.get("participant_min_visual_seconds", 8.0)
    min_observations = cfg.get("participant_min_observations", 12)
    min_speech = cfg.get("participant_min_speech_seconds", 3.0)
    min_shots = cfg.get("participant_min_distinct_shots", 2)
    speaker_to_person = {r["speaker_id"]: r.get("person_id") for r in mapping_summary if r.get("person_id")}
    person_to_speakers = defaultdict(list)
    for speaker, person in speaker_to_person.items():
        person_to_speakers[person].append(speaker)
    speech = {s["speaker_id"]: s.get("speech_seconds") for s in diarization.get("speakers", [])}
    q_count = Counter(q.get("question_speaker") for q in questions_answers if q.get("question_speaker"))
    a_count = Counter(q.get("answer_speaker") for q in questions_answers if q.get("answer_speaker"))
    names = _speaker_name_evidence(transcript)
    participants = []
    known_people = {p["person_id"]: p for p in vision.get("people", [])}

    for person_id, person in sorted(known_people.items()):
        speakers = sorted(person_to_speakers.get(person_id, []))
        visual_seconds = person.get("total_visual_seconds", 0.0) or 0.0
        observations = person.get("observation_count", 0) or 0
        distinct_shots = len(person.get("scene_ids", []))
        speech_seconds = sum(speech.get(speaker) or 0 for speaker in speakers)
        confirmed = speech_seconds >= min_speech
        likely = visual_seconds >= min_visual and observations >= min_observations and (
                 distinct_shots >= min_shots or visual_seconds >= 4 * min_visual)
        status = ("confirmed_editorial_participant" if confirmed else "likely_visual_participant" if likely else
                  "background_person" if visual_seconds >= 1 else "insufficient_evidence")
        if not confirmed and not likely and not include_background:
            continue
        questions = sum(q_count[s] for s in speakers)
        answers = sum(a_count[s] for s in speakers)
        role = "unknown"
        role_confidence = None
        role_evidence = []
        if questions >= 3 and questions >= max(2, answers*2):
            role, role_confidence = "likely_host", min(0.85, 0.55+0.05*questions)
            role_evidence = ["repeated_questions"]
        elif answers >= 3 and answers >= max(2, questions*2):
            role, role_confidence = "likely_guest", min(0.80, 0.50+0.05*answers)
            role_evidence = ["repeated_answers"]
        name_rows = [names[s] for s in speakers if s in names]
        name = name_rows[0] if name_rows else {}
        participants.append({
            "participant_id": f"PARTICIPANT_{len(participants):04}", "status": status,
            "person_id": person_id, "speaker_ids": speakers,
            "total_visual_seconds": visual_seconds, "distinct_shots": distinct_shots,
            "first_seen": person.get("first_seen"), "last_seen": person.get("last_seen"),
            "observation_count": person.get("observation_count"),
            "speech_seconds": sum(speech.get(s) or 0 for s in speakers) if speakers else None,
            "question_count": questions, "answer_count": answers,
            "role": role, "role_confidence": role_confidence, "role_evidence": role_evidence,
            "possible_name": name.get("possible_name"), "name_source": name.get("name_source"),
            "name_evidence_segment_id": name.get("name_evidence_segment_id"),
            "name_confidence": name.get("name_confidence"),
            "civil_identity_inferred": False,
        })
    mapped_speakers = {s for p in participants for s in p["speaker_ids"]}
    for speaker_id in sorted(speech):
        if speaker_id in mapped_speakers:
            continue
        if (speech[speaker_id] or 0) < min_speech and not include_background:
            continue
        name = names.get(speaker_id, {})
        participants.append({
            "participant_id": f"PARTICIPANT_{len(participants):04}",
            "status": "confirmed_editorial_participant" if (speech[speaker_id] or 0) >= min_speech else "insufficient_evidence",
            "person_id": None, "speaker_ids": [speaker_id], "first_seen": None, "last_seen": None,
            "observation_count": None, "speech_seconds": speech.get(speaker_id),
            "question_count": q_count[speaker_id], "answer_count": a_count[speaker_id],
            "role": "unknown", "role_confidence": None, "role_evidence": [],
            "possible_name": name.get("possible_name"), "name_source": name.get("name_source"),
            "name_evidence_segment_id": name.get("name_evidence_segment_id"),
            "name_confidence": name.get("name_confidence"), "civil_identity_inferred": False,
        })
    return participants


# Generated by GitHub Copilot - Oct-05-2026
def build_story_arcs(transcript, topics, questions_answers=None):
    """Keep marker-supported narratives and explicit unresolved discussion-arc candidates."""
    by_id = {s["segment_id"]: s for s in transcript.get("segments", [])}
    arcs = []
    conflict_re = re.compile(r"\b(mas|só que|so que|porém|porem|problema|dificuldade|errado|não deu|nao deu)\b", re.I)
    payoff_re = re.compile(r"\b(no fim|no final|acabou|consegui|deu certo|resultado|virou|aí deu|ai deu)\b", re.I)
    setup_re = re.compile(r"\b(quando|na época|na epoca|um dia|começou|comecou|aconteceu)\b", re.I)
    for topic in topics:
        segments = [by_id[sid] for sid in topic.get("evidence_segment_ids", []) if sid in by_id]
        if len(segments) < 3:
            continue
        setup = next((s for s in segments if setup_re.search(s["text"])), segments[0])
        conflict = next((s for s in segments if conflict_re.search(s["text"])), None)
        payoff = next((s for s in reversed(segments) if payoff_re.search(s["text"])), None)
        complete_qa = next((pair for pair in questions_answers or [] if pair.get("question_answer_complete") and
                            topic["start"] <= pair["question_start"] and pair["answer_end"] <= topic["end"]), None)
        marker_supported = conflict is not None and payoff is not None and payoff["start"] > conflict["start"]
        if not marker_supported:
            conflict, payoff = None, None
            setup = segments[0]
            if complete_qa:
                payoff = by_id.get(complete_qa["answer_segment_ids"][-1])
        if classify_content(" ".join(segment["text"] for segment in segments))["content_type"] in {"advertisement", "sponsor_read", "merchandising"}:
            continue
        middle = [segment for segment in segments[1:-1] if not payoff or segment["start"] < payoff["start"]]
        ending = segments[-1]
        duration = ending["end"]-setup["start"]
        if duration < 8:
            continue
        complete = ending["text"].rstrip().endswith((".", "?", "!"))
        score = min(1.0, 0.55 + 0.10*bool(setup) + 0.15*bool(middle) + 0.15*complete)
        arcs.append({
            "story_arc_id": f"STORY_{len(arcs):04}", "topic_id": topic.get("topic_id"),
            "topic_ids": [topic.get("topic_id")], "section_id": None,
            "title": topic.get("topic"), "summary": topic.get("summary"),
            "evidence_segment_ids": [segment["segment_id"] for segment in segments],
            "start": setup["start"], "end": ending["end"],
            "setup": {"text": setup["text"], "segment_ids": [setup["segment_id"]]},
            "conflict": {"text": conflict["text"], "segment_ids": [conflict["segment_id"]]} if conflict else None,
            "development": {"text": " ".join(s["text"] for s in middle) or None,
                            "segment_ids": [s["segment_id"] for s in middle]},
            "payoff": {"text": payoff["text"], "segment_ids": [payoff["segment_id"]]} if payoff else None,
            "ending": {"text": ending["text"], "segment_ids": [ending["segment_id"]]},
            "standalone_score": score if marker_supported or complete_qa else None,
            "completeness": "supported_setup_development_payoff" if marker_supported or complete_qa else "unresolved_payoff",
            "method": "narrative_marker_heuristic" if marker_supported else "grounded_qa_arc" if complete_qa else "discussion_section_candidate",
            "inference": True,
            "confidence": None, "needs_review": True,
        })
    return arcs


def _score_class(value):
    return {"excellent": 0.95, "good": 0.78, "needs_context": 0.45, "poor": 0.20}.get(value)


# Generated by GitHub Copilot - Oct-05-2026
def build_main_moments(transcript, topics, moments, questions_answers, story_arcs, shots, editorial_review=None, cfg=None):
    """Optimize grounded boundaries then rank and deduplicate editorial candidates."""
    cfg = cfg or {}
    segments = transcript.get("segments", [])
    review_scores = {r["moment_id"]: r.get("editorial_score")
                     for r in (editorial_review or {}).get("top_moments", [])}
    result = []
    for original in moments:
        moment = normalize_moment(original)
        start, end = moment["start"], moment["end"]
        topic = next((t for t in topics if overlap(start, end, t["start"], t["end"]) > 0), None)
        lo = max(0.0, start-30.0, topic["start"] if topic else 0.0)
        hi = min((segments[-1]["end"] if segments else end), end+30.0,
                 topic["end"] if topic else (segments[-1]["end"] if segments else end+30.0))
        story = next((arc for arc in story_arcs if overlap(start, end, arc["start"], arc["end"]) > 0), None)
        boundaries = optimize_boundaries(moment, segments, cfg, story)
        ideal_start, ideal_end = boundaries["ideal_start"], boundaries["ideal_end"]
        q_complete = any(q.get("answer_end") is not None and q["question_start"] >= ideal_start and
                         q["answer_end"] <= ideal_end for q in questions_answers)
        visual = [s.get("camera_score") for s in shots if overlap(start, end, s["start"], s["end"]) > 0 and
                  isinstance(s.get("camera_score"), (int, float))]
        ed = moment.get("editorial") or {}
        cats = set(moment.get("categories") or [])
        available = [v for v in ed.values() if isinstance(v, (int, float))]
        editorial_score = review_scores.get(moment["moment_id"])
        if editorial_score is None:
            editorial_score = sum(available)/len(available) if available else None
        result.append({
            "moment_id": moment["moment_id"],
            "topic_id": topic.get("topic_id") if topic else None,
            "story_arc_id": story.get("story_arc_id") if story else None,
            "core_moment": {"start": start, "end": end, "text": moment.get("text")},
            "possible_start": max(lo, start-10.0), "ideal_start": ideal_start,
            "possible_end": min(hi, end+10.0), "ideal_end": ideal_end,
            "context_required": moment.get("context_required"),
            "context_requirement": moment["context_requirement"], "context_reason": moment["context_reason"],
            "context_seconds_before": boundaries["context_added_before"], "context_seconds_after": boundaries["context_added_after"],
            "content_type": moment["content_type"], "commercial_score": moment["commercial_score"],
            "commercial_classification": moment["commercial_classification"],
            "metadata_locale": "pt-BR", **boundaries,
            "recommended_context_seconds": max(0.0, ideal_end-ideal_start),
            "standalone_score": _score_class(moment.get("standalone_class")),
            "hook_strength": ed.get("hook_strength"),
            "ending_strength": 1.0 if moment.get("complete_sentence") else 0.35,
            "story_completeness": story.get("standalone_score") if story else None,
            "question_answer_complete": q_complete,
            "editorial_score": editorial_score,
            "story_score": story.get("standalone_score") if story else None,
            "hook_score": ed.get("hook_strength"),
            "information_score": ed.get("clarity"),
            "nostalgia_score": None,
            "surprise_score": ed.get("curiosity") if "surprise" in cats else None,
            "conflict_score": ed.get("controversy") if "conflict" in cats else None,
            "visual_score": sum(visual)/len(visual) if visual else None,
            "evidence_segment_ids": moment.get("evidence_segment_ids", []),
            "categories": sorted(cats), "method": "grounded_sentence_story_boundaries_and_weighted_utility",
            "inference": True, "needs_review": True,
        })
    ranked = [rank_candidate(candidate, cfg) for candidate in result]
    return deduplicate_candidates(ranked)[0]


# Generated by GitHub Copilot - Oct-05-2026
def build_thumbnail_candidates(vision, shots, max_candidates=80, main_moments=None):
    """Prioritize editorial timing and meaningful anonymous presence, not new raw IDs."""
    shot_by_scene = {s.get("scene_id"): s for s in shots}
    obs_by_time = defaultdict(list)
    for obs in vision.get("observations", []):
        obs_by_time[obs["time"]].append(obs)
    rows = []
    seen = set()
    meaningful={person['person_id'] for person in vision.get('people',[]) if person.get('meaningful')}
    for thumb in vision.get("thumbnails", []):
        # Generated by GitHub Copilot - Oct-05-2026
        if thumb.get("reason") == "new_person":
            continue
        time = float(thumb["time"])
        if time in seen:
            continue
        seen.add(time)
        obs = obs_by_time.get(time, [])
        scene = obs[0].get("scene_id") if obs else None
        shot = shot_by_scene.get(scene)
        face_sizes = [o.get("face_height") for o in obs if o.get("face_height") is not None]
        left_space = min((o["face_bbox"]["x"] for o in obs if o.get("face_bbox")), default=None)
        right_space = min((1-o["face_bbox"]["x"]-o["face_bbox"]["width"] for o in obs if o.get("face_bbox")), default=None)
        rows.append({
            "time": time, "path": thumb.get("path"), "reason": thumb.get("reason"),
            "shot_id": shot.get("shot_id") if shot else None,
            "person_ids": sorted({o.get("person_id") for o in obs if o.get("person_id")}),
            "sharpness": shot.get("sharpness_score") if shot else None,
            "motion_blur": shot.get("motion_blur_score") if shot else None,
            "face_size": max(face_sizes) if face_sizes else None,
            "eyes_open": None,
            "composition": shot.get("composition_score") if shot else None,
            "negative_space_left": left_space,
            "negative_space_right": right_space,
            "thumbnail_score": shot.get("thumbnail_score") if shot else None,
            "evidence": ["saved_visual_sample"],
            "editorial_moment_ids":[moment['moment_id'] for moment in main_moments or [] if
                                     moment['ideal_start']<=time<=moment['ideal_end']],
            "meaningful_person_present":any(observation.get('person_id') in meaningful for observation in obs),
        })
    rows.sort(key=lambda row:(bool(row['editorial_moment_ids']),row['meaningful_person_present'],
                              row.get('thumbnail_score') is not None,row.get('thumbnail_score') or -1,-row['time']),reverse=True)
    return rows[:int(max_candidates)]


def extract_moment_frames(ctx, main_moments, thumbnail_candidates, cfg):
    if not cfg.get("extract_frames", True):
        return []
    limit = int(cfg.get("max_moments", 12))
    out = []
    root = ctx.output / "moment_frames"
    root.mkdir(parents=True, exist_ok=True)
    for moment in main_moments[:limit]:
        mid = moment["moment_id"]
        if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_.-]{0,100}',mid) or '..' in mid:
            raise ValueError('ID de momento inseguro para extracao de frames.')
        if not moment.get('default_shortlist_eligible',True):
            continue
        folder = root / mid
        folder.mkdir(exist_ok=True)
        start = float(moment["ideal_start"])
        core = moment["core_moment"]
        candidates = [t for t in thumbnail_candidates if core["start"]-5 <= t["time"] <= core["end"]+5]
        best = max(candidates, key=lambda r: r.get("thumbnail_score") or -1, default=None)
        best_t = best["time"] if best else (core["start"]+core["end"])/2
        clean_t = core["end"] if core["end"] > core["start"] else best_t
        files = {}
        for name, timestamp in (("opening_frame.jpg", start), ("best_frame.jpg", best_t), ("clean_frame.jpg", clean_t)):
            path = folder / name
            run_command(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-ss", f"{timestamp:.3f}",
                         "-i", str(ctx.video), "-frames:v", "1", "-q:v", "2", str(path)])
            files[name] = str(path.relative_to(ctx.output)).replace("\\", "/")
        out.append({"moment_id": mid, "frames": files})
    return out


def build_video_understanding(metadata, transcript, topics, participants, entities, story_arcs,
                              main_moments, questions_answers, shots):
    top_topics = sorted(topics, key=lambda t: t.get("end", 0)-t.get("start", 0), reverse=True)
    top_entities = sorted(entities, key=lambda e: (-e.get("mentions", 0), e.get("first_time", 0)))
    speech_participants = sorted(participants, key=lambda p: p.get("speech_seconds") or 0, reverse=True)
    about = None
    if top_topics:
        qualified=[topic for topic in top_topics if topic.get('method')=='ollama' and topic.get('content_type') not in
                   ('advertisement','sponsor_read','merchandising')]
        if qualified:
            about=qualified[0].get('summary') or qualified[0].get('topic')
    dense = sorted(main_moments, key=lambda m: m.get("information_score") or -1, reverse=True)[:10]
    best_image = sorted(shots, key=lambda s: s.get("camera_score") or -1, reverse=True)[:10]
    return {
        "about": about,
        "duration": metadata.get("duration"),
        "main_topics": top_topics[:12],
        "main_participants": speech_participants[:10],
        "top_entities": top_entities[:30],
        "story_arcs": story_arcs,
        "main_moments": main_moments[:30],
        "questions_answers": questions_answers,
        "high_information_sections": [m["moment_id"] for m in dense if m.get("information_score") is not None],
        "best_visual_shots": [s["shot_id"] for s in best_image if s.get("camera_score") is not None],
        "method": "derived_from_grounded_analyzer_artifacts",
        "inference": True,
    }


def run_understanding(ctx, metadata, transcript, diarization, vision, active_data, semantic, shots, cfg):
    entities = extract_entities(transcript)
    qas = semantic.get("questions_answers", [])
    participants = build_participants(transcript, diarization, vision,
                                      active_data.get("mapping_summary", []), qas, cfg, shots)
    story_arcs = build_story_arcs(transcript, semantic.get("topics", []), qas)
    section_by_topic = {topic_id: section["section_id"] for section in semantic.get("program_sections", []) for topic_id in section["topic_ids"]}
    for arc in story_arcs:
        arc["section_id"] = section_by_topic.get(arc.get("topic_id"))
    main_moments = build_main_moments(transcript, semantic.get("topics", []), semantic.get("moments", []),
                                      qas, story_arcs, shots, semantic.get("editorial_review"), cfg)
    for candidate in main_moments:
        candidate["program_section_id"] = section_by_topic.get(candidate.get("topic_id"))
    candidate_metrics = {"candidates_before_dedup": len(semantic.get("moments", [])),
                         "candidates_after_dedup": len(main_moments),
                         "alternate_count": sum(len(candidate.get("alternates", [])) for candidate in main_moments),
                         "excluded_commercial_count": sum(not candidate.get("default_shortlist_eligible", True) for candidate in main_moments),
                         "final_shortlist_count": sum(candidate.get("default_shortlist_eligible", True) for candidate in main_moments[:cfg.get("max_moments", 12)])}
    thumbnails = build_thumbnail_candidates(vision, shots, cfg.get("max_thumbnail_candidates", 80),
                    [moment for moment in main_moments if moment.get('default_shortlist_eligible',True)][:cfg.get('max_moments',12)])
    moment_frames = []
    try:
        moment_frames = extract_moment_frames(ctx, main_moments, thumbnails, cfg)
    except Exception as exc:
        ctx.logger.warning("Frames dos momentos: %s: %s", type(exc).__name__, exc)
    video_understanding = build_video_understanding(metadata, transcript, semantic.get("topics", []),
                                                   participants, entities, story_arcs, main_moments, qas, shots)
    notes = ["Entidades são extraídas apenas de evidência textual; nomes não são inferidos por rosto.",
             "Story arcs e papéis host/guest são heurísticas conservadoras e permanecem needs_review."]
    artifacts = []
    for row in moment_frames:
        for relative in (row.get("frames") or {}).values():
            artifacts.append(ctx.output / relative)
    return ok({"entities": entities, "participants": participants, "story_arcs": story_arcs,
               "candidate_metrics": candidate_metrics,
               "editorial_shortlist": [candidate["moment_id"] for candidate in main_moments if candidate.get("default_shortlist_eligible", True)][:cfg.get("max_moments", 12)],
               "main_moments": main_moments, "thumbnail_candidates": thumbnails,
               "moment_frames": moment_frames, "video_understanding": video_understanding},
              "ok" if transcript.get("segments") else "partial", notes, artifacts)
