"""Atomic chunk checkpoints for long-running visual perception."""
from pathlib import Path
import numpy as np
import math
from . import __version__
from .core import digest, read_json, write_json, file_hash
from .config import asset_path


class VisionCheckpointStore:
    schema_version = '2.0'

    def __init__(self, ctx, cfg):
        self.ctx = ctx
        self.cfg = cfg
        self.root = ctx.cache/'vision_chunks'
        self.root.mkdir(parents=True, exist_ok=True)
        self.config_hash = digest(cfg)
        # Generated by GitHub Copilot - Oct-05-2026
        module_root=Path(__file__).parent
        self.code_hash=digest({name:file_hash(module_root/name) for name in ('vision.py','vision_checkpoint.py','visual_sampling.py')})
        self.model_hash=digest({name:file_hash(asset_path(cfg[name])) for name in ('yunet_model','sface_model','landmarker_model')
                    if cfg.get(name) and asset_path(cfg[name]).is_file()})

    def _valid(self, payload):
        checksum = payload.get('checksum')
        body = {k:v for k,v in payload.items() if k != 'checksum'}
        return bool(checksum and checksum == digest(body) and
                    payload.get('input_hash') == self.ctx.signature and
                    payload.get('config_hash') == self.config_hash and
                    payload.get('code_hash') == self.code_hash and payload.get('model_hash') == self.model_hash and
                    payload.get('schema_version') == self.schema_version and
                    payload.get('status') == 'complete')

    def load(self):
        if self.ctx.force:
            return None
        observations, frames, thumbnails = [], [], []
        last = None
        expected_index = 0
        previous_checksum=None
        for path in sorted(self.root.glob('chunk_*.json')):
            try:
                payload = read_json(path)
            except (OSError, ValueError):
                break
            if payload.get('chunk_index') != expected_index or not self._valid(payload):
                break
            # Generated by GitHub Copilot - Oct-05-2026
            start,end=payload.get('start'),payload.get('end')
            if (not isinstance(start,(int,float)) or not isinstance(end,(int,float)) or
                    not math.isfinite(start+end) or start < 0 or end <= start or
                    payload.get('previous_checksum') != previous_checksum or
                    (last and abs(start-last['end'])>1e-6)):
                break
            chunk_frames=payload.get('frames',[])
            chunk_observations=payload.get('observations',[])
            if any(not isinstance(row.get('time'),(int,float)) or not math.isfinite(row['time']) or
                   row['time'] < start or row['time'] > end or (last and row['time'] <= start)
                   for row in chunk_frames+chunk_observations):
                break
            if len({row.get('time') for row in chunk_frames}) != len(chunk_frames):
                break
            keys=[(row.get('time'),row.get('track_id') or row.get('person_id')) for row in chunk_observations]
            if len(set(keys)) != len(keys):
                break
            observations.extend(payload.get('observations', []))
            frames.extend(payload.get('frames', []))
            thumbnails.extend(payload.get('thumbnails', []))
            last = payload
            previous_checksum=payload['checksum']
            expected_index += 1
        if last is None:
            return None
        return {
            'next_chunk_index': expected_index,
            'end': float(last['end']), 'observations': observations, 'frames': frames,
            'thumbnails': thumbnails, 'people': last.get('people', {}),
            'tracker': last.get('tracker', {}), 'last_gray': last.get('last_gray'),
            'last_scene': last.get('last_scene'), 'next_sample': float(last.get('next_sample') or last['end']),
            'frame_index': int(last.get('frame_index') or 0),
            'sampling_state':last.get('sampling_state',{}),
        }

    @staticmethod
    def serialize_tracker(tracker):
        def emb(value):
            return value.tolist() if value is not None else None
        tracks = {}
        for pid, row in tracker.tracks.items():
            tracks[pid] = {**row, 'embedding': emb(row.get('embedding'))}
        return {'tracks': tracks, 'gallery': {pid: emb(v) for pid,v in tracker.gallery.items()},
                'next_id': tracker.next_id, 'next_track_id': tracker.next_track_id,
                'completed_tracks': tracker.completed_tracks,
                'association_count': tracker.association_count,
                'conflicting_embedding_count': tracker.conflicting_embedding_count}

    @staticmethod
    def restore_tracker(tracker, payload):
        tracker.tracks = {}
        for pid, row in (payload.get('tracks') or {}).items():
            tracker.tracks[pid] = {**row, 'embedding': np.asarray(row['embedding'], dtype=float) if row.get('embedding') is not None else None}
        tracker.gallery = {pid: np.asarray(v, dtype=float) for pid,v in (payload.get('gallery') or {}).items() if v is not None}
        tracker.next_id = int(payload.get('next_id') or 1)
        tracker.next_track_id = int(payload.get('next_track_id') or 1)
        tracker.completed_tracks = list(payload.get('completed_tracks') or [])
        tracker.association_count = int(payload.get('association_count') or 0)
        tracker.conflicting_embedding_count = int(payload.get('conflicting_embedding_count') or 0)

    def save(self, chunk_index, start, end, observations, frames, thumbnails, people,
             tracker, last_gray, last_scene, next_sample, frame_index, backend, sampling_state=None):
        if end <= start:
            return None
        # Generated by GitHub Copilot - Oct-05-2026
        previous_checksum=None
        if chunk_index:
            previous=read_json(self.root/f'chunk_{chunk_index-1:06d}.json')
            if not self._valid(previous) or abs(previous['end']-start)>1e-6:
                raise ValueError('Checkpoint visual sem predecessor integro e contiguo.')
            previous_checksum=previous['checksum']
        payload = {
            'schema_version': self.schema_version, 'chunk_index': int(chunk_index),
            'start': float(start), 'end': float(end), 'interval_semantics': 'first:[start,end]; next:(start,end]',
            'input_hash': self.ctx.signature, 'config_hash': self.config_hash,
            'implementation_version': __version__, 'backend': backend,
            'code_hash':self.code_hash,'model_hash':self.model_hash,'previous_checksum':previous_checksum,
            'sampling_state':sampling_state or {},
            'status': 'complete', 'observations': observations, 'frames': frames,
            'thumbnails': thumbnails, 'people': people,
            'tracker': self.serialize_tracker(tracker),
            'last_gray': last_gray.tolist() if last_gray is not None else None,
            'last_scene': last_scene, 'next_sample': float(next_sample), 'frame_index': int(frame_index),
        }
        payload['checksum'] = digest(payload)
        target = self.root/f'chunk_{chunk_index:06d}.json'
        write_json(target, payload)
        return target
